// Class: ReadMLP0_25_B
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Sun Aug  9 12:04:00 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 19635


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,24.9091453552]
ClusterParameters.end         ClusterParameters.end             'F'    [0.452642351389,34.9224777222]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,30.2763938904]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,1]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.303021222353,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.000358459714334,0.999999940395]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999999701977]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.0331833958626,15.0479383469]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.00387161248364,0.909888803959]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,56]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [3.42735767365,757226.375]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-10.4946260452,21.9868850708]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP0_25_B : public IClassifierReader {

 public:

   // constructor
   ReadMLP0_25_B( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP0_25_B" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 24.9091453552246;
      fVmin[1] = 0.452642351388931;
      fVmax[1] = 34.922477722168;
      fVmin[2] = 0;
      fVmax[2] = 30.2763938903809;
      fVmin[3] = 0;
      fVmax[3] = 1;
      fVmin[4] = 0;
      fVmax[4] = 1;
      fVmin[5] = 0.303021222352982;
      fVmax[5] = 1;
      fVmin[6] = 0.000358459714334458;
      fVmax[6] = 0.999999940395355;
      fVmin[7] = 0;
      fVmax[7] = 0.999999701976776;
      fVmin[8] = 0.0331833958625793;
      fVmax[8] = 15.0479383468628;
      fVmin[9] = 0.00387161248363554;
      fVmax[9] = 0.909888803958893;
      fVmin[10] = 5;
      fVmax[10] = 56;
      fVmin[11] = 3.42735767364502;
      fVmax[11] = 757226.375;
      fVmin[12] = -10.4946260452271;
      fVmax[12] = 21.9868850708008;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP0_25_B() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP0_25_B::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.699318125737825;
   fWeightMatrix0to1[1][0] = 1.99281361777723;
   fWeightMatrix0to1[2][0] = -0.0166449462435487;
   fWeightMatrix0to1[3][0] = 2.04501685017064;
   fWeightMatrix0to1[4][0] = -6.6698486144051;
   fWeightMatrix0to1[5][0] = -1.87816633996587;
   fWeightMatrix0to1[6][0] = -0.549650181681698;
   fWeightMatrix0to1[7][0] = 4.15138516588465;
   fWeightMatrix0to1[8][0] = -1.28712740117223;
   fWeightMatrix0to1[9][0] = -2.04252219374936;
   fWeightMatrix0to1[10][0] = -1.63929536103151;
   fWeightMatrix0to1[11][0] = -0.00405200634746503;
   fWeightMatrix0to1[12][0] = -3.01092553074311;
   fWeightMatrix0to1[13][0] = -0.51110831689334;
   fWeightMatrix0to1[0][1] = -1.39601961429263;
   fWeightMatrix0to1[1][1] = 0.678197815920599;
   fWeightMatrix0to1[2][1] = -1.11192544601335;
   fWeightMatrix0to1[3][1] = 1.7493468858277;
   fWeightMatrix0to1[4][1] = -1.27057305660029;
   fWeightMatrix0to1[5][1] = 0.984431930424204;
   fWeightMatrix0to1[6][1] = -0.354361536256127;
   fWeightMatrix0to1[7][1] = -0.705716576418084;
   fWeightMatrix0to1[8][1] = 0.403029232607892;
   fWeightMatrix0to1[9][1] = 0.990412784278705;
   fWeightMatrix0to1[10][1] = -1.1886795089141;
   fWeightMatrix0to1[11][1] = 0.0584202290403766;
   fWeightMatrix0to1[12][1] = 1.75726014892899;
   fWeightMatrix0to1[13][1] = 0.272746875763769;
   fWeightMatrix0to1[0][2] = 0.134716112182576;
   fWeightMatrix0to1[1][2] = 0.139438095795504;
   fWeightMatrix0to1[2][2] = 0.0368483695396944;
   fWeightMatrix0to1[3][2] = 1.71725836480441;
   fWeightMatrix0to1[4][2] = -2.23473863106783;
   fWeightMatrix0to1[5][2] = -0.548869146910454;
   fWeightMatrix0to1[6][2] = 0.348875825666473;
   fWeightMatrix0to1[7][2] = 1.31214072274493;
   fWeightMatrix0to1[8][2] = -1.39749565244226;
   fWeightMatrix0to1[9][2] = 0.857652035846392;
   fWeightMatrix0to1[10][2] = -1.19924557179439;
   fWeightMatrix0to1[11][2] = 1.52044044526381;
   fWeightMatrix0to1[12][2] = 1.17957507379809;
   fWeightMatrix0to1[13][2] = 0.708742991505624;
   fWeightMatrix0to1[0][3] = -0.282061467942385;
   fWeightMatrix0to1[1][3] = 1.22077360134841;
   fWeightMatrix0to1[2][3] = -1.52259726943683;
   fWeightMatrix0to1[3][3] = -1.09662859852606;
   fWeightMatrix0to1[4][3] = 0.22235895823831;
   fWeightMatrix0to1[5][3] = -0.033912627904494;
   fWeightMatrix0to1[6][3] = 1.73569430030469;
   fWeightMatrix0to1[7][3] = -0.147533209341278;
   fWeightMatrix0to1[8][3] = -0.054963902253981;
   fWeightMatrix0to1[9][3] = -0.0182336328570107;
   fWeightMatrix0to1[10][3] = -1.64985456186764;
   fWeightMatrix0to1[11][3] = 1.83380986316461;
   fWeightMatrix0to1[12][3] = -0.505034182298211;
   fWeightMatrix0to1[13][3] = -1.64609248685174;
   fWeightMatrix0to1[0][4] = -0.215941344721725;
   fWeightMatrix0to1[1][4] = -1.75518192607862;
   fWeightMatrix0to1[2][4] = 1.23590047136473;
   fWeightMatrix0to1[3][4] = 0.430178418801556;
   fWeightMatrix0to1[4][4] = -0.238158161611695;
   fWeightMatrix0to1[5][4] = 0.798780217800211;
   fWeightMatrix0to1[6][4] = -0.218373150994783;
   fWeightMatrix0to1[7][4] = 0.00994139757554987;
   fWeightMatrix0to1[8][4] = 0.346511433725898;
   fWeightMatrix0to1[9][4] = 0.751718546792962;
   fWeightMatrix0to1[10][4] = 0.216737112463751;
   fWeightMatrix0to1[11][4] = 0.184461090160894;
   fWeightMatrix0to1[12][4] = -0.652283878264052;
   fWeightMatrix0to1[13][4] = 0.341288017557596;
   fWeightMatrix0to1[0][5] = -1.73018459051694;
   fWeightMatrix0to1[1][5] = -1.426358206862;
   fWeightMatrix0to1[2][5] = 1.18544454149387;
   fWeightMatrix0to1[3][5] = 0.683363973478178;
   fWeightMatrix0to1[4][5] = 0.34211211548912;
   fWeightMatrix0to1[5][5] = 0.180687350189543;
   fWeightMatrix0to1[6][5] = -1.80893453979612;
   fWeightMatrix0to1[7][5] = 1.53083930955598;
   fWeightMatrix0to1[8][5] = 0.954496904906171;
   fWeightMatrix0to1[9][5] = -0.0516025457409606;
   fWeightMatrix0to1[10][5] = 2.08321938275651;
   fWeightMatrix0to1[11][5] = 0.656893651568334;
   fWeightMatrix0to1[12][5] = 0.0503039835594811;
   fWeightMatrix0to1[13][5] = -0.82451741648131;
   fWeightMatrix0to1[0][6] = -3.32275900389481;
   fWeightMatrix0to1[1][6] = -0.222316992983121;
   fWeightMatrix0to1[2][6] = 1.76154642875109;
   fWeightMatrix0to1[3][6] = -1.44975046471037;
   fWeightMatrix0to1[4][6] = 0.551913012783051;
   fWeightMatrix0to1[5][6] = -1.29235988205455;
   fWeightMatrix0to1[6][6] = -0.375081425810591;
   fWeightMatrix0to1[7][6] = 1.84289341156367;
   fWeightMatrix0to1[8][6] = 3.12546707901562;
   fWeightMatrix0to1[9][6] = -5.28318032165581;
   fWeightMatrix0to1[10][6] = -0.647541602009536;
   fWeightMatrix0to1[11][6] = 1.89582838939344;
   fWeightMatrix0to1[12][6] = -0.299751589909529;
   fWeightMatrix0to1[13][6] = -0.772435084557325;
   fWeightMatrix0to1[0][7] = 0.012930247879592;
   fWeightMatrix0to1[1][7] = 0.0921627142688257;
   fWeightMatrix0to1[2][7] = -1.203241504909;
   fWeightMatrix0to1[3][7] = -1.2365000210378;
   fWeightMatrix0to1[4][7] = 0.664035713128246;
   fWeightMatrix0to1[5][7] = 1.73755869665066;
   fWeightMatrix0to1[6][7] = -1.07036174063003;
   fWeightMatrix0to1[7][7] = 1.22452926809618;
   fWeightMatrix0to1[8][7] = -0.0897220535929556;
   fWeightMatrix0to1[9][7] = -0.841832550249093;
   fWeightMatrix0to1[10][7] = 0.0871802156439848;
   fWeightMatrix0to1[11][7] = 0.0153832602847185;
   fWeightMatrix0to1[12][7] = -0.195153565948539;
   fWeightMatrix0to1[13][7] = 1.37054743537393;
   fWeightMatrix0to1[0][8] = -8.35529992162594;
   fWeightMatrix0to1[1][8] = 0.453758912548528;
   fWeightMatrix0to1[2][8] = -1.29033855442876;
   fWeightMatrix0to1[3][8] = 1.87793225639897;
   fWeightMatrix0to1[4][8] = -2.0847251641121;
   fWeightMatrix0to1[5][8] = -1.18017741470581;
   fWeightMatrix0to1[6][8] = 0.595027864936591;
   fWeightMatrix0to1[7][8] = -2.86777713552161;
   fWeightMatrix0to1[8][8] = -4.89205045530495;
   fWeightMatrix0to1[9][8] = 1.10952826941693;
   fWeightMatrix0to1[10][8] = -0.469608438160832;
   fWeightMatrix0to1[11][8] = -0.26034340839849;
   fWeightMatrix0to1[12][8] = -0.0973730191858028;
   fWeightMatrix0to1[13][8] = 0.455058305860576;
   fWeightMatrix0to1[0][9] = -0.801725640524336;
   fWeightMatrix0to1[1][9] = 0.166405449244297;
   fWeightMatrix0to1[2][9] = -1.2618408579191;
   fWeightMatrix0to1[3][9] = 1.11247896575614;
   fWeightMatrix0to1[4][9] = 0.780304654086044;
   fWeightMatrix0to1[5][9] = -1.34538873644071;
   fWeightMatrix0to1[6][9] = 0.67040414153631;
   fWeightMatrix0to1[7][9] = 0.881130385011958;
   fWeightMatrix0to1[8][9] = 1.2717825115139;
   fWeightMatrix0to1[9][9] = 1.03170770761679;
   fWeightMatrix0to1[10][9] = 1.6485196209965;
   fWeightMatrix0to1[11][9] = -1.8836786903734;
   fWeightMatrix0to1[12][9] = -0.0496579370295612;
   fWeightMatrix0to1[13][9] = 2.67276526703604;
   fWeightMatrix0to1[0][10] = 4.85716825205882;
   fWeightMatrix0to1[1][10] = 0.168019145234771;
   fWeightMatrix0to1[2][10] = -1.95726438409947;
   fWeightMatrix0to1[3][10] = 0.221758090748252;
   fWeightMatrix0to1[4][10] = 8.33914359060444;
   fWeightMatrix0to1[5][10] = 1.05836043271599;
   fWeightMatrix0to1[6][10] = 1.1914788418275;
   fWeightMatrix0to1[7][10] = 5.72427485979049;
   fWeightMatrix0to1[8][10] = 4.52766447637522;
   fWeightMatrix0to1[9][10] = -8.76817975509807;
   fWeightMatrix0to1[10][10] = -1.47546812057778;
   fWeightMatrix0to1[11][10] = 0.241365938112398;
   fWeightMatrix0to1[12][10] = 4.58716130064577;
   fWeightMatrix0to1[13][10] = 0.975409653387064;
   fWeightMatrix0to1[0][11] = -0.72079275900152;
   fWeightMatrix0to1[1][11] = 0.292173345335886;
   fWeightMatrix0to1[2][11] = -0.035150116633634;
   fWeightMatrix0to1[3][11] = 1.02461399485537;
   fWeightMatrix0to1[4][11] = 0.765354671934141;
   fWeightMatrix0to1[5][11] = -2.05962205568002;
   fWeightMatrix0to1[6][11] = 1.62908160924555;
   fWeightMatrix0to1[7][11] = -2.69232462439807;
   fWeightMatrix0to1[8][11] = 0.711697816553657;
   fWeightMatrix0to1[9][11] = 2.0474654540964;
   fWeightMatrix0to1[10][11] = 0.827671561094743;
   fWeightMatrix0to1[11][11] = -0.992151549484831;
   fWeightMatrix0to1[12][11] = -1.28701625285074;
   fWeightMatrix0to1[13][11] = 1.2891359376725;
   fWeightMatrix0to1[0][12] = 0.307785277776556;
   fWeightMatrix0to1[1][12] = -0.573389830880968;
   fWeightMatrix0to1[2][12] = 1.4720807903507;
   fWeightMatrix0to1[3][12] = 0.944520116363969;
   fWeightMatrix0to1[4][12] = 1.69001281684484;
   fWeightMatrix0to1[5][12] = 1.36470703947973;
   fWeightMatrix0to1[6][12] = 1.8261583924389;
   fWeightMatrix0to1[7][12] = -2.46982845112653;
   fWeightMatrix0to1[8][12] = 0.91246685662074;
   fWeightMatrix0to1[9][12] = 0.212808414808335;
   fWeightMatrix0to1[10][12] = 0.463548423710922;
   fWeightMatrix0to1[11][12] = -1.71837644534966;
   fWeightMatrix0to1[12][12] = -0.324345676125684;
   fWeightMatrix0to1[13][12] = 1.05935775685278;
   fWeightMatrix0to1[0][13] = 1.1021198897225;
   fWeightMatrix0to1[1][13] = -1.75405249575778;
   fWeightMatrix0to1[2][13] = 0.854109050397886;
   fWeightMatrix0to1[3][13] = -1.20201525898754;
   fWeightMatrix0to1[4][13] = -0.5923427050171;
   fWeightMatrix0to1[5][13] = 2.34115186045788;
   fWeightMatrix0to1[6][13] = -0.607470260811941;
   fWeightMatrix0to1[7][13] = 1.34970148748423;
   fWeightMatrix0to1[8][13] = -2.73315812100714;
   fWeightMatrix0to1[9][13] = -0.546670395122006;
   fWeightMatrix0to1[10][13] = 1.81317656995783;
   fWeightMatrix0to1[11][13] = 1.50360354205086;
   fWeightMatrix0to1[12][13] = 0.868068786516491;
   fWeightMatrix0to1[13][13] = -0.837176639486511;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.269177825605136;
   fWeightMatrix1to2[1][0] = 1.84803459105153;
   fWeightMatrix1to2[2][0] = -0.608629820160712;
   fWeightMatrix1to2[3][0] = 0.940753628157642;
   fWeightMatrix1to2[4][0] = -1.47866803258026;
   fWeightMatrix1to2[5][0] = 0.382242671545101;
   fWeightMatrix1to2[6][0] = -0.0932810059759035;
   fWeightMatrix1to2[7][0] = -0.362098257293813;
   fWeightMatrix1to2[8][0] = 1.87015618113402;
   fWeightMatrix1to2[9][0] = 0.0895047670465939;
   fWeightMatrix1to2[10][0] = -0.443093725215841;
   fWeightMatrix1to2[11][0] = 1.07046181216119;
   fWeightMatrix1to2[12][0] = 3.61889294214334;
   fWeightMatrix1to2[0][1] = 2.3065146486826;
   fWeightMatrix1to2[1][1] = -0.0340230589680395;
   fWeightMatrix1to2[2][1] = -0.118030502623113;
   fWeightMatrix1to2[3][1] = -1.84855376069951;
   fWeightMatrix1to2[4][1] = -0.647506575889471;
   fWeightMatrix1to2[5][1] = 1.47171179270794;
   fWeightMatrix1to2[6][1] = 1.19810908257175;
   fWeightMatrix1to2[7][1] = 0.8915275871748;
   fWeightMatrix1to2[8][1] = -0.187960356908766;
   fWeightMatrix1to2[9][1] = 2.19447893161622;
   fWeightMatrix1to2[10][1] = -1.82661724710647;
   fWeightMatrix1to2[11][1] = -1.07690346093871;
   fWeightMatrix1to2[12][1] = -0.219668592635567;
   fWeightMatrix1to2[0][2] = -2.44899701672833;
   fWeightMatrix1to2[1][2] = 0.390158560630467;
   fWeightMatrix1to2[2][2] = 1.73025644330797;
   fWeightMatrix1to2[3][2] = -1.58098675577493;
   fWeightMatrix1to2[4][2] = 0.955702962444228;
   fWeightMatrix1to2[5][2] = 0.027151724038648;
   fWeightMatrix1to2[6][2] = -1.05776135021899;
   fWeightMatrix1to2[7][2] = -1.08489053392944;
   fWeightMatrix1to2[8][2] = 0.570683296875499;
   fWeightMatrix1to2[9][2] = 0.319361550322718;
   fWeightMatrix1to2[10][2] = 0.962076025940196;
   fWeightMatrix1to2[11][2] = -1.72546023857855;
   fWeightMatrix1to2[12][2] = 1.34513972464844;
   fWeightMatrix1to2[0][3] = -0.553573498123068;
   fWeightMatrix1to2[1][3] = 0.323543734760155;
   fWeightMatrix1to2[2][3] = 0.0545990498158792;
   fWeightMatrix1to2[3][3] = -1.33757001463186;
   fWeightMatrix1to2[4][3] = -1.04187549938746;
   fWeightMatrix1to2[5][3] = -1.98704860630987;
   fWeightMatrix1to2[6][3] = -0.588135972309388;
   fWeightMatrix1to2[7][3] = -1.75523173356428;
   fWeightMatrix1to2[8][3] = -1.77227301066382;
   fWeightMatrix1to2[9][3] = -1.36811386436208;
   fWeightMatrix1to2[10][3] = -0.0343685244221782;
   fWeightMatrix1to2[11][3] = -0.737254063216893;
   fWeightMatrix1to2[12][3] = -1.68130642482744;
   fWeightMatrix1to2[0][4] = 3.4530076847531;
   fWeightMatrix1to2[1][4] = 0.793110188541048;
   fWeightMatrix1to2[2][4] = 0.178424859191177;
   fWeightMatrix1to2[3][4] = -0.0381272839449051;
   fWeightMatrix1to2[4][4] = 1.66906088294842;
   fWeightMatrix1to2[5][4] = -0.232501696634212;
   fWeightMatrix1to2[6][4] = 0.0939506925560244;
   fWeightMatrix1to2[7][4] = 0.0681959622009669;
   fWeightMatrix1to2[8][4] = -0.977884727734039;
   fWeightMatrix1to2[9][4] = 0.149244693639334;
   fWeightMatrix1to2[10][4] = -0.770661219666956;
   fWeightMatrix1to2[11][4] = -0.208261910244054;
   fWeightMatrix1to2[12][4] = -0.254659379167035;
   fWeightMatrix1to2[0][5] = -0.913435939553894;
   fWeightMatrix1to2[1][5] = 2.1885188979412;
   fWeightMatrix1to2[2][5] = -0.338668259600937;
   fWeightMatrix1to2[3][5] = 0.170139713285855;
   fWeightMatrix1to2[4][5] = -0.820157605044388;
   fWeightMatrix1to2[5][5] = -1.8517587091914;
   fWeightMatrix1to2[6][5] = 1.38081345204634;
   fWeightMatrix1to2[7][5] = 0.988800880129441;
   fWeightMatrix1to2[8][5] = -0.536483200158756;
   fWeightMatrix1to2[9][5] = -1.41783742338843;
   fWeightMatrix1to2[10][5] = 1.00061523893932;
   fWeightMatrix1to2[11][5] = 0.905330568231901;
   fWeightMatrix1to2[12][5] = 0.527494973888712;
   fWeightMatrix1to2[0][6] = 0.749674059583354;
   fWeightMatrix1to2[1][6] = -0.808865327809745;
   fWeightMatrix1to2[2][6] = 1.43952223769021;
   fWeightMatrix1to2[3][6] = 1.10160516027456;
   fWeightMatrix1to2[4][6] = 1.26030906978577;
   fWeightMatrix1to2[5][6] = -0.51491788806677;
   fWeightMatrix1to2[6][6] = 0.0870066627561994;
   fWeightMatrix1to2[7][6] = -0.161033347964362;
   fWeightMatrix1to2[8][6] = -1.81662079508096;
   fWeightMatrix1to2[9][6] = -0.268588239780977;
   fWeightMatrix1to2[10][6] = -1.70983863309262;
   fWeightMatrix1to2[11][6] = -1.15513041364483;
   fWeightMatrix1to2[12][6] = -1.62391642002184;
   fWeightMatrix1to2[0][7] = 0.761853798171714;
   fWeightMatrix1to2[1][7] = -1.3504064525871;
   fWeightMatrix1to2[2][7] = -0.0185451492346228;
   fWeightMatrix1to2[3][7] = -2.01040056102337;
   fWeightMatrix1to2[4][7] = 1.55175193216578;
   fWeightMatrix1to2[5][7] = -0.00234233312909282;
   fWeightMatrix1to2[6][7] = 0.0592569690694531;
   fWeightMatrix1to2[7][7] = 0.0822443163752079;
   fWeightMatrix1to2[8][7] = -1.58817894685131;
   fWeightMatrix1to2[9][7] = -0.1786780481845;
   fWeightMatrix1to2[10][7] = 0.462535707560961;
   fWeightMatrix1to2[11][7] = -1.74039805420248;
   fWeightMatrix1to2[12][7] = -1.02318447983532;
   fWeightMatrix1to2[0][8] = -1.1233287177962;
   fWeightMatrix1to2[1][8] = -1.45397894345829;
   fWeightMatrix1to2[2][8] = 0.460314340181738;
   fWeightMatrix1to2[3][8] = 0.419401635827931;
   fWeightMatrix1to2[4][8] = -0.866508301749449;
   fWeightMatrix1to2[5][8] = -0.0408504035333942;
   fWeightMatrix1to2[6][8] = -0.0489432470052726;
   fWeightMatrix1to2[7][8] = 0.0536636554996544;
   fWeightMatrix1to2[8][8] = -0.881008883725729;
   fWeightMatrix1to2[9][8] = -0.0107610005157017;
   fWeightMatrix1to2[10][8] = 0.869037156889174;
   fWeightMatrix1to2[11][8] = -0.393300288159023;
   fWeightMatrix1to2[12][8] = -1.96389306841842;
   fWeightMatrix1to2[0][9] = 0.240760694698682;
   fWeightMatrix1to2[1][9] = 1.47061250432167;
   fWeightMatrix1to2[2][9] = -0.426241252640159;
   fWeightMatrix1to2[3][9] = 0.561350032915462;
   fWeightMatrix1to2[4][9] = -0.646861496585261;
   fWeightMatrix1to2[5][9] = 0.0401651085356389;
   fWeightMatrix1to2[6][9] = 0.0154300574655076;
   fWeightMatrix1to2[7][9] = -0.0332982289004314;
   fWeightMatrix1to2[8][9] = 0.368152237537281;
   fWeightMatrix1to2[9][9] = -0.18748824769068;
   fWeightMatrix1to2[10][9] = -1.26429014223168;
   fWeightMatrix1to2[11][9] = 0.134714783259026;
   fWeightMatrix1to2[12][9] = 2.0186962023391;
   fWeightMatrix1to2[0][10] = 0.0728582039213775;
   fWeightMatrix1to2[1][10] = 2.09256464804914;
   fWeightMatrix1to2[2][10] = -1.37648920900689;
   fWeightMatrix1to2[3][10] = 0.936019510377493;
   fWeightMatrix1to2[4][10] = -2.18905566125706;
   fWeightMatrix1to2[5][10] = 0.839810308596196;
   fWeightMatrix1to2[6][10] = -1.57674711250724;
   fWeightMatrix1to2[7][10] = -1.96979404972439;
   fWeightMatrix1to2[8][10] = 0.332832410005923;
   fWeightMatrix1to2[9][10] = 1.05047526786513;
   fWeightMatrix1to2[10][10] = 0.529527753295369;
   fWeightMatrix1to2[11][10] = 0.810835467229472;
   fWeightMatrix1to2[12][10] = 0.371507638565938;
   fWeightMatrix1to2[0][11] = -0.31787538099938;
   fWeightMatrix1to2[1][11] = -0.317925591888849;
   fWeightMatrix1to2[2][11] = 0.208359217237953;
   fWeightMatrix1to2[3][11] = 1.58651387498386;
   fWeightMatrix1to2[4][11] = -2.56336839933227;
   fWeightMatrix1to2[5][11] = 0.662901323817213;
   fWeightMatrix1to2[6][11] = -1.18227624071199;
   fWeightMatrix1to2[7][11] = -0.632951012334238;
   fWeightMatrix1to2[8][11] = 0.0612587398848051;
   fWeightMatrix1to2[9][11] = -0.316002917618602;
   fWeightMatrix1to2[10][11] = -1.03078379170154;
   fWeightMatrix1to2[11][11] = 0.649950910976289;
   fWeightMatrix1to2[12][11] = 1.6395623475871;
   fWeightMatrix1to2[0][12] = -0.804480374751462;
   fWeightMatrix1to2[1][12] = 0.883616357397762;
   fWeightMatrix1to2[2][12] = -0.571498759841771;
   fWeightMatrix1to2[3][12] = -0.0511330405102566;
   fWeightMatrix1to2[4][12] = -2.20646481186727;
   fWeightMatrix1to2[5][12] = 0.642339002501283;
   fWeightMatrix1to2[6][12] = -0.209501001008647;
   fWeightMatrix1to2[7][12] = -0.282572705143955;
   fWeightMatrix1to2[8][12] = 1.19914073455461;
   fWeightMatrix1to2[9][12] = -0.938726838555126;
   fWeightMatrix1to2[10][12] = -1.05984911259022;
   fWeightMatrix1to2[11][12] = -0.983994980216569;
   fWeightMatrix1to2[12][12] = 1.86890900395707;
   fWeightMatrix1to2[0][13] = -0.905781328544197;
   fWeightMatrix1to2[1][13] = -1.28091238805933;
   fWeightMatrix1to2[2][13] = -0.623981756441546;
   fWeightMatrix1to2[3][13] = -0.478540248797091;
   fWeightMatrix1to2[4][13] = -1.65224879358455;
   fWeightMatrix1to2[5][13] = 0.898406517785925;
   fWeightMatrix1to2[6][13] = -1.75001675782918;
   fWeightMatrix1to2[7][13] = -1.11016994878713;
   fWeightMatrix1to2[8][13] = 1.76402778803774;
   fWeightMatrix1to2[9][13] = 0.655945201011536;
   fWeightMatrix1to2[10][13] = 0.273503559263076;
   fWeightMatrix1to2[11][13] = 0.573972172647758;
   fWeightMatrix1to2[12][13] = 1.48523722268372;
   fWeightMatrix1to2[0][14] = 0.450637374985734;
   fWeightMatrix1to2[1][14] = 1.02114616609118;
   fWeightMatrix1to2[2][14] = -0.959518167099009;
   fWeightMatrix1to2[3][14] = -0.789758515550214;
   fWeightMatrix1to2[4][14] = -2.01301155091049;
   fWeightMatrix1to2[5][14] = 1.15859169179164;
   fWeightMatrix1to2[6][14] = 1.06610280515411;
   fWeightMatrix1to2[7][14] = -0.0372269251615935;
   fWeightMatrix1to2[8][14] = 1.48355610317196;
   fWeightMatrix1to2[9][14] = 0.741920305439332;
   fWeightMatrix1to2[10][14] = 1.73829346976036;
   fWeightMatrix1to2[11][14] = -1.57184643369492;
   fWeightMatrix1to2[12][14] = 1.8378786007325;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.381814741117937;
   fWeightMatrix2to3[0][1] = -1.57357908820941;
   fWeightMatrix2to3[0][2] = -0.0130051098034682;
   fWeightMatrix2to3[0][3] = 0.221897774973781;
   fWeightMatrix2to3[0][4] = 0.356797507806856;
   fWeightMatrix2to3[0][5] = -0.0459472607980787;
   fWeightMatrix2to3[0][6] = -0.0395261499769648;
   fWeightMatrix2to3[0][7] = 0.0655414629172363;
   fWeightMatrix2to3[0][8] = -0.207467754616505;
   fWeightMatrix2to3[0][9] = 0.0498974712548933;
   fWeightMatrix2to3[0][10] = 0.887639429963574;
   fWeightMatrix2to3[0][11] = -0.0816483816454138;
   fWeightMatrix2to3[0][12] = -0.303569439119838;
   fWeightMatrix2to3[0][13] = 0.89489344327319;
}

inline double ReadMLP0_25_B::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP0_25_B::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP0_25_B::Clear() 
{
   // nothing to clear
}
inline double ReadMLP0_25_B::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
