// Class: ReadMLP1_25_B_10x10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Tue Sep 22 14:47:23 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 8349


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,12.3490390778]
ClusterParameters.end         ClusterParameters.end             'F'    [4.3144659996,33.8960456848]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,31.4201011658]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.979311048985]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0353877656162,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.365337818861,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.0133150462061,0.999998509884]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999997913837]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.626850306988,27.0070209503]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.0573310144246,0.897238016129]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [6,82]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [22.8135871887,1404720.5]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-11.4260559082,24.4208679199]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1_25_B_10x10 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1_25_B_10x10( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1_25_B_10x10" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 12.3490390777588;
      fVmin[1] = 4.31446599960327;
      fVmax[1] = 33.8960456848145;
      fVmin[2] = 0;
      fVmax[2] = 31.4201011657715;
      fVmin[3] = 0;
      fVmax[3] = 0.979311048984528;
      fVmin[4] = 0.0353877656161785;
      fVmax[4] = 1;
      fVmin[5] = 0.365337818861008;
      fVmax[5] = 1;
      fVmin[6] = 0.0133150462061167;
      fVmax[6] = 0.999998509883881;
      fVmin[7] = 0;
      fVmax[7] = 0.999997913837433;
      fVmin[8] = 0.626850306987762;
      fVmax[8] = 27.0070209503174;
      fVmin[9] = 0.0573310144245625;
      fVmax[9] = 0.89723801612854;
      fVmin[10] = 6;
      fVmax[10] = 82;
      fVmin[11] = 22.8135871887207;
      fVmax[11] = 1404720.5;
      fVmin[12] = -11.4260559082031;
      fVmax[12] = 24.4208679199219;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1_25_B_10x10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1_25_B_10x10::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.168228721829915;
   fWeightMatrix0to1[1][0] = 1.94237052483927;
   fWeightMatrix0to1[2][0] = 0.277026438375901;
   fWeightMatrix0to1[3][0] = 1.47005189306622;
   fWeightMatrix0to1[4][0] = -1.51637201009161;
   fWeightMatrix0to1[5][0] = -1.26741169071789;
   fWeightMatrix0to1[6][0] = -0.715483772340828;
   fWeightMatrix0to1[7][0] = 2.2478932151138;
   fWeightMatrix0to1[8][0] = -0.261629765149232;
   fWeightMatrix0to1[9][0] = -0.90524812299827;
   fWeightMatrix0to1[10][0] = -1.45916666392841;
   fWeightMatrix0to1[11][0] = -0.381574589979601;
   fWeightMatrix0to1[12][0] = -1.78562681136462;
   fWeightMatrix0to1[13][0] = -0.236694519996796;
   fWeightMatrix0to1[0][1] = -0.625071373741355;
   fWeightMatrix0to1[1][1] = 0.604126933197299;
   fWeightMatrix0to1[2][1] = -0.997836150374287;
   fWeightMatrix0to1[3][1] = 1.59580566189358;
   fWeightMatrix0to1[4][1] = 0.640050706848502;
   fWeightMatrix0to1[5][1] = 1.29111717720912;
   fWeightMatrix0to1[6][1] = -0.261947603245798;
   fWeightMatrix0to1[7][1] = -1.0686793775014;
   fWeightMatrix0to1[8][1] = 1.35278001587028;
   fWeightMatrix0to1[9][1] = -0.141240530570648;
   fWeightMatrix0to1[10][1] = -0.993047256592894;
   fWeightMatrix0to1[11][1] = -0.223448015103433;
   fWeightMatrix0to1[12][1] = 2.83116218865258;
   fWeightMatrix0to1[13][1] = -0.914507422776583;
   fWeightMatrix0to1[0][2] = -1.63009753052089;
   fWeightMatrix0to1[1][2] = 0.103251821691319;
   fWeightMatrix0to1[2][2] = -0.0191739282811837;
   fWeightMatrix0to1[3][2] = 1.40894972989309;
   fWeightMatrix0to1[4][2] = -0.295857229982141;
   fWeightMatrix0to1[5][2] = -0.162326155790191;
   fWeightMatrix0to1[6][2] = 0.24704463457117;
   fWeightMatrix0to1[7][2] = -0.163459981908048;
   fWeightMatrix0to1[8][2] = -2.38609078879544;
   fWeightMatrix0to1[9][2] = 1.90314260371289;
   fWeightMatrix0to1[10][2] = -1.15258273237521;
   fWeightMatrix0to1[11][2] = 0.662899088653376;
   fWeightMatrix0to1[12][2] = 1.59329347472804;
   fWeightMatrix0to1[13][2] = 0.966252701756483;
   fWeightMatrix0to1[0][3] = 2.5950782565376;
   fWeightMatrix0to1[1][3] = 1.37154794567037;
   fWeightMatrix0to1[2][3] = -0.863420167132387;
   fWeightMatrix0to1[3][3] = -0.639476099429886;
   fWeightMatrix0to1[4][3] = 1.12045984368067;
   fWeightMatrix0to1[5][3] = 0.129365338689479;
   fWeightMatrix0to1[6][3] = 1.75687800481591;
   fWeightMatrix0to1[7][3] = 0.948829558842276;
   fWeightMatrix0to1[8][3] = 1.76814456395673;
   fWeightMatrix0to1[9][3] = 1.03217655628408;
   fWeightMatrix0to1[10][3] = -1.74369601360336;
   fWeightMatrix0to1[11][3] = 1.65179898508229;
   fWeightMatrix0to1[12][3] = -1.99028336264607;
   fWeightMatrix0to1[13][3] = -0.733357583952758;
   fWeightMatrix0to1[0][4] = -0.757116861719296;
   fWeightMatrix0to1[1][4] = -1.66021518080394;
   fWeightMatrix0to1[2][4] = 1.36698934242341;
   fWeightMatrix0to1[3][4] = 1.37686505494242;
   fWeightMatrix0to1[4][4] = -0.851397625167106;
   fWeightMatrix0to1[5][4] = 0.200020171844605;
   fWeightMatrix0to1[6][4] = -0.157267316639509;
   fWeightMatrix0to1[7][4] = 0.747133294788304;
   fWeightMatrix0to1[8][4] = 2.39213144865078;
   fWeightMatrix0to1[9][4] = 0.0201538451791996;
   fWeightMatrix0to1[10][4] = 0.195367277842223;
   fWeightMatrix0to1[11][4] = -1.62834701865795;
   fWeightMatrix0to1[12][4] = -0.756990316176241;
   fWeightMatrix0to1[13][4] = -0.884503771107406;
   fWeightMatrix0to1[0][5] = -1.03746594166881;
   fWeightMatrix0to1[1][5] = -1.2715382576674;
   fWeightMatrix0to1[2][5] = 0.539087792074554;
   fWeightMatrix0to1[3][5] = 1.0545747155653;
   fWeightMatrix0to1[4][5] = 0.769257171579184;
   fWeightMatrix0to1[5][5] = -0.442363104194173;
   fWeightMatrix0to1[6][5] = -1.77780322329634;
   fWeightMatrix0to1[7][5] = -1.75186788649425;
   fWeightMatrix0to1[8][5] = 0.804152423217138;
   fWeightMatrix0to1[9][5] = 0.32736007455875;
   fWeightMatrix0to1[10][5] = 2.21698869464603;
   fWeightMatrix0to1[11][5] = 0.849895240995736;
   fWeightMatrix0to1[12][5] = 0.884522837296495;
   fWeightMatrix0to1[13][5] = -1.06751444030758;
   fWeightMatrix0to1[0][6] = -1.16421214012407;
   fWeightMatrix0to1[1][6] = -0.39429011837339;
   fWeightMatrix0to1[2][6] = 1.1128945372775;
   fWeightMatrix0to1[3][6] = -0.873043232482102;
   fWeightMatrix0to1[4][6] = -1.88778188470169;
   fWeightMatrix0to1[5][6] = -1.8335158773781;
   fWeightMatrix0to1[6][6] = -0.289439127463854;
   fWeightMatrix0to1[7][6] = -0.299485666215411;
   fWeightMatrix0to1[8][6] = 2.38236484402428;
   fWeightMatrix0to1[9][6] = -2.2484439891431;
   fWeightMatrix0to1[10][6] = -0.435654171141175;
   fWeightMatrix0to1[11][6] = 1.40582801103495;
   fWeightMatrix0to1[12][6] = -1.6690657105332;
   fWeightMatrix0to1[13][6] = -1.58789983360643;
   fWeightMatrix0to1[0][7] = -0.103582822634532;
   fWeightMatrix0to1[1][7] = -0.0987334783267118;
   fWeightMatrix0to1[2][7] = -0.321546477333218;
   fWeightMatrix0to1[3][7] = -2.40705279663689;
   fWeightMatrix0to1[4][7] = -0.936376942119766;
   fWeightMatrix0to1[5][7] = 2.09503256653368;
   fWeightMatrix0to1[6][7] = -0.964058906707823;
   fWeightMatrix0to1[7][7] = 0.874582418142923;
   fWeightMatrix0to1[8][7] = 0.71695191342236;
   fWeightMatrix0to1[9][7] = -0.436211754593317;
   fWeightMatrix0to1[10][7] = 0.0871786164318105;
   fWeightMatrix0to1[11][7] = 0.22228002855637;
   fWeightMatrix0to1[12][7] = -0.983401314483265;
   fWeightMatrix0to1[13][7] = 0.307070512190568;
   fWeightMatrix0to1[0][8] = 0.0205318736653581;
   fWeightMatrix0to1[1][8] = 0.300507079204935;
   fWeightMatrix0to1[2][8] = -1.61795357760338;
   fWeightMatrix0to1[3][8] = 1.41915232893368;
   fWeightMatrix0to1[4][8] = 0.708184207103736;
   fWeightMatrix0to1[5][8] = -1.00006578150319;
   fWeightMatrix0to1[6][8] = 0.542282061784346;
   fWeightMatrix0to1[7][8] = -1.23942520454536;
   fWeightMatrix0to1[8][8] = -1.88058201126314;
   fWeightMatrix0to1[9][8] = 0.256830351950712;
   fWeightMatrix0to1[10][8] = -0.376803453488054;
   fWeightMatrix0to1[11][8] = 1.26793393097751;
   fWeightMatrix0to1[12][8] = 1.16316320088425;
   fWeightMatrix0to1[13][8] = 0.103361838781221;
   fWeightMatrix0to1[0][9] = -0.505393904578108;
   fWeightMatrix0to1[1][9] = 0.213190636993247;
   fWeightMatrix0to1[2][9] = -1.95804230578683;
   fWeightMatrix0to1[3][9] = 0.615709752745201;
   fWeightMatrix0to1[4][9] = -0.284081283930216;
   fWeightMatrix0to1[5][9] = -1.82146110257103;
   fWeightMatrix0to1[6][9] = 0.527690916525928;
   fWeightMatrix0to1[7][9] = -1.34071711187324;
   fWeightMatrix0to1[8][9] = 1.21936109864573;
   fWeightMatrix0to1[9][9] = 0.491757952894295;
   fWeightMatrix0to1[10][9] = 1.61413106291617;
   fWeightMatrix0to1[11][9] = -2.4383126953036;
   fWeightMatrix0to1[12][9] = 0.0095648740773099;
   fWeightMatrix0to1[13][9] = 1.42997152939715;
   fWeightMatrix0to1[0][10] = 1.88275898077706;
   fWeightMatrix0to1[1][10] = 0.186222950386219;
   fWeightMatrix0to1[2][10] = -1.54746955600654;
   fWeightMatrix0to1[3][10] = -0.118902291623835;
   fWeightMatrix0to1[4][10] = -3.69979902886819;
   fWeightMatrix0to1[5][10] = 1.28669570223082;
   fWeightMatrix0to1[6][10] = 1.26540250237289;
   fWeightMatrix0to1[7][10] = -0.986156357555208;
   fWeightMatrix0to1[8][10] = 1.77691460867186;
   fWeightMatrix0to1[9][10] = -1.95919339691185;
   fWeightMatrix0to1[10][10] = -1.44470571613995;
   fWeightMatrix0to1[11][10] = 0.382240275305789;
   fWeightMatrix0to1[12][10] = 0.793532058564168;
   fWeightMatrix0to1[13][10] = -0.577891860019478;
   fWeightMatrix0to1[0][11] = -0.110107993782159;
   fWeightMatrix0to1[1][11] = 0.265478784648788;
   fWeightMatrix0to1[2][11] = 1.52549157636121;
   fWeightMatrix0to1[3][11] = 0.659085207213532;
   fWeightMatrix0to1[4][11] = 0.908123632187407;
   fWeightMatrix0to1[5][11] = -1.50711337134299;
   fWeightMatrix0to1[6][11] = 1.74674689771021;
   fWeightMatrix0to1[7][11] = 0.558891023435064;
   fWeightMatrix0to1[8][11] = 1.39554787867882;
   fWeightMatrix0to1[9][11] = 0.254068175469141;
   fWeightMatrix0to1[10][11] = 0.736942190168907;
   fWeightMatrix0to1[11][11] = -0.249682378102065;
   fWeightMatrix0to1[12][11] = 0.0441719835169325;
   fWeightMatrix0to1[13][11] = 1.23509021940099;
   fWeightMatrix0to1[0][12] = -0.833646980046392;
   fWeightMatrix0to1[1][12] = -0.617339496885782;
   fWeightMatrix0to1[2][12] = 1.10573096634241;
   fWeightMatrix0to1[3][12] = 0.816796759931181;
   fWeightMatrix0to1[4][12] = -0.485523357083345;
   fWeightMatrix0to1[5][12] = 1.46395964307812;
   fWeightMatrix0to1[6][12] = 1.79573979877172;
   fWeightMatrix0to1[7][12] = -1.95793866175053;
   fWeightMatrix0to1[8][12] = -0.834514452994763;
   fWeightMatrix0to1[9][12] = 0.129236381392215;
   fWeightMatrix0to1[10][12] = 0.540292701315823;
   fWeightMatrix0to1[11][12] = -2.17798388955192;
   fWeightMatrix0to1[12][12] = -0.93970994020184;
   fWeightMatrix0to1[13][12] = 1.14234549537545;
   fWeightMatrix0to1[0][13] = 1.29548793352059;
   fWeightMatrix0to1[1][13] = -1.91649732255474;
   fWeightMatrix0to1[2][13] = -0.622233818870723;
   fWeightMatrix0to1[3][13] = -0.977435371103381;
   fWeightMatrix0to1[4][13] = -0.0525050520475864;
   fWeightMatrix0to1[5][13] = 1.80658557910764;
   fWeightMatrix0to1[6][13] = -0.653505350814705;
   fWeightMatrix0to1[7][13] = -0.584586831858429;
   fWeightMatrix0to1[8][13] = -2.5918832133;
   fWeightMatrix0to1[9][13] = 1.40616416176962;
   fWeightMatrix0to1[10][13] = 1.99324257400329;
   fWeightMatrix0to1[11][13] = 0.690594461252346;
   fWeightMatrix0to1[12][13] = 0.745326717945228;
   fWeightMatrix0to1[13][13] = -0.925955929305822;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.08646425882871;
   fWeightMatrix1to2[1][0] = 1.07932057884129;
   fWeightMatrix1to2[2][0] = 0.24444381420884;
   fWeightMatrix1to2[3][0] = -1.62994751458453;
   fWeightMatrix1to2[4][0] = -0.595041181875965;
   fWeightMatrix1to2[5][0] = 0.208562745406406;
   fWeightMatrix1to2[6][0] = 0.18292677528156;
   fWeightMatrix1to2[7][0] = -2.01370706060343;
   fWeightMatrix1to2[8][0] = 1.4806595062345;
   fWeightMatrix1to2[9][0] = 0.600856309350817;
   fWeightMatrix1to2[10][0] = -0.477458336617694;
   fWeightMatrix1to2[11][0] = -0.108830937364665;
   fWeightMatrix1to2[12][0] = 1.26064456630779;
   fWeightMatrix1to2[0][1] = 0.584658689777106;
   fWeightMatrix1to2[1][1] = 0.171068451523078;
   fWeightMatrix1to2[2][1] = -0.329385616196356;
   fWeightMatrix1to2[3][1] = -1.93253626675636;
   fWeightMatrix1to2[4][1] = -1.05114734740121;
   fWeightMatrix1to2[5][1] = 1.68131173097299;
   fWeightMatrix1to2[6][1] = 1.44470202173638;
   fWeightMatrix1to2[7][1] = 0.417808276722881;
   fWeightMatrix1to2[8][1] = 0.123441652274041;
   fWeightMatrix1to2[9][1] = 1.19912678825737;
   fWeightMatrix1to2[10][1] = -1.96850601116082;
   fWeightMatrix1to2[11][1] = -1.32962494398483;
   fWeightMatrix1to2[12][1] = -0.389496923752894;
   fWeightMatrix1to2[0][2] = -1.71191129873475;
   fWeightMatrix1to2[1][2] = 1.21943224920086;
   fWeightMatrix1to2[2][2] = 1.83882934489106;
   fWeightMatrix1to2[3][2] = -1.15439933015727;
   fWeightMatrix1to2[4][2] = 0.772647882110326;
   fWeightMatrix1to2[5][2] = -0.079256802634944;
   fWeightMatrix1to2[6][2] = -1.58126488159016;
   fWeightMatrix1to2[7][2] = -0.938219123322488;
   fWeightMatrix1to2[8][2] = 1.09578196622764;
   fWeightMatrix1to2[9][2] = 0.187791557331106;
   fWeightMatrix1to2[10][2] = 0.805902171981201;
   fWeightMatrix1to2[11][2] = -1.154522409937;
   fWeightMatrix1to2[12][2] = 1.6520263871428;
   fWeightMatrix1to2[0][3] = -1.63071906294504;
   fWeightMatrix1to2[1][3] = 0.632258496737441;
   fWeightMatrix1to2[2][3] = -0.126331181094971;
   fWeightMatrix1to2[3][3] = -1.51150064492409;
   fWeightMatrix1to2[4][3] = -1.50896292515202;
   fWeightMatrix1to2[5][3] = -1.94529527316873;
   fWeightMatrix1to2[6][3] = -0.203996316068068;
   fWeightMatrix1to2[7][3] = -1.95653563794139;
   fWeightMatrix1to2[8][3] = -1.62618997649786;
   fWeightMatrix1to2[9][3] = -1.65073090659464;
   fWeightMatrix1to2[10][3] = -0.0779557202307635;
   fWeightMatrix1to2[11][3] = -0.987676207214261;
   fWeightMatrix1to2[12][3] = -1.47184257131906;
   fWeightMatrix1to2[0][4] = 2.63012683746104;
   fWeightMatrix1to2[1][4] = -1.32261512166029;
   fWeightMatrix1to2[2][4] = -0.0575332577693173;
   fWeightMatrix1to2[3][4] = -1.19145413830431;
   fWeightMatrix1to2[4][4] = 0.034292936417101;
   fWeightMatrix1to2[5][4] = 1.80646979534048;
   fWeightMatrix1to2[6][4] = 1.33672675128048;
   fWeightMatrix1to2[7][4] = -1.14433395863456;
   fWeightMatrix1to2[8][4] = -1.55279018721555;
   fWeightMatrix1to2[9][4] = -1.23428053344821;
   fWeightMatrix1to2[10][4] = -0.906345564841414;
   fWeightMatrix1to2[11][4] = -1.61451173739716;
   fWeightMatrix1to2[12][4] = 0.000670524214458932;
   fWeightMatrix1to2[0][5] = 1.05841004729179;
   fWeightMatrix1to2[1][5] = 2.05075701000711;
   fWeightMatrix1to2[2][5] = -0.0850703545286145;
   fWeightMatrix1to2[3][5] = 0.347553292035662;
   fWeightMatrix1to2[4][5] = -0.25148951128366;
   fWeightMatrix1to2[5][5] = -1.92348077337918;
   fWeightMatrix1to2[6][5] = 1.11441026481232;
   fWeightMatrix1to2[7][5] = 1.56872855603045;
   fWeightMatrix1to2[8][5] = -0.768794430116968;
   fWeightMatrix1to2[9][5] = -0.715868848946777;
   fWeightMatrix1to2[10][5] = 0.82879360205132;
   fWeightMatrix1to2[11][5] = 1.21950194874525;
   fWeightMatrix1to2[12][5] = 0.447417158691301;
   fWeightMatrix1to2[0][6] = -0.962851267972827;
   fWeightMatrix1to2[1][6] = -0.565664418836033;
   fWeightMatrix1to2[2][6] = 1.25448904104712;
   fWeightMatrix1to2[3][6] = 0.988815052707405;
   fWeightMatrix1to2[4][6] = 0.873039155000127;
   fWeightMatrix1to2[5][6] = -0.305948987052033;
   fWeightMatrix1to2[6][6] = 0.48127032484623;
   fWeightMatrix1to2[7][6] = -0.486244225865934;
   fWeightMatrix1to2[8][6] = -1.54718302866516;
   fWeightMatrix1to2[9][6] = -1.14728194395642;
   fWeightMatrix1to2[10][6] = -1.80082679547932;
   fWeightMatrix1to2[11][6] = -1.40440918485574;
   fWeightMatrix1to2[12][6] = -1.8809954027103;
   fWeightMatrix1to2[0][7] = 1.31119759354146;
   fWeightMatrix1to2[1][7] = -1.62233449615206;
   fWeightMatrix1to2[2][7] = 1.47373706960039;
   fWeightMatrix1to2[3][7] = -1.69289806295827;
   fWeightMatrix1to2[4][7] = 0.934895205757113;
   fWeightMatrix1to2[5][7] = -1.12930860031188;
   fWeightMatrix1to2[6][7] = 0.605675772862954;
   fWeightMatrix1to2[7][7] = 0.511690646721173;
   fWeightMatrix1to2[8][7] = -1.78750600127616;
   fWeightMatrix1to2[9][7] = -0.538593160231631;
   fWeightMatrix1to2[10][7] = 0.356168486699327;
   fWeightMatrix1to2[11][7] = -1.98970179300351;
   fWeightMatrix1to2[12][7] = -1.67505392366086;
   fWeightMatrix1to2[0][8] = -3.37160482942328;
   fWeightMatrix1to2[1][8] = -0.585316069580309;
   fWeightMatrix1to2[2][8] = 2.07494373020123;
   fWeightMatrix1to2[3][8] = -1.04257841457894;
   fWeightMatrix1to2[4][8] = 1.1601072469211;
   fWeightMatrix1to2[5][8] = -0.892561007773449;
   fWeightMatrix1to2[6][8] = -1.01664278519248;
   fWeightMatrix1to2[7][8] = -1.63573881744958;
   fWeightMatrix1to2[8][8] = -0.959061807669521;
   fWeightMatrix1to2[9][8] = -1.51476161508546;
   fWeightMatrix1to2[10][8] = 0.727900561183694;
   fWeightMatrix1to2[11][8] = -1.37107766129448;
   fWeightMatrix1to2[12][8] = -1.39670408419086;
   fWeightMatrix1to2[0][9] = 2.20517502285757;
   fWeightMatrix1to2[1][9] = 0.443394835559196;
   fWeightMatrix1to2[2][9] = -0.755625785537533;
   fWeightMatrix1to2[3][9] = 1.74978001225426;
   fWeightMatrix1to2[4][9] = -2.02031042659434;
   fWeightMatrix1to2[5][9] = 1.36030346518938;
   fWeightMatrix1to2[6][9] = 1.24742513903613;
   fWeightMatrix1to2[7][9] = -1.27702287816759;
   fWeightMatrix1to2[8][9] = -0.872534958275455;
   fWeightMatrix1to2[9][9] = -0.110154852351116;
   fWeightMatrix1to2[10][9] = -1.18805411413718;
   fWeightMatrix1to2[11][9] = 0.48162487405472;
   fWeightMatrix1to2[12][9] = 1.70400987460941;
   fWeightMatrix1to2[0][10] = 1.68365342642197;
   fWeightMatrix1to2[1][10] = 1.85526672646837;
   fWeightMatrix1to2[2][10] = -1.17742260131003;
   fWeightMatrix1to2[3][10] = 0.924892701239194;
   fWeightMatrix1to2[4][10] = -1.78221753878598;
   fWeightMatrix1to2[5][10] = 0.64000134616792;
   fWeightMatrix1to2[6][10] = -1.85259893597379;
   fWeightMatrix1to2[7][10] = -1.49638780017219;
   fWeightMatrix1to2[8][10] = 0.0179212679141695;
   fWeightMatrix1to2[9][10] = 2.03499747307021;
   fWeightMatrix1to2[10][10] = 0.696566486113617;
   fWeightMatrix1to2[11][10] = 1.06905680087077;
   fWeightMatrix1to2[12][10] = 0.519622856811824;
   fWeightMatrix1to2[0][11] = -1.74696963313039;
   fWeightMatrix1to2[1][11] = -0.703248998606981;
   fWeightMatrix1to2[2][11] = 0.185256157208727;
   fWeightMatrix1to2[3][11] = 1.64903320086053;
   fWeightMatrix1to2[4][11] = -1.07798653792278;
   fWeightMatrix1to2[5][11] = 0.359315592210959;
   fWeightMatrix1to2[6][11] = -1.5747459566054;
   fWeightMatrix1to2[7][11] = -0.247999016946073;
   fWeightMatrix1to2[8][11] = 0.0888309526258131;
   fWeightMatrix1to2[9][11] = 0.314534189690307;
   fWeightMatrix1to2[10][11] = -0.969760670854642;
   fWeightMatrix1to2[11][11] = 0.97271889109983;
   fWeightMatrix1to2[12][11] = 1.6255592471355;
   fWeightMatrix1to2[0][12] = 2.0013858050982;
   fWeightMatrix1to2[1][12] = -0.475699769564056;
   fWeightMatrix1to2[2][12] = -1.26414081238646;
   fWeightMatrix1to2[3][12] = -1.35436367710863;
   fWeightMatrix1to2[4][12] = -1.6745795375643;
   fWeightMatrix1to2[5][12] = 1.10981908406331;
   fWeightMatrix1to2[6][12] = -0.460082932011191;
   fWeightMatrix1to2[7][12] = -0.884187788277769;
   fWeightMatrix1to2[8][12] = 0.428948823346946;
   fWeightMatrix1to2[9][12] = -1.0133479394386;
   fWeightMatrix1to2[10][12] = -0.896411090062443;
   fWeightMatrix1to2[11][12] = -1.57804863190355;
   fWeightMatrix1to2[12][12] = 1.07882479680941;
   fWeightMatrix1to2[0][13] = -1.75680937586091;
   fWeightMatrix1to2[1][13] = -1.83275639521377;
   fWeightMatrix1to2[2][13] = -0.770849494646033;
   fWeightMatrix1to2[3][13] = -1.07549466888108;
   fWeightMatrix1to2[4][13] = -1.77518126370821;
   fWeightMatrix1to2[5][13] = 1.17911733512672;
   fWeightMatrix1to2[6][13] = -1.24063114164495;
   fWeightMatrix1to2[7][13] = -1.32683268097162;
   fWeightMatrix1to2[8][13] = 1.63833912945733;
   fWeightMatrix1to2[9][13] = 0.39369252545427;
   fWeightMatrix1to2[10][13] = 0.424342315342238;
   fWeightMatrix1to2[11][13] = 0.0776101227396118;
   fWeightMatrix1to2[12][13] = 0.993888949756279;
   fWeightMatrix1to2[0][14] = 2.17715966240326;
   fWeightMatrix1to2[1][14] = 0.782249699203267;
   fWeightMatrix1to2[2][14] = -0.747284332565172;
   fWeightMatrix1to2[3][14] = -0.707603457085857;
   fWeightMatrix1to2[4][14] = -1.62115052333434;
   fWeightMatrix1to2[5][14] = 0.945795745036927;
   fWeightMatrix1to2[6][14] = 0.774379873219019;
   fWeightMatrix1to2[7][14] = 0.432911835595702;
   fWeightMatrix1to2[8][14] = 1.18367646956403;
   fWeightMatrix1to2[9][14] = 1.65786459312554;
   fWeightMatrix1to2[10][14] = 1.88144070590553;
   fWeightMatrix1to2[11][14] = -1.32010345333559;
   fWeightMatrix1to2[12][14] = 2.11528101674308;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.08664681451031;
   fWeightMatrix2to3[0][1] = -2.00453325553436;
   fWeightMatrix2to3[0][2] = -0.117517126640713;
   fWeightMatrix2to3[0][3] = -0.853711850703274;
   fWeightMatrix2to3[0][4] = 0.0310414433320693;
   fWeightMatrix2to3[0][5] = 0.00445962119222653;
   fWeightMatrix2to3[0][6] = -0.00938590081918486;
   fWeightMatrix2to3[0][7] = -0.0153473924396887;
   fWeightMatrix2to3[0][8] = -0.0704593731994647;
   fWeightMatrix2to3[0][9] = 0.698737181619247;
   fWeightMatrix2to3[0][10] = 1.29792077790895;
   fWeightMatrix2to3[0][11] = 0.126502821144096;
   fWeightMatrix2to3[0][12] = -0.832299091107964;
   fWeightMatrix2to3[0][13] = 1.64395391765079;
}

inline double ReadMLP1_25_B_10x10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1_25_B_10x10::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1_25_B_10x10::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1_25_B_10x10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
