// Class: ReadMLP1_25_EC_1x1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Mon Aug 10 10:48:35 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 2057


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,9.71573162079]
ClusterParameters.end         ClusterParameters.end             'F'    [3.98371052742,33.7255096436]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,20.8941783905]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,1]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0593672394753,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.345857203007,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.00646160263568,0.999996840954]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999969303608]
ClusterParameters.Width       ClusterParameters.Width           'F'    [6.1035152612e-05,36.0768089294]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [9.81259017863e-06,0.944616913795]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [6,73]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [0.00989148300141,1251308.375]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [0,19.3002300262]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1_25_EC_1x1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1_25_EC_1x1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1_25_EC_1x1" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 9.71573162078857;
      fVmin[1] = 3.98371052742004;
      fVmax[1] = 33.7255096435547;
      fVmin[2] = 0;
      fVmax[2] = 20.8941783905029;
      fVmin[3] = 0;
      fVmax[3] = 1;
      fVmin[4] = 0.0593672394752502;
      fVmax[4] = 1;
      fVmin[5] = 0.345857203006744;
      fVmax[5] = 1;
      fVmin[6] = 0.00646160263568163;
      fVmax[6] = 0.999996840953827;
      fVmin[7] = 0;
      fVmax[7] = 0.999969303607941;
      fVmin[8] = 6.10351526120212e-05;
      fVmax[8] = 36.0768089294434;
      fVmin[9] = 9.81259017862612e-06;
      fVmax[9] = 0.944616913795471;
      fVmin[10] = 6;
      fVmax[10] = 73;
      fVmin[11] = 0.00989148300141096;
      fVmax[11] = 1251308.375;
      fVmin[12] = 0;
      fVmax[12] = 19.3002300262451;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1_25_EC_1x1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1_25_EC_1x1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.187073540552031;
   fWeightMatrix0to1[1][0] = 1.96301020676907;
   fWeightMatrix0to1[2][0] = 0.984018690580867;
   fWeightMatrix0to1[3][0] = 1.70578718114501;
   fWeightMatrix0to1[4][0] = -1.20193996601493;
   fWeightMatrix0to1[5][0] = -1.5301439183194;
   fWeightMatrix0to1[6][0] = -0.577924891813884;
   fWeightMatrix0to1[7][0] = 2.26264373495135;
   fWeightMatrix0to1[8][0] = -1.67765896310793;
   fWeightMatrix0to1[9][0] = -0.844414502111302;
   fWeightMatrix0to1[10][0] = -1.62140219004431;
   fWeightMatrix0to1[11][0] = -0.176972883917306;
   fWeightMatrix0to1[12][0] = -0.825313859462816;
   fWeightMatrix0to1[13][0] = -0.406935768030216;
   fWeightMatrix0to1[0][1] = -0.571923288612816;
   fWeightMatrix0to1[1][1] = 0.677675859957048;
   fWeightMatrix0to1[2][1] = -1.04836243768509;
   fWeightMatrix0to1[3][1] = 1.55220577832541;
   fWeightMatrix0to1[4][1] = -0.586720844087564;
   fWeightMatrix0to1[5][1] = 1.10376117341542;
   fWeightMatrix0to1[6][1] = -0.311675793241916;
   fWeightMatrix0to1[7][1] = -0.667048578258472;
   fWeightMatrix0to1[8][1] = 0.530205749674061;
   fWeightMatrix0to1[9][1] = -0.0624349050050844;
   fWeightMatrix0to1[10][1] = -1.12100963930393;
   fWeightMatrix0to1[11][1] = -0.303597563087346;
   fWeightMatrix0to1[12][1] = 0.918845384754493;
   fWeightMatrix0to1[13][1] = -1.11318550872755;
   fWeightMatrix0to1[0][2] = -1.84590484356846;
   fWeightMatrix0to1[1][2] = 0.0813235205707323;
   fWeightMatrix0to1[2][2] = 0.474385855892661;
   fWeightMatrix0to1[3][2] = 1.70036097704853;
   fWeightMatrix0to1[4][2] = 0.582630310295451;
   fWeightMatrix0to1[5][2] = -0.13796518231929;
   fWeightMatrix0to1[6][2] = 0.254014129895058;
   fWeightMatrix0to1[7][2] = -0.25375343354517;
   fWeightMatrix0to1[8][2] = -1.53285076354619;
   fWeightMatrix0to1[9][2] = 1.82603946857447;
   fWeightMatrix0to1[10][2] = -1.06723533055304;
   fWeightMatrix0to1[11][2] = 1.19567771499157;
   fWeightMatrix0to1[12][2] = 2.47861865528405;
   fWeightMatrix0to1[13][2] = 0.803742620854019;
   fWeightMatrix0to1[0][3] = 2.29094479495721;
   fWeightMatrix0to1[1][3] = 1.37946369583924;
   fWeightMatrix0to1[2][3] = -1.01806119202484;
   fWeightMatrix0to1[3][3] = -1.92830428334552;
   fWeightMatrix0to1[4][3] = -0.0965406451298879;
   fWeightMatrix0to1[5][3] = -0.433061305002486;
   fWeightMatrix0to1[6][3] = 1.68881263614048;
   fWeightMatrix0to1[7][3] = 1.23487173231129;
   fWeightMatrix0to1[8][3] = 1.11967208658919;
   fWeightMatrix0to1[9][3] = 0.665932586108287;
   fWeightMatrix0to1[10][3] = -1.67657212123194;
   fWeightMatrix0to1[11][3] = 1.26266059613422;
   fWeightMatrix0to1[12][3] = -2.20844847852665;
   fWeightMatrix0to1[13][3] = -0.805943306817659;
   fWeightMatrix0to1[0][4] = -1.40271014210969;
   fWeightMatrix0to1[1][4] = -1.65410884382808;
   fWeightMatrix0to1[2][4] = 1.01532304781625;
   fWeightMatrix0to1[3][4] = 0.159825191036625;
   fWeightMatrix0to1[4][4] = -2.22890578757372;
   fWeightMatrix0to1[5][4] = 0.0727511660715789;
   fWeightMatrix0to1[6][4] = -0.186771041271399;
   fWeightMatrix0to1[7][4] = 0.303415709995579;
   fWeightMatrix0to1[8][4] = 1.80828091000961;
   fWeightMatrix0to1[9][4] = -0.523257495808088;
   fWeightMatrix0to1[10][4] = 0.357132122990927;
   fWeightMatrix0to1[11][4] = -1.30416614343037;
   fWeightMatrix0to1[12][4] = -0.0299900666817055;
   fWeightMatrix0to1[13][4] = -0.804223321982569;
   fWeightMatrix0to1[0][5] = -1.10408972532732;
   fWeightMatrix0to1[1][5] = -1.37021482415204;
   fWeightMatrix0to1[2][5] = 0.340454454901221;
   fWeightMatrix0to1[3][5] = 0.879883207867;
   fWeightMatrix0to1[4][5] = 1.63153854710207;
   fWeightMatrix0to1[5][5] = -0.174418130599968;
   fWeightMatrix0to1[6][5] = -1.95853730466924;
   fWeightMatrix0to1[7][5] = -2.21053211206892;
   fWeightMatrix0to1[8][5] = 1.44192984341742;
   fWeightMatrix0to1[9][5] = 0.367990690978848;
   fWeightMatrix0to1[10][5] = 2.13934918667609;
   fWeightMatrix0to1[11][5] = 0.703356950810972;
   fWeightMatrix0to1[12][5] = 0.741652683711367;
   fWeightMatrix0to1[13][5] = -0.703733915735515;
   fWeightMatrix0to1[0][6] = -0.963732859656557;
   fWeightMatrix0to1[1][6] = -0.236810964403981;
   fWeightMatrix0to1[2][6] = 0.72205876052971;
   fWeightMatrix0to1[3][6] = -1.10033936288946;
   fWeightMatrix0to1[4][6] = -1.80989315335568;
   fWeightMatrix0to1[5][6] = -1.662273284205;
   fWeightMatrix0to1[6][6] = -0.23734599095845;
   fWeightMatrix0to1[7][6] = -0.699835387269251;
   fWeightMatrix0to1[8][6] = 1.92478784300567;
   fWeightMatrix0to1[9][6] = -2.01629782860786;
   fWeightMatrix0to1[10][6] = -0.435725213751591;
   fWeightMatrix0to1[11][6] = 1.53006848113025;
   fWeightMatrix0to1[12][6] = -2.13661616578189;
   fWeightMatrix0to1[13][6] = -1.56261627951732;
   fWeightMatrix0to1[0][7] = -1.4456814157286;
   fWeightMatrix0to1[1][7] = 0.0694069803923115;
   fWeightMatrix0to1[2][7] = -2.1161062868062;
   fWeightMatrix0to1[3][7] = -0.888016291084094;
   fWeightMatrix0to1[4][7] = 0.560228077096509;
   fWeightMatrix0to1[5][7] = 1.96185141897626;
   fWeightMatrix0to1[6][7] = -1.17459054184877;
   fWeightMatrix0to1[7][7] = 1.08498444868135;
   fWeightMatrix0to1[8][7] = -0.624951989925193;
   fWeightMatrix0to1[9][7] = -0.762277637517578;
   fWeightMatrix0to1[10][7] = 0.137586974669243;
   fWeightMatrix0to1[11][7] = 0.294712809268761;
   fWeightMatrix0to1[12][7] = -1.3376888753407;
   fWeightMatrix0to1[13][7] = 0.244245903184223;
   fWeightMatrix0to1[0][8] = 0.217828539152929;
   fWeightMatrix0to1[1][8] = 0.41577358503833;
   fWeightMatrix0to1[2][8] = -1.26235946217249;
   fWeightMatrix0to1[3][8] = 2.20266997064553;
   fWeightMatrix0to1[4][8] = 0.729548682715789;
   fWeightMatrix0to1[5][8] = -0.769926738154213;
   fWeightMatrix0to1[6][8] = 0.64027689755125;
   fWeightMatrix0to1[7][8] = -0.851314949271778;
   fWeightMatrix0to1[8][8] = -1.52084300316226;
   fWeightMatrix0to1[9][8] = 0.293130176482725;
   fWeightMatrix0to1[10][8] = -0.474874768682343;
   fWeightMatrix0to1[11][8] = 1.77202055721549;
   fWeightMatrix0to1[12][8] = 0.590950136808148;
   fWeightMatrix0to1[13][8] = -0.0286017984521865;
   fWeightMatrix0to1[0][9] = -0.389532904936352;
   fWeightMatrix0to1[1][9] = 0.183612466011939;
   fWeightMatrix0to1[2][9] = -1.43152026162527;
   fWeightMatrix0to1[3][9] = 1.43785254158649;
   fWeightMatrix0to1[4][9] = 0.0106228023275038;
   fWeightMatrix0to1[5][9] = -1.72842918302809;
   fWeightMatrix0to1[6][9] = 0.612237934084415;
   fWeightMatrix0to1[7][9] = -1.21904648550763;
   fWeightMatrix0to1[8][9] = 0.0995017521246949;
   fWeightMatrix0to1[9][9] = 1.33268788365843;
   fWeightMatrix0to1[10][9] = 1.59681072464466;
   fWeightMatrix0to1[11][9] = -1.85390930535285;
   fWeightMatrix0to1[12][9] = -0.354395816392571;
   fWeightMatrix0to1[13][9] = 1.56246995406742;
   fWeightMatrix0to1[0][10] = 1.44662096843488;
   fWeightMatrix0to1[1][10] = 0.184026553980495;
   fWeightMatrix0to1[2][10] = -2.03646313952218;
   fWeightMatrix0to1[3][10] = -0.206953206510866;
   fWeightMatrix0to1[4][10] = -1.9727209911635;
   fWeightMatrix0to1[5][10] = 1.37848547484491;
   fWeightMatrix0to1[6][10] = 1.15280670166939;
   fWeightMatrix0to1[7][10] = -0.274229523341361;
   fWeightMatrix0to1[8][10] = -0.422617907189696;
   fWeightMatrix0to1[9][10] = 0.220290897058661;
   fWeightMatrix0to1[10][10] = -1.51314863684463;
   fWeightMatrix0to1[11][10] = 0.497385327054218;
   fWeightMatrix0to1[12][10] = 1.07643586951331;
   fWeightMatrix0to1[13][10] = -0.464725167773364;
   fWeightMatrix0to1[0][11] = -0.254312790409153;
   fWeightMatrix0to1[1][11] = 0.355419849042526;
   fWeightMatrix0to1[2][11] = 1.38242494671511;
   fWeightMatrix0to1[3][11] = 0.492090467084222;
   fWeightMatrix0to1[4][11] = 0.468275577590055;
   fWeightMatrix0to1[5][11] = -1.67556722950962;
   fWeightMatrix0to1[6][11] = 1.5505231329818;
   fWeightMatrix0to1[7][11] = 1.34592888564399;
   fWeightMatrix0to1[8][11] = 0.073881133386035;
   fWeightMatrix0to1[9][11] = 0.519992247873851;
   fWeightMatrix0to1[10][11] = 0.63954278703078;
   fWeightMatrix0to1[11][11] = -0.624765686101239;
   fWeightMatrix0to1[12][11] = -0.940715120823614;
   fWeightMatrix0to1[13][11] = 1.12116722040741;
   fWeightMatrix0to1[0][12] = -0.757289166027304;
   fWeightMatrix0to1[1][12] = -0.548334173268706;
   fWeightMatrix0to1[2][12] = 1.49380506282433;
   fWeightMatrix0to1[3][12] = 1.06905239043521;
   fWeightMatrix0to1[4][12] = 0.096338147544157;
   fWeightMatrix0to1[5][12] = 1.46075095830558;
   fWeightMatrix0to1[6][12] = 1.86597504235445;
   fWeightMatrix0to1[7][12] = -1.73620998372748;
   fWeightMatrix0to1[8][12] = 0.436198217793559;
   fWeightMatrix0to1[9][12] = 0.0184346019343417;
   fWeightMatrix0to1[10][12] = 0.413744021445777;
   fWeightMatrix0to1[11][12] = -1.74209377904684;
   fWeightMatrix0to1[12][12] = -0.457212936328683;
   fWeightMatrix0to1[13][12] = 1.11529701414865;
   fWeightMatrix0to1[0][13] = 1.35194557230306;
   fWeightMatrix0to1[1][13] = -1.9185623036513;
   fWeightMatrix0to1[2][13] = -0.643753755296557;
   fWeightMatrix0to1[3][13] = -0.572593454294165;
   fWeightMatrix0to1[4][13] = 0.79681609237844;
   fWeightMatrix0to1[5][13] = 2.05736028494968;
   fWeightMatrix0to1[6][13] = -0.588134133836722;
   fWeightMatrix0to1[7][13] = -1.25517136668423;
   fWeightMatrix0to1[8][13] = -0.461096564062729;
   fWeightMatrix0to1[9][13] = 0.91608357167012;
   fWeightMatrix0to1[10][13] = 2.13711492479029;
   fWeightMatrix0to1[11][13] = 1.10303311936445;
   fWeightMatrix0to1[12][13] = 0.48697747642091;
   fWeightMatrix0to1[13][13] = -0.92157106975294;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.03816246487938;
   fWeightMatrix1to2[1][0] = 0.917420002093654;
   fWeightMatrix1to2[2][0] = 0.236088850866418;
   fWeightMatrix1to2[3][0] = -1.22938052678193;
   fWeightMatrix1to2[4][0] = -0.442074548826415;
   fWeightMatrix1to2[5][0] = 0.34089822226431;
   fWeightMatrix1to2[6][0] = 0.16744283112496;
   fWeightMatrix1to2[7][0] = -2.20407442115246;
   fWeightMatrix1to2[8][0] = 1.4326223154544;
   fWeightMatrix1to2[9][0] = 0.261874865853728;
   fWeightMatrix1to2[10][0] = -0.331769339830107;
   fWeightMatrix1to2[11][0] = -0.153815419541412;
   fWeightMatrix1to2[12][0] = 1.41110385351515;
   fWeightMatrix1to2[0][1] = 0.987085952325085;
   fWeightMatrix1to2[1][1] = 0.284287398324255;
   fWeightMatrix1to2[2][1] = 0.0281043336884451;
   fWeightMatrix1to2[3][1] = -2.15854014774014;
   fWeightMatrix1to2[4][1] = -0.782944322925562;
   fWeightMatrix1to2[5][1] = 1.70071078842487;
   fWeightMatrix1to2[6][1] = 1.45770877491629;
   fWeightMatrix1to2[7][1] = 0.52676079867769;
   fWeightMatrix1to2[8][1] = 0.204647175625987;
   fWeightMatrix1to2[9][1] = 2.068294295181;
   fWeightMatrix1to2[10][1] = -2.00780335397646;
   fWeightMatrix1to2[11][1] = -1.34068990020422;
   fWeightMatrix1to2[12][1] = -0.364527604555161;
   fWeightMatrix1to2[0][2] = -1.36523005090811;
   fWeightMatrix1to2[1][2] = 0.812405215344433;
   fWeightMatrix1to2[2][2] = 1.88783552790821;
   fWeightMatrix1to2[3][2] = -1.31485903936541;
   fWeightMatrix1to2[4][2] = 0.668126945434882;
   fWeightMatrix1to2[5][2] = -0.0271117025403262;
   fWeightMatrix1to2[6][2] = -1.63995964749018;
   fWeightMatrix1to2[7][2] = -0.938622196126912;
   fWeightMatrix1to2[8][2] = 1.06677309904357;
   fWeightMatrix1to2[9][2] = 0.153728877178132;
   fWeightMatrix1to2[10][2] = 0.834471962717781;
   fWeightMatrix1to2[11][2] = -1.12736120548027;
   fWeightMatrix1to2[12][2] = 1.52111056975725;
   fWeightMatrix1to2[0][3] = -1.75639677408994;
   fWeightMatrix1to2[1][3] = 0.657514946676043;
   fWeightMatrix1to2[2][3] = -0.0543533236198397;
   fWeightMatrix1to2[3][3] = -1.33172201457514;
   fWeightMatrix1to2[4][3] = -1.16890543176288;
   fWeightMatrix1to2[5][3] = -1.93985826870881;
   fWeightMatrix1to2[6][3] = -0.206806090157889;
   fWeightMatrix1to2[7][3] = -2.01894765800099;
   fWeightMatrix1to2[8][3] = -1.50199660198033;
   fWeightMatrix1to2[9][3] = -2.19837126679714;
   fWeightMatrix1to2[10][3] = 0.262493679986433;
   fWeightMatrix1to2[11][3] = -1.01330581796461;
   fWeightMatrix1to2[12][3] = -1.75551978774536;
   fWeightMatrix1to2[0][4] = 1.40326709218609;
   fWeightMatrix1to2[1][4] = -0.815431025411285;
   fWeightMatrix1to2[2][4] = 1.26258070998664;
   fWeightMatrix1to2[3][4] = -0.88250550955009;
   fWeightMatrix1to2[4][4] = 0.01886598665318;
   fWeightMatrix1to2[5][4] = 1.83408573819039;
   fWeightMatrix1to2[6][4] = 1.30704496694566;
   fWeightMatrix1to2[7][4] = -1.06819104828979;
   fWeightMatrix1to2[8][4] = -1.55499148817969;
   fWeightMatrix1to2[9][4] = -2.729366542484;
   fWeightMatrix1to2[10][4] = -0.601137822998992;
   fWeightMatrix1to2[11][4] = -1.62416260398388;
   fWeightMatrix1to2[12][4] = 0.176851538633384;
   fWeightMatrix1to2[0][5] = 0.248925767578657;
   fWeightMatrix1to2[1][5] = 2.06880889238083;
   fWeightMatrix1to2[2][5] = 0.486736837696029;
   fWeightMatrix1to2[3][5] = 0.343161089402585;
   fWeightMatrix1to2[4][5] = -0.676059828653864;
   fWeightMatrix1to2[5][5] = -1.94445377624638;
   fWeightMatrix1to2[6][5] = 1.05752182618914;
   fWeightMatrix1to2[7][5] = 1.31698249766568;
   fWeightMatrix1to2[8][5] = -0.864759376543168;
   fWeightMatrix1to2[9][5] = -1.03397628699186;
   fWeightMatrix1to2[10][5] = 0.903828338249177;
   fWeightMatrix1to2[11][5] = 1.22178346087045;
   fWeightMatrix1to2[12][5] = 0.643047339333485;
   fWeightMatrix1to2[0][6] = -0.519982989244042;
   fWeightMatrix1to2[1][6] = -0.511316772075853;
   fWeightMatrix1to2[2][6] = 1.61161569944707;
   fWeightMatrix1to2[3][6] = 0.78619712467984;
   fWeightMatrix1to2[4][6] = 1.12967546185649;
   fWeightMatrix1to2[5][6] = -0.306418173252169;
   fWeightMatrix1to2[6][6] = 0.378709509798283;
   fWeightMatrix1to2[7][6] = -0.514216352626703;
   fWeightMatrix1to2[8][6] = -1.4684520946652;
   fWeightMatrix1to2[9][6] = -0.440995846079171;
   fWeightMatrix1to2[10][6] = -1.91351852610825;
   fWeightMatrix1to2[11][6] = -1.41675702984517;
   fWeightMatrix1to2[12][6] = -1.76981739748868;
   fWeightMatrix1to2[0][7] = 1.62620764925926;
   fWeightMatrix1to2[1][7] = -1.88925932612913;
   fWeightMatrix1to2[2][7] = 1.78700743183072;
   fWeightMatrix1to2[3][7] = -1.76679391268177;
   fWeightMatrix1to2[4][7] = 1.16560991647179;
   fWeightMatrix1to2[5][7] = -1.11619916051659;
   fWeightMatrix1to2[6][7] = 0.481765872074283;
   fWeightMatrix1to2[7][7] = 0.592571144700031;
   fWeightMatrix1to2[8][7] = -1.77983798328709;
   fWeightMatrix1to2[9][7] = -0.0480291634291174;
   fWeightMatrix1to2[10][7] = 0.312991798007818;
   fWeightMatrix1to2[11][7] = -1.98431779900583;
   fWeightMatrix1to2[12][7] = -1.65720577801182;
   fWeightMatrix1to2[0][8] = -1.65753824929418;
   fWeightMatrix1to2[1][8] = -0.894423423577733;
   fWeightMatrix1to2[2][8] = 1.71274265262017;
   fWeightMatrix1to2[3][8] = -0.581383068074535;
   fWeightMatrix1to2[4][8] = 0.135676537369021;
   fWeightMatrix1to2[5][8] = -0.80975373951965;
   fWeightMatrix1to2[6][8] = -1.06628695686955;
   fWeightMatrix1to2[7][8] = -1.30923728122132;
   fWeightMatrix1to2[8][8] = -1.05590100501385;
   fWeightMatrix1to2[9][8] = -0.2182864689254;
   fWeightMatrix1to2[10][8] = 0.66570390395896;
   fWeightMatrix1to2[11][8] = -1.33098032293339;
   fWeightMatrix1to2[12][8] = -0.991327202162208;
   fWeightMatrix1to2[0][9] = 1.72368429400286;
   fWeightMatrix1to2[1][9] = 0.1176461171218;
   fWeightMatrix1to2[2][9] = -0.663701502448222;
   fWeightMatrix1to2[3][9] = 2.06472836935403;
   fWeightMatrix1to2[4][9] = -1.66003715128978;
   fWeightMatrix1to2[5][9] = 1.39553368819213;
   fWeightMatrix1to2[6][9] = 1.14806657033139;
   fWeightMatrix1to2[7][9] = -1.20368323601374;
   fWeightMatrix1to2[8][9] = -0.805525746581236;
   fWeightMatrix1to2[9][9] = -0.897144207728537;
   fWeightMatrix1to2[10][9] = -0.792233763854175;
   fWeightMatrix1to2[11][9] = 0.489890245888767;
   fWeightMatrix1to2[12][9] = 1.70999188728233;
   fWeightMatrix1to2[0][10] = 1.42637389879762;
   fWeightMatrix1to2[1][10] = 1.74920250445584;
   fWeightMatrix1to2[2][10] = -1.24029273162907;
   fWeightMatrix1to2[3][10] = 1.25565239123635;
   fWeightMatrix1to2[4][10] = -2.15203772180313;
   fWeightMatrix1to2[5][10] = 0.626159896967556;
   fWeightMatrix1to2[6][10] = -1.82896787852748;
   fWeightMatrix1to2[7][10] = -1.61808747549475;
   fWeightMatrix1to2[8][10] = -0.0647880390556652;
   fWeightMatrix1to2[9][10] = 1.11971734701373;
   fWeightMatrix1to2[10][10] = 0.727976491349492;
   fWeightMatrix1to2[11][10] = 1.0794454267131;
   fWeightMatrix1to2[12][10] = 0.521443625172788;
   fWeightMatrix1to2[0][11] = -0.112303242782274;
   fWeightMatrix1to2[1][11] = -0.502272331598075;
   fWeightMatrix1to2[2][11] = 0.297655327867567;
   fWeightMatrix1to2[3][11] = 1.88034478337425;
   fWeightMatrix1to2[4][11] = -1.67942239608921;
   fWeightMatrix1to2[5][11] = 0.326713242586592;
   fWeightMatrix1to2[6][11] = -1.65280165595326;
   fWeightMatrix1to2[7][11] = -0.208990445066033;
   fWeightMatrix1to2[8][11] = 0.0675070406701967;
   fWeightMatrix1to2[9][11] = 0.384346208593706;
   fWeightMatrix1to2[10][11] = -0.889282453585156;
   fWeightMatrix1to2[11][11] = 1.0026852824576;
   fWeightMatrix1to2[12][11] = 1.8983359475125;
   fWeightMatrix1to2[0][12] = 0.74584655859828;
   fWeightMatrix1to2[1][12] = -0.221112702265215;
   fWeightMatrix1to2[2][12] = -1.65614301918366;
   fWeightMatrix1to2[3][12] = -1.2782280235893;
   fWeightMatrix1to2[4][12] = -1.65359764601576;
   fWeightMatrix1to2[5][12] = 1.06731964145911;
   fWeightMatrix1to2[6][12] = -0.3436073111327;
   fWeightMatrix1to2[7][12] = -1.02262328782982;
   fWeightMatrix1to2[8][12] = 0.499576897616663;
   fWeightMatrix1to2[9][12] = -2.44791943000408;
   fWeightMatrix1to2[10][12] = -0.858155188970085;
   fWeightMatrix1to2[11][12] = -1.58249351268334;
   fWeightMatrix1to2[12][12] = 0.861737729403386;
   fWeightMatrix1to2[0][13] = -1.42227360462298;
   fWeightMatrix1to2[1][13] = -1.69779642838965;
   fWeightMatrix1to2[2][13] = -0.432287608444141;
   fWeightMatrix1to2[3][13] = -0.951329871958431;
   fWeightMatrix1to2[4][13] = -1.48114475191985;
   fWeightMatrix1to2[5][13] = 1.17017865374086;
   fWeightMatrix1to2[6][13] = -1.3282515536688;
   fWeightMatrix1to2[7][13] = -1.45926189867594;
   fWeightMatrix1to2[8][13] = 1.7472476169739;
   fWeightMatrix1to2[9][13] = 0.455484024325688;
   fWeightMatrix1to2[10][13] = 0.46958777764299;
   fWeightMatrix1to2[11][13] = 0.0632654764442132;
   fWeightMatrix1to2[12][13] = 1.10552054848961;
   fWeightMatrix1to2[0][14] = 1.7707091559416;
   fWeightMatrix1to2[1][14] = 0.73163780832966;
   fWeightMatrix1to2[2][14] = -1.10620246751897;
   fWeightMatrix1to2[3][14] = -0.480428176612439;
   fWeightMatrix1to2[4][14] = -1.87728571656173;
   fWeightMatrix1to2[5][14] = 0.924626512397778;
   fWeightMatrix1to2[6][14] = 0.792568054251273;
   fWeightMatrix1to2[7][14] = 0.327824508425594;
   fWeightMatrix1to2[8][14] = 1.08958115433648;
   fWeightMatrix1to2[9][14] = 0.843981256460445;
   fWeightMatrix1to2[10][14] = 1.93472237393687;
   fWeightMatrix1to2[11][14] = -1.30820660532002;
   fWeightMatrix1to2[12][14] = 1.98246233333038;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.0352977031125024;
   fWeightMatrix2to3[0][1] = -1.66023857172478;
   fWeightMatrix2to3[0][2] = -1.14670632162622;
   fWeightMatrix2to3[0][3] = -0.868956315061054;
   fWeightMatrix2to3[0][4] = 0.16172645311758;
   fWeightMatrix2to3[0][5] = 0.0121775668970508;
   fWeightMatrix2to3[0][6] = 0.0509677788546067;
   fWeightMatrix2to3[0][7] = 0.00490727237360521;
   fWeightMatrix2to3[0][8] = -0.0190874122332393;
   fWeightMatrix2to3[0][9] = 1.01598540115875;
   fWeightMatrix2to3[0][10] = 1.07334234929817;
   fWeightMatrix2to3[0][11] = -0.00786119702842719;
   fWeightMatrix2to3[0][12] = -1.07840808396988;
   fWeightMatrix2to3[0][13] = 1.63233243629028;
}

inline double ReadMLP1_25_EC_1x1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1_25_EC_1x1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1_25_EC_1x1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1_25_EC_1x1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
