// Class: ReadMLP1_5_EC_10x10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Tue Sep 22 14:54:51 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 2455


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,9.936668396]
ClusterParameters.end         ClusterParameters.end             'F'    [4.56421089172,29.1329498291]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,22.8278827667]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.949683308601]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0876754596829,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.450747281313,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.0782214403152,0.999999582767]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999996840954]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.979804337025,26.9941825867]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.0691780373454,0.926156163216]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,103]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [53.6119613647,599866.25]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-1.98519515991,21.6346168518]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1_5_EC_10x10 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1_5_EC_10x10( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1_5_EC_10x10" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 9.93666839599609;
      fVmin[1] = 4.56421089172363;
      fVmax[1] = 29.1329498291016;
      fVmin[2] = 0;
      fVmax[2] = 22.8278827667236;
      fVmin[3] = 0;
      fVmax[3] = 0.949683308601379;
      fVmin[4] = 0.0876754596829414;
      fVmax[4] = 1;
      fVmin[5] = 0.450747281312943;
      fVmax[5] = 1;
      fVmin[6] = 0.0782214403152466;
      fVmax[6] = 0.999999582767487;
      fVmin[7] = 0;
      fVmax[7] = 0.999996840953827;
      fVmin[8] = 0.979804337024689;
      fVmax[8] = 26.9941825866699;
      fVmin[9] = 0.0691780373454094;
      fVmax[9] = 0.926156163215637;
      fVmin[10] = 5;
      fVmax[10] = 103;
      fVmin[11] = 53.6119613647461;
      fVmax[11] = 599866.25;
      fVmin[12] = -1.98519515991211;
      fVmax[12] = 21.6346168518066;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1_5_EC_10x10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1_5_EC_10x10::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.500318908082804;
   fWeightMatrix0to1[1][0] = 1.85872077095623;
   fWeightMatrix0to1[2][0] = 0.311879966104102;
   fWeightMatrix0to1[3][0] = 2.10460281698708;
   fWeightMatrix0to1[4][0] = -1.44269526098778;
   fWeightMatrix0to1[5][0] = -1.64134413589503;
   fWeightMatrix0to1[6][0] = -0.482565016103193;
   fWeightMatrix0to1[7][0] = 1.47509475798378;
   fWeightMatrix0to1[8][0] = -1.05930901797789;
   fWeightMatrix0to1[9][0] = -1.17542878902271;
   fWeightMatrix0to1[10][0] = -1.52913221717205;
   fWeightMatrix0to1[11][0] = -0.288823840614337;
   fWeightMatrix0to1[12][0] = -0.976172300687038;
   fWeightMatrix0to1[13][0] = -0.4771801663285;
   fWeightMatrix0to1[0][1] = -0.527408497488349;
   fWeightMatrix0to1[1][1] = 0.611602760797794;
   fWeightMatrix0to1[2][1] = -0.553720982511514;
   fWeightMatrix0to1[3][1] = 1.74760237045767;
   fWeightMatrix0to1[4][1] = 0.543007375324152;
   fWeightMatrix0to1[5][1] = 1.1235686533924;
   fWeightMatrix0to1[6][1] = -0.265167880895806;
   fWeightMatrix0to1[7][1] = -1.0643181849866;
   fWeightMatrix0to1[8][1] = 0.8547905968598;
   fWeightMatrix0to1[9][1] = 0.296473638850611;
   fWeightMatrix0to1[10][1] = -1.13440100001893;
   fWeightMatrix0to1[11][1] = -0.277891071224773;
   fWeightMatrix0to1[12][1] = 0.985641252674359;
   fWeightMatrix0to1[13][1] = -1.07312675411868;
   fWeightMatrix0to1[0][2] = -1.91101640686559;
   fWeightMatrix0to1[1][2] = 0.0631888281446792;
   fWeightMatrix0to1[2][2] = 0.463437314513849;
   fWeightMatrix0to1[3][2] = 1.62786426210474;
   fWeightMatrix0to1[4][2] = 0.10201089195987;
   fWeightMatrix0to1[5][2] = -0.0673361408573888;
   fWeightMatrix0to1[6][2] = 0.190032657359044;
   fWeightMatrix0to1[7][2] = -0.703290462057594;
   fWeightMatrix0to1[8][2] = -1.67220772665357;
   fWeightMatrix0to1[9][2] = 2.54111287705254;
   fWeightMatrix0to1[10][2] = -1.03849736934343;
   fWeightMatrix0to1[11][2] = 1.09863956423851;
   fWeightMatrix0to1[12][2] = 1.53257962657125;
   fWeightMatrix0to1[13][2] = 0.845227550121398;
   fWeightMatrix0to1[0][3] = 2.1052143653413;
   fWeightMatrix0to1[1][3] = 1.41666622690425;
   fWeightMatrix0to1[2][3] = -0.893717902053344;
   fWeightMatrix0to1[3][3] = -1.63350947978719;
   fWeightMatrix0to1[4][3] = 0.444886212155066;
   fWeightMatrix0to1[5][3] = -0.278033978031139;
   fWeightMatrix0to1[6][3] = 1.63140946235205;
   fWeightMatrix0to1[7][3] = 1.6950763743058;
   fWeightMatrix0to1[8][3] = 2.02059411800564;
   fWeightMatrix0to1[9][3] = 1.28732896711834;
   fWeightMatrix0to1[10][3] = -1.32718319220317;
   fWeightMatrix0to1[11][3] = 1.3478358950882;
   fWeightMatrix0to1[12][3] = -3.04662816685763;
   fWeightMatrix0to1[13][3] = -1.03557641531116;
   fWeightMatrix0to1[0][4] = -1.4620493847125;
   fWeightMatrix0to1[1][4] = -1.59067933714759;
   fWeightMatrix0to1[2][4] = 1.82279005895006;
   fWeightMatrix0to1[3][4] = 0.89962445353914;
   fWeightMatrix0to1[4][4] = -2.07147357062472;
   fWeightMatrix0to1[5][4] = 0.0394485366813563;
   fWeightMatrix0to1[6][4] = -0.279964503922779;
   fWeightMatrix0to1[7][4] = 1.21870619695338;
   fWeightMatrix0to1[8][4] = 1.97520085769476;
   fWeightMatrix0to1[9][4] = -0.846580966521575;
   fWeightMatrix0to1[10][4] = 0.507401646139966;
   fWeightMatrix0to1[11][4] = -1.03091750645868;
   fWeightMatrix0to1[12][4] = -0.662108001497937;
   fWeightMatrix0to1[13][4] = -0.927036786488414;
   fWeightMatrix0to1[0][5] = -1.03021851150821;
   fWeightMatrix0to1[1][5] = -1.39863908812487;
   fWeightMatrix0to1[2][5] = 1.21167009478075;
   fWeightMatrix0to1[3][5] = 1.14397805757819;
   fWeightMatrix0to1[4][5] = 1.13678370955979;
   fWeightMatrix0to1[5][5] = -0.446758244701094;
   fWeightMatrix0to1[6][5] = -1.94754381331646;
   fWeightMatrix0to1[7][5] = -1.4868159928408;
   fWeightMatrix0to1[8][5] = 0.743849075943364;
   fWeightMatrix0to1[9][5] = 0.536629132757208;
   fWeightMatrix0to1[10][5] = 2.40992354922961;
   fWeightMatrix0to1[11][5] = 0.691136066865818;
   fWeightMatrix0to1[12][5] = 0.851994923387146;
   fWeightMatrix0to1[13][5] = -0.779549399844143;
   fWeightMatrix0to1[0][6] = -1.15169150005164;
   fWeightMatrix0to1[1][6] = -0.287391573724305;
   fWeightMatrix0to1[2][6] = 1.70796676678708;
   fWeightMatrix0to1[3][6] = -1.06808306324634;
   fWeightMatrix0to1[4][6] = -1.81762812085614;
   fWeightMatrix0to1[5][6] = -1.99250805601204;
   fWeightMatrix0to1[6][6] = -0.402947279471141;
   fWeightMatrix0to1[7][6] = 0.219403489989382;
   fWeightMatrix0to1[8][6] = 1.42854324065509;
   fWeightMatrix0to1[9][6] = -1.64724474586943;
   fWeightMatrix0to1[10][6] = -0.495987712868302;
   fWeightMatrix0to1[11][6] = 1.67904919720299;
   fWeightMatrix0to1[12][6] = -1.61988266774636;
   fWeightMatrix0to1[13][6] = -1.52390142476158;
   fWeightMatrix0to1[0][7] = -1.55106587668388;
   fWeightMatrix0to1[1][7] = 0.169896297690806;
   fWeightMatrix0to1[2][7] = -1.36603944461672;
   fWeightMatrix0to1[3][7] = -1.4419998605723;
   fWeightMatrix0to1[4][7] = 0.288845021178027;
   fWeightMatrix0to1[5][7] = 2.05203668945781;
   fWeightMatrix0to1[6][7] = -1.10759866497557;
   fWeightMatrix0to1[7][7] = 1.82624670435007;
   fWeightMatrix0to1[8][7] = -0.318955674288769;
   fWeightMatrix0to1[9][7] = -0.845057915410569;
   fWeightMatrix0to1[10][7] = 0.0389193647441893;
   fWeightMatrix0to1[11][7] = 0.705284169324804;
   fWeightMatrix0to1[12][7] = -2.67925665264776;
   fWeightMatrix0to1[13][7] = 0.35432994327448;
   fWeightMatrix0to1[0][8] = 0.393733813521723;
   fWeightMatrix0to1[1][8] = 0.317890590190856;
   fWeightMatrix0to1[2][8] = -1.52208252279064;
   fWeightMatrix0to1[3][8] = 1.67191593610458;
   fWeightMatrix0to1[4][8] = 0.42344199536064;
   fWeightMatrix0to1[5][8] = -0.698042214725087;
   fWeightMatrix0to1[6][8] = 0.698290223705337;
   fWeightMatrix0to1[7][8] = -1.30418373474747;
   fWeightMatrix0to1[8][8] = -1.75591591734199;
   fWeightMatrix0to1[9][8] = 0.126279609409495;
   fWeightMatrix0to1[10][8] = -0.67867784938964;
   fWeightMatrix0to1[11][8] = 1.67254251419273;
   fWeightMatrix0to1[12][8] = 0.827090838565937;
   fWeightMatrix0to1[13][8] = -0.0142108831915324;
   fWeightMatrix0to1[0][9] = -0.180122381202441;
   fWeightMatrix0to1[1][9] = 0.0333117635576113;
   fWeightMatrix0to1[2][9] = -1.89895145245332;
   fWeightMatrix0to1[3][9] = 1.06527085050811;
   fWeightMatrix0to1[4][9] = -0.359172318224206;
   fWeightMatrix0to1[5][9] = -1.19073621010353;
   fWeightMatrix0to1[6][9] = 0.627971599247582;
   fWeightMatrix0to1[7][9] = -1.31475309486138;
   fWeightMatrix0to1[8][9] = 0.12388981388469;
   fWeightMatrix0to1[9][9] = 0.597943908097763;
   fWeightMatrix0to1[10][9] = 1.54643078902266;
   fWeightMatrix0to1[11][9] = -1.90936169064215;
   fWeightMatrix0to1[12][9] = 0.573909383553273;
   fWeightMatrix0to1[13][9] = 1.48568288062599;
   fWeightMatrix0to1[0][10] = 1.58340431761131;
   fWeightMatrix0to1[1][10] = 0.208893401659231;
   fWeightMatrix0to1[2][10] = -1.62868586211716;
   fWeightMatrix0to1[3][10] = -0.167574881107423;
   fWeightMatrix0to1[4][10] = -1.52642426278324;
   fWeightMatrix0to1[5][10] = 1.71792789012759;
   fWeightMatrix0to1[6][10] = 1.13534439542519;
   fWeightMatrix0to1[7][10] = -0.137675425885968;
   fWeightMatrix0to1[8][10] = -0.175519426466802;
   fWeightMatrix0to1[9][10] = -0.46839909373594;
   fWeightMatrix0to1[10][10] = -1.44208362101359;
   fWeightMatrix0to1[11][10] = 0.435817031107446;
   fWeightMatrix0to1[12][10] = 0.819119843874269;
   fWeightMatrix0to1[13][10] = -0.665646958945153;
   fWeightMatrix0to1[0][11] = -0.260014502649989;
   fWeightMatrix0to1[1][11] = 0.440950125846071;
   fWeightMatrix0to1[2][11] = 0.485498637153274;
   fWeightMatrix0to1[3][11] = 0.426701304870364;
   fWeightMatrix0to1[4][11] = 1.15137511846562;
   fWeightMatrix0to1[5][11] = -1.48196014825559;
   fWeightMatrix0to1[6][11] = 1.70812368369312;
   fWeightMatrix0to1[7][11] = 0.577365079412247;
   fWeightMatrix0to1[8][11] = 0.770977912229329;
   fWeightMatrix0to1[9][11] = 0.533572288804647;
   fWeightMatrix0to1[10][11] = 0.796249497970834;
   fWeightMatrix0to1[11][11] = -0.643291506445066;
   fWeightMatrix0to1[12][11] = -0.814465816199668;
   fWeightMatrix0to1[13][11] = 1.0217605473681;
   fWeightMatrix0to1[0][12] = -0.730393204545862;
   fWeightMatrix0to1[1][12] = -0.526973781669151;
   fWeightMatrix0to1[2][12] = 1.44284780301614;
   fWeightMatrix0to1[3][12] = 0.854785317299817;
   fWeightMatrix0to1[4][12] = -0.0969081595606384;
   fWeightMatrix0to1[5][12] = 1.68553806147307;
   fWeightMatrix0to1[6][12] = 1.78256051818089;
   fWeightMatrix0to1[7][12] = -2.12468000579584;
   fWeightMatrix0to1[8][12] = 0.442229986323446;
   fWeightMatrix0to1[9][12] = 0.583083404104734;
   fWeightMatrix0to1[10][12] = 0.543206589962613;
   fWeightMatrix0to1[11][12] = -1.78596772240096;
   fWeightMatrix0to1[12][12] = -1.41599270233374;
   fWeightMatrix0to1[13][12] = 1.10167320065255;
   fWeightMatrix0to1[0][13] = 1.31241680887772;
   fWeightMatrix0to1[1][13] = -1.96800954677913;
   fWeightMatrix0to1[2][13] = 0.390781539661619;
   fWeightMatrix0to1[3][13] = -0.677224150641866;
   fWeightMatrix0to1[4][13] = 0.290116301366337;
   fWeightMatrix0to1[5][13] = 1.78451613676107;
   fWeightMatrix0to1[6][13] = -0.703126893923867;
   fWeightMatrix0to1[7][13] = -0.554996640491539;
   fWeightMatrix0to1[8][13] = -1.62215861445281;
   fWeightMatrix0to1[9][13] = 1.81372893418055;
   fWeightMatrix0to1[10][13] = 1.83823703807473;
   fWeightMatrix0to1[11][13] = 1.13598693941289;
   fWeightMatrix0to1[12][13] = 0.56118790152224;
   fWeightMatrix0to1[13][13] = -0.653957259128015;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.76801587676981;
   fWeightMatrix1to2[1][0] = 0.797370599329287;
   fWeightMatrix1to2[2][0] = 0.0591111732527881;
   fWeightMatrix1to2[3][0] = -1.34663878883536;
   fWeightMatrix1to2[4][0] = -0.604600904485451;
   fWeightMatrix1to2[5][0] = 0.267472071175641;
   fWeightMatrix1to2[6][0] = 0.11316071505093;
   fWeightMatrix1to2[7][0] = -2.23847280879314;
   fWeightMatrix1to2[8][0] = 1.51207772626143;
   fWeightMatrix1to2[9][0] = 0.868483557247105;
   fWeightMatrix1to2[10][0] = -0.295085575260631;
   fWeightMatrix1to2[11][0] = -0.22304556038901;
   fWeightMatrix1to2[12][0] = 1.39759599701439;
   fWeightMatrix1to2[0][1] = 0.851513950232568;
   fWeightMatrix1to2[1][1] = 0.0020383968888905;
   fWeightMatrix1to2[2][1] = -0.224282231760187;
   fWeightMatrix1to2[3][1] = -1.79597060024229;
   fWeightMatrix1to2[4][1] = -0.709941660660509;
   fWeightMatrix1to2[5][1] = 1.64952099788661;
   fWeightMatrix1to2[6][1] = 1.50356051056599;
   fWeightMatrix1to2[7][1] = 0.61374547980342;
   fWeightMatrix1to2[8][1] = 0.0695947002312984;
   fWeightMatrix1to2[9][1] = 2.12546304747247;
   fWeightMatrix1to2[10][1] = -1.91757424401262;
   fWeightMatrix1to2[11][1] = -1.30345790124467;
   fWeightMatrix1to2[12][1] = -0.362559864598144;
   fWeightMatrix1to2[0][2] = -1.28190036211098;
   fWeightMatrix1to2[1][2] = 1.09527775437081;
   fWeightMatrix1to2[2][2] = 1.82870572044216;
   fWeightMatrix1to2[3][2] = -1.40268854239536;
   fWeightMatrix1to2[4][2] = 0.5544844349789;
   fWeightMatrix1to2[5][2] = -0.0577102990145426;
   fWeightMatrix1to2[6][2] = -1.58301502776743;
   fWeightMatrix1to2[7][2] = -0.945824004823457;
   fWeightMatrix1to2[8][2] = 1.02308788859234;
   fWeightMatrix1to2[9][2] = 0.278898179738688;
   fWeightMatrix1to2[10][2] = 0.899035557975519;
   fWeightMatrix1to2[11][2] = -1.16559898308947;
   fWeightMatrix1to2[12][2] = 1.85620151662313;
   fWeightMatrix1to2[0][3] = -1.39067420538558;
   fWeightMatrix1to2[1][3] = 0.493829790939578;
   fWeightMatrix1to2[2][3] = 0.0379252673273296;
   fWeightMatrix1to2[3][3] = -1.52771398956679;
   fWeightMatrix1to2[4][3] = -1.01478339080612;
   fWeightMatrix1to2[5][3] = -1.99614143926341;
   fWeightMatrix1to2[6][3] = -0.275105884453511;
   fWeightMatrix1to2[7][3] = -1.8057768778402;
   fWeightMatrix1to2[8][3] = -1.37652190635804;
   fWeightMatrix1to2[9][3] = -1.87783842254342;
   fWeightMatrix1to2[10][3] = 0.111314111873656;
   fWeightMatrix1to2[11][3] = -0.832253683796227;
   fWeightMatrix1to2[12][3] = -1.85539980149342;
   fWeightMatrix1to2[0][4] = 1.38370596176481;
   fWeightMatrix1to2[1][4] = -0.858472188514704;
   fWeightMatrix1to2[2][4] = 0.202147512314478;
   fWeightMatrix1to2[3][4] = -0.997756151180668;
   fWeightMatrix1to2[4][4] = -0.71639755681334;
   fWeightMatrix1to2[5][4] = 1.86015912530059;
   fWeightMatrix1to2[6][4] = 1.26760085353777;
   fWeightMatrix1to2[7][4] = -0.856439371022142;
   fWeightMatrix1to2[8][4] = -1.1678702152614;
   fWeightMatrix1to2[9][4] = -1.14834799500274;
   fWeightMatrix1to2[10][4] = -0.819223014686633;
   fWeightMatrix1to2[11][4] = -1.49545562625887;
   fWeightMatrix1to2[12][4] = 0.235716464539129;
   fWeightMatrix1to2[0][5] = 0.115226385510915;
   fWeightMatrix1to2[1][5] = 2.08066819148217;
   fWeightMatrix1to2[2][5] = -0.00465504916628531;
   fWeightMatrix1to2[3][5] = 0.271117484491528;
   fWeightMatrix1to2[4][5] = -0.849096567099122;
   fWeightMatrix1to2[5][5] = -1.87701930333591;
   fWeightMatrix1to2[6][5] = 1.06784060058292;
   fWeightMatrix1to2[7][5] = 1.31725593492248;
   fWeightMatrix1to2[8][5] = -1.42391624761836;
   fWeightMatrix1to2[9][5] = -1.21352274481399;
   fWeightMatrix1to2[10][5] = 0.784271122747638;
   fWeightMatrix1to2[11][5] = 1.438553258468;
   fWeightMatrix1to2[12][5] = 0.57750133225132;
   fWeightMatrix1to2[0][6] = -0.56598050344047;
   fWeightMatrix1to2[1][6] = -0.575353853193138;
   fWeightMatrix1to2[2][6] = 1.38492854133305;
   fWeightMatrix1to2[3][6] = 1.11605906280254;
   fWeightMatrix1to2[4][6] = 1.20341105050895;
   fWeightMatrix1to2[5][6] = -0.37038139241832;
   fWeightMatrix1to2[6][6] = 0.451497088740786;
   fWeightMatrix1to2[7][6] = -0.431358549298969;
   fWeightMatrix1to2[8][6] = -1.55800949002058;
   fWeightMatrix1to2[9][6] = -0.395125756343629;
   fWeightMatrix1to2[10][6] = -1.87409811753566;
   fWeightMatrix1to2[11][6] = -1.29163299330503;
   fWeightMatrix1to2[12][6] = -1.76873283515795;
   fWeightMatrix1to2[0][7] = 1.78362314525056;
   fWeightMatrix1to2[1][7] = -1.6027388105284;
   fWeightMatrix1to2[2][7] = 1.65091152888259;
   fWeightMatrix1to2[3][7] = -1.37604717911146;
   fWeightMatrix1to2[4][7] = 0.943497832339124;
   fWeightMatrix1to2[5][7] = -1.15325919702054;
   fWeightMatrix1to2[6][7] = 0.610799636433803;
   fWeightMatrix1to2[7][7] = 0.697661167013344;
   fWeightMatrix1to2[8][7] = -1.72853825311102;
   fWeightMatrix1to2[9][7] = 0.309540966271097;
   fWeightMatrix1to2[10][7] = 0.360245042972521;
   fWeightMatrix1to2[11][7] = -2.01852557161215;
   fWeightMatrix1to2[12][7] = -1.2625672206839;
   fWeightMatrix1to2[0][8] = -2.40715184358307;
   fWeightMatrix1to2[1][8] = -0.549736007648937;
   fWeightMatrix1to2[2][8] = 2.06284473602058;
   fWeightMatrix1to2[3][8] = -0.71691666230271;
   fWeightMatrix1to2[4][8] = -0.0245045417714749;
   fWeightMatrix1to2[5][8] = -0.892846648669127;
   fWeightMatrix1to2[6][8] = -1.02461529212336;
   fWeightMatrix1to2[7][8] = -1.43029145539455;
   fWeightMatrix1to2[8][8] = -1.64320344322409;
   fWeightMatrix1to2[9][8] = -0.701140161062015;
   fWeightMatrix1to2[10][8] = 0.736926421301833;
   fWeightMatrix1to2[11][8] = -1.48391765589959;
   fWeightMatrix1to2[12][8] = -0.967014865549815;
   fWeightMatrix1to2[0][9] = 1.82634652788019;
   fWeightMatrix1to2[1][9] = 0.125627479318869;
   fWeightMatrix1to2[2][9] = -0.586082784536779;
   fWeightMatrix1to2[3][9] = 2.06223892657996;
   fWeightMatrix1to2[4][9] = -3.07349928413736;
   fWeightMatrix1to2[5][9] = 1.31683647036479;
   fWeightMatrix1to2[6][9] = 1.17091358072084;
   fWeightMatrix1to2[7][9] = -1.20037847723563;
   fWeightMatrix1to2[8][9] = -0.699433095877084;
   fWeightMatrix1to2[9][9] = 0.0479187932101329;
   fWeightMatrix1to2[10][9] = -1.05077998890172;
   fWeightMatrix1to2[11][9] = 0.64050920929433;
   fWeightMatrix1to2[12][9] = 1.686582356819;
   fWeightMatrix1to2[0][10] = 1.45305201716299;
   fWeightMatrix1to2[1][10] = 1.83978650125775;
   fWeightMatrix1to2[2][10] = -1.27792835896419;
   fWeightMatrix1to2[3][10] = 0.900622754488977;
   fWeightMatrix1to2[4][10] = -2.10550914473093;
   fWeightMatrix1to2[5][10] = 0.674055134656601;
   fWeightMatrix1to2[6][10] = -1.87923793282483;
   fWeightMatrix1to2[7][10] = -1.68836304969397;
   fWeightMatrix1to2[8][10] = 0.0651642854855761;
   fWeightMatrix1to2[9][10] = 1.08809514680706;
   fWeightMatrix1to2[10][10] = 0.622256183899208;
   fWeightMatrix1to2[11][10] = 1.05284998892794;
   fWeightMatrix1to2[12][10] = 0.533138092866211;
   fWeightMatrix1to2[0][11] = -0.0441247262684711;
   fWeightMatrix1to2[1][11] = -0.50033909567113;
   fWeightMatrix1to2[2][11] = 0.264804317999347;
   fWeightMatrix1to2[3][11] = 1.73370824294021;
   fWeightMatrix1to2[4][11] = -1.70334060011255;
   fWeightMatrix1to2[5][11] = 0.38351776333398;
   fWeightMatrix1to2[6][11] = -1.57218409694693;
   fWeightMatrix1to2[7][11] = -0.31734882962239;
   fWeightMatrix1to2[8][11] = 0.144722103448709;
   fWeightMatrix1to2[9][11] = 0.130069168672741;
   fWeightMatrix1to2[10][11] = -1.01450827958615;
   fWeightMatrix1to2[11][11] = 0.909321129969576;
   fWeightMatrix1to2[12][11] = 1.90469841196061;
   fWeightMatrix1to2[0][12] = 0.857444829283912;
   fWeightMatrix1to2[1][12] = -0.396642517393579;
   fWeightMatrix1to2[2][12] = -1.1166091169189;
   fWeightMatrix1to2[3][12] = -1.63894346444168;
   fWeightMatrix1to2[4][12] = -2.71217254420772;
   fWeightMatrix1to2[5][12] = 1.09153310888598;
   fWeightMatrix1to2[6][12] = -0.630693692233776;
   fWeightMatrix1to2[7][12] = -1.11345386910555;
   fWeightMatrix1to2[8][12] = 0.738017823825593;
   fWeightMatrix1to2[9][12] = -1.9623379326828;
   fWeightMatrix1to2[10][12] = -0.897413835770835;
   fWeightMatrix1to2[11][12] = -1.76103764307456;
   fWeightMatrix1to2[12][12] = 0.750792730503665;
   fWeightMatrix1to2[0][13] = -1.53214450564991;
   fWeightMatrix1to2[1][13] = -2.02477241489769;
   fWeightMatrix1to2[2][13] = -0.669484936579336;
   fWeightMatrix1to2[3][13] = -0.755540021703302;
   fWeightMatrix1to2[4][13] = -1.41241019291724;
   fWeightMatrix1to2[5][13] = 1.14891692488363;
   fWeightMatrix1to2[6][13] = -1.26489141971591;
   fWeightMatrix1to2[7][13] = -1.39749433713848;
   fWeightMatrix1to2[8][13] = 1.63527463850238;
   fWeightMatrix1to2[9][13] = 0.686659794636984;
   fWeightMatrix1to2[10][13] = 0.474195322562169;
   fWeightMatrix1to2[11][13] = 0.139431959098502;
   fWeightMatrix1to2[12][13] = 1.10635479114898;
   fWeightMatrix1to2[0][14] = 1.89790908963658;
   fWeightMatrix1to2[1][14] = 0.749164329987583;
   fWeightMatrix1to2[2][14] = -0.852956559269006;
   fWeightMatrix1to2[3][14] = -0.810523138681181;
   fWeightMatrix1to2[4][14] = -1.95453333909596;
   fWeightMatrix1to2[5][14] = 0.98122452755117;
   fWeightMatrix1to2[6][14] = 0.735290421922599;
   fWeightMatrix1to2[7][14] = 0.232094301077333;
   fWeightMatrix1to2[8][14] = 1.22633558564761;
   fWeightMatrix1to2[9][14] = 0.796762624534697;
   fWeightMatrix1to2[10][14] = 1.88684024064558;
   fWeightMatrix1to2[11][14] = -1.35020509576236;
   fWeightMatrix1to2[12][14] = 1.98710048150992;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.20741415746413;
   fWeightMatrix2to3[0][1] = -1.4135511798412;
   fWeightMatrix2to3[0][2] = -0.50279895739205;
   fWeightMatrix2to3[0][3] = 0.0309169141571966;
   fWeightMatrix2to3[0][4] = 1.09293955636837;
   fWeightMatrix2to3[0][5] = 0.014409838777098;
   fWeightMatrix2to3[0][6] = 0.0171746011291325;
   fWeightMatrix2to3[0][7] = 0.0181098623390732;
   fWeightMatrix2to3[0][8] = -0.412317920735705;
   fWeightMatrix2to3[0][9] = -0.00157369771990525;
   fWeightMatrix2to3[0][10] = 1.40315018941487;
   fWeightMatrix2to3[0][11] = -0.401493843497393;
   fWeightMatrix2to3[0][12] = -0.531246030278948;
   fWeightMatrix2to3[0][13] = 2.12686556069036;
}

inline double ReadMLP1_5_EC_10x10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1_5_EC_10x10::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1_5_EC_10x10::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1_5_EC_10x10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
