// Class: ReadMLP1_EC_10x10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Tue Sep 22 14:38:27 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 4015


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,9.13947868347]
ClusterParameters.end         ClusterParameters.end             'F'    [1.9474439621,30.5900630951]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,21.2053031921]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.965895533562]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0513214655221,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.415317445993,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.00649774027988,0.999998688698]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999996960163]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.705317378044,29.202583313]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.0792230814695,0.938266277313]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [7,74]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [54.6154174805,488213.8125]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-1.97964119911,20.0559864044]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1_EC_10x10 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1_EC_10x10( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1_EC_10x10" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 9.13947868347168;
      fVmin[1] = 1.94744396209717;
      fVmax[1] = 30.5900630950928;
      fVmin[2] = 0;
      fVmax[2] = 21.2053031921387;
      fVmin[3] = 0;
      fVmax[3] = 0.965895533561707;
      fVmin[4] = 0.0513214655220509;
      fVmax[4] = 1;
      fVmin[5] = 0.415317445993423;
      fVmax[5] = 1;
      fVmin[6] = 0.00649774027988315;
      fVmax[6] = 0.999998688697815;
      fVmin[7] = 0;
      fVmax[7] = 0.999996960163116;
      fVmin[8] = 0.705317378044128;
      fVmax[8] = 29.2025833129883;
      fVmin[9] = 0.0792230814695358;
      fVmax[9] = 0.938266277313232;
      fVmin[10] = 7;
      fVmax[10] = 74;
      fVmin[11] = 54.6154174804688;
      fVmax[11] = 488213.8125;
      fVmin[12] = -1.97964119911194;
      fVmax[12] = 20.0559864044189;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1_EC_10x10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1_EC_10x10::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.941601216233476;
   fWeightMatrix0to1[1][0] = 1.84907759994957;
   fWeightMatrix0to1[2][0] = 0.143648709868464;
   fWeightMatrix0to1[3][0] = 2.0845532811991;
   fWeightMatrix0to1[4][0] = -0.92825800754406;
   fWeightMatrix0to1[5][0] = -1.91785466867745;
   fWeightMatrix0to1[6][0] = -0.49983411032866;
   fWeightMatrix0to1[7][0] = 2.54394827119276;
   fWeightMatrix0to1[8][0] = -1.30528637611836;
   fWeightMatrix0to1[9][0] = -1.05298439536915;
   fWeightMatrix0to1[10][0] = -1.54227192414489;
   fWeightMatrix0to1[11][0] = -0.414677801271766;
   fWeightMatrix0to1[12][0] = -0.354396252214316;
   fWeightMatrix0to1[13][0] = -0.533587368641484;
   fWeightMatrix0to1[0][1] = -1.08676914283348;
   fWeightMatrix0to1[1][1] = 0.694627356502104;
   fWeightMatrix0to1[2][1] = -0.129798439399273;
   fWeightMatrix0to1[3][1] = 1.80363173934964;
   fWeightMatrix0to1[4][1] = -0.0915341230821973;
   fWeightMatrix0to1[5][1] = 1.33453787019697;
   fWeightMatrix0to1[6][1] = -0.367425586177516;
   fWeightMatrix0to1[7][1] = -0.247285839411638;
   fWeightMatrix0to1[8][1] = 0.332418316991956;
   fWeightMatrix0to1[9][1] = 0.341131325113319;
   fWeightMatrix0to1[10][1] = -1.23562688977613;
   fWeightMatrix0to1[11][1] = -0.367927504690699;
   fWeightMatrix0to1[12][1] = 0.623381311119221;
   fWeightMatrix0to1[13][1] = -1.17014839296374;
   fWeightMatrix0to1[0][2] = -2.05767765102848;
   fWeightMatrix0to1[1][2] = 0.100617454526393;
   fWeightMatrix0to1[2][2] = 0.622098086565706;
   fWeightMatrix0to1[3][2] = 1.54159011430021;
   fWeightMatrix0to1[4][2] = -0.189732250636211;
   fWeightMatrix0to1[5][2] = -0.25874897926762;
   fWeightMatrix0to1[6][2] = 0.299217076953161;
   fWeightMatrix0to1[7][2] = 0.180607280487036;
   fWeightMatrix0to1[8][2] = -1.42975101122401;
   fWeightMatrix0to1[9][2] = 2.41043329563945;
   fWeightMatrix0to1[10][2] = -1.52771033598211;
   fWeightMatrix0to1[11][2] = 1.09972764198876;
   fWeightMatrix0to1[12][2] = 1.28870295206596;
   fWeightMatrix0to1[13][2] = 0.833726508827729;
   fWeightMatrix0to1[0][3] = 1.42122586724246;
   fWeightMatrix0to1[1][3] = 1.39130306322763;
   fWeightMatrix0to1[2][3] = -0.397008098404532;
   fWeightMatrix0to1[3][3] = -1.77946641480433;
   fWeightMatrix0to1[4][3] = -0.122026655775028;
   fWeightMatrix0to1[5][3] = 0.400143499152554;
   fWeightMatrix0to1[6][3] = 1.76752592387619;
   fWeightMatrix0to1[7][3] = 1.65756672858123;
   fWeightMatrix0to1[8][3] = 1.59084794959908;
   fWeightMatrix0to1[9][3] = 0.905964911760666;
   fWeightMatrix0to1[10][3] = -0.915251708944239;
   fWeightMatrix0to1[11][3] = 1.21793526449431;
   fWeightMatrix0to1[12][3] = -2.66964383350131;
   fWeightMatrix0to1[13][3] = -1.01569601214443;
   fWeightMatrix0to1[0][4] = -0.724872450846953;
   fWeightMatrix0to1[1][4] = -1.65229642635185;
   fWeightMatrix0to1[2][4] = 2.00830055173588;
   fWeightMatrix0to1[3][4] = 0.382215040825468;
   fWeightMatrix0to1[4][4] = -2.42313681365307;
   fWeightMatrix0to1[5][4] = 0.137948231173655;
   fWeightMatrix0to1[6][4] = -0.157047223605402;
   fWeightMatrix0to1[7][4] = 0.557237646388352;
   fWeightMatrix0to1[8][4] = 1.79368759380057;
   fWeightMatrix0to1[9][4] = -0.453450542601473;
   fWeightMatrix0to1[10][4] = -0.0255991566174916;
   fWeightMatrix0to1[11][4] = -0.95440758345377;
   fWeightMatrix0to1[12][4] = -2.04502496020012;
   fWeightMatrix0to1[13][4] = -0.672639499489813;
   fWeightMatrix0to1[0][5] = -0.211607016812636;
   fWeightMatrix0to1[1][5] = -1.47257984752876;
   fWeightMatrix0to1[2][5] = 1.14473753739495;
   fWeightMatrix0to1[3][5] = 1.0154124034539;
   fWeightMatrix0to1[4][5] = 1.81344894895316;
   fWeightMatrix0to1[5][5] = -0.487810952855091;
   fWeightMatrix0to1[6][5] = -1.89656117650366;
   fWeightMatrix0to1[7][5] = -1.80706144606721;
   fWeightMatrix0to1[8][5] = 1.00279593385214;
   fWeightMatrix0to1[9][5] = 0.280715030365493;
   fWeightMatrix0to1[10][5] = 2.03102553174008;
   fWeightMatrix0to1[11][5] = 0.942786264972746;
   fWeightMatrix0to1[12][5] = 0.546559025388838;
   fWeightMatrix0to1[13][5] = -0.727997652508285;
   fWeightMatrix0to1[0][6] = -0.414455234731551;
   fWeightMatrix0to1[1][6] = -0.18436895090907;
   fWeightMatrix0to1[2][6] = 1.0647273476947;
   fWeightMatrix0to1[3][6] = -1.36248400131682;
   fWeightMatrix0to1[4][6] = -1.52923883227631;
   fWeightMatrix0to1[5][6] = -1.76641551152407;
   fWeightMatrix0to1[6][6] = -0.322197247674059;
   fWeightMatrix0to1[7][6] = 0.221029151919961;
   fWeightMatrix0to1[8][6] = 1.65585345090551;
   fWeightMatrix0to1[9][6] = -2.13877371569249;
   fWeightMatrix0to1[10][6] = -1.36987734661902;
   fWeightMatrix0to1[11][6] = 1.44868137708529;
   fWeightMatrix0to1[12][6] = -2.29247561435262;
   fWeightMatrix0to1[13][6] = -1.5735152806942;
   fWeightMatrix0to1[0][7] = -0.681527496686829;
   fWeightMatrix0to1[1][7] = 0.251869437536176;
   fWeightMatrix0to1[2][7] = -1.70063524894069;
   fWeightMatrix0to1[3][7] = -1.24125197871538;
   fWeightMatrix0to1[4][7] = 0.271504816516302;
   fWeightMatrix0to1[5][7] = 1.17206536412738;
   fWeightMatrix0to1[6][7] = -1.08767350776561;
   fWeightMatrix0to1[7][7] = 0.32213320084578;
   fWeightMatrix0to1[8][7] = 0.037318737542067;
   fWeightMatrix0to1[9][7] = -0.498718780202318;
   fWeightMatrix0to1[10][7] = -0.0734178545007765;
   fWeightMatrix0to1[11][7] = 0.460229369956018;
   fWeightMatrix0to1[12][7] = -1.5236004829997;
   fWeightMatrix0to1[13][7] = 0.408491783288106;
   fWeightMatrix0to1[0][8] = -0.301168439138669;
   fWeightMatrix0to1[1][8] = 0.467655419135572;
   fWeightMatrix0to1[2][8] = -2.00101466762961;
   fWeightMatrix0to1[3][8] = 1.90131249502778;
   fWeightMatrix0to1[4][8] = 0.581723682616952;
   fWeightMatrix0to1[5][8] = -0.662705185555602;
   fWeightMatrix0to1[6][8] = 0.635745795712079;
   fWeightMatrix0to1[7][8] = -0.906301387483458;
   fWeightMatrix0to1[8][8] = -1.93036258229707;
   fWeightMatrix0to1[9][8] = 1.00229237046057;
   fWeightMatrix0to1[10][8] = -0.24312727714203;
   fWeightMatrix0to1[11][8] = 1.568131728663;
   fWeightMatrix0to1[12][8] = 1.95062237933672;
   fWeightMatrix0to1[13][8] = -0.115701482035613;
   fWeightMatrix0to1[0][9] = -0.503369157924899;
   fWeightMatrix0to1[1][9] = 0.163894992477185;
   fWeightMatrix0to1[2][9] = -2.22821492521989;
   fWeightMatrix0to1[3][9] = 1.13514715395839;
   fWeightMatrix0to1[4][9] = -0.209802079357596;
   fWeightMatrix0to1[5][9] = -1.43840975512846;
   fWeightMatrix0to1[6][9] = 0.642228435351471;
   fWeightMatrix0to1[7][9] = -1.09457843135708;
   fWeightMatrix0to1[8][9] = -0.160029257415861;
   fWeightMatrix0to1[9][9] = 0.130342619002454;
   fWeightMatrix0to1[10][9] = 1.84822342606904;
   fWeightMatrix0to1[11][9] = -1.90796234280609;
   fWeightMatrix0to1[12][9] = -1.25283399152403;
   fWeightMatrix0to1[13][9] = 1.46305011792793;
   fWeightMatrix0to1[0][10] = 2.61715361247907;
   fWeightMatrix0to1[1][10] = 0.206977529772196;
   fWeightMatrix0to1[2][10] = -1.67171442836969;
   fWeightMatrix0to1[3][10] = -0.415486085865324;
   fWeightMatrix0to1[4][10] = -2.18996312897371;
   fWeightMatrix0to1[5][10] = 1.58281145827531;
   fWeightMatrix0to1[6][10] = 1.10120707491128;
   fWeightMatrix0to1[7][10] = -0.450230514335644;
   fWeightMatrix0to1[8][10] = -0.538013583107688;
   fWeightMatrix0to1[9][10] = -3.02395615840796;
   fWeightMatrix0to1[10][10] = -1.31070344082076;
   fWeightMatrix0to1[11][10] = 0.226580526660077;
   fWeightMatrix0to1[12][10] = 0.425314213713706;
   fWeightMatrix0to1[13][10] = -0.684664251429529;
   fWeightMatrix0to1[0][11] = -0.289470726493836;
   fWeightMatrix0to1[1][11] = 0.440819829246321;
   fWeightMatrix0to1[2][11] = 0.544977262762764;
   fWeightMatrix0to1[3][11] = 0.487321645521017;
   fWeightMatrix0to1[4][11] = 0.665534974525744;
   fWeightMatrix0to1[5][11] = -1.49547935348544;
   fWeightMatrix0to1[6][11] = 1.51333460018812;
   fWeightMatrix0to1[7][11] = 0.825191640759039;
   fWeightMatrix0to1[8][11] = 0.256744828524091;
   fWeightMatrix0to1[9][11] = 0.350790041082517;
   fWeightMatrix0to1[10][11] = 1.59910448901625;
   fWeightMatrix0to1[11][11] = -0.878480777177009;
   fWeightMatrix0to1[12][11] = -1.5130168853768;
   fWeightMatrix0to1[13][11] = 0.824512298783379;
   fWeightMatrix0to1[0][12] = -0.928323353264253;
   fWeightMatrix0to1[1][12] = -0.4962302964877;
   fWeightMatrix0to1[2][12] = 1.7647227023262;
   fWeightMatrix0to1[3][12] = 0.769867695087772;
   fWeightMatrix0to1[4][12] = -0.777687201615104;
   fWeightMatrix0to1[5][12] = 1.54756430687184;
   fWeightMatrix0to1[6][12] = 1.8873685005691;
   fWeightMatrix0to1[7][12] = -1.62577150314661;
   fWeightMatrix0to1[8][12] = 0.629144065678448;
   fWeightMatrix0to1[9][12] = 0.490171832928029;
   fWeightMatrix0to1[10][12] = 0.155865022419363;
   fWeightMatrix0to1[11][12] = -1.79158171494943;
   fWeightMatrix0to1[12][12] = -1.99804202471373;
   fWeightMatrix0to1[13][12] = 1.11296026364722;
   fWeightMatrix0to1[0][13] = 2.16451025898132;
   fWeightMatrix0to1[1][13] = -1.94668812979029;
   fWeightMatrix0to1[2][13] = 0.0461960985381604;
   fWeightMatrix0to1[3][13] = -0.636046194629875;
   fWeightMatrix0to1[4][13] = 0.978824724364465;
   fWeightMatrix0to1[5][13] = 2.03141156137906;
   fWeightMatrix0to1[6][13] = -0.684966033761358;
   fWeightMatrix0to1[7][13] = -0.899423185334796;
   fWeightMatrix0to1[8][13] = -1.0946766881818;
   fWeightMatrix0to1[9][13] = 1.52990607493961;
   fWeightMatrix0to1[10][13] = 1.5629611659244;
   fWeightMatrix0to1[11][13] = 1.35715138092884;
   fWeightMatrix0to1[12][13] = 0.903316978624338;
   fWeightMatrix0to1[13][13] = -0.643597860193727;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.86627851680262;
   fWeightMatrix1to2[1][0] = 1.15497701232399;
   fWeightMatrix1to2[2][0] = 0.972009260097147;
   fWeightMatrix1to2[3][0] = -1.41781514573613;
   fWeightMatrix1to2[4][0] = 1.27725416128306;
   fWeightMatrix1to2[5][0] = 0.203939641190315;
   fWeightMatrix1to2[6][0] = -0.0222771344632029;
   fWeightMatrix1to2[7][0] = -2.08710557284315;
   fWeightMatrix1to2[8][0] = 0.394150185726651;
   fWeightMatrix1to2[9][0] = 0.525529446100777;
   fWeightMatrix1to2[10][0] = -0.0627486034375313;
   fWeightMatrix1to2[11][0] = 0.530491209327161;
   fWeightMatrix1to2[12][0] = 1.61306327315594;
   fWeightMatrix1to2[0][1] = 0.952256550850498;
   fWeightMatrix1to2[1][1] = -0.00291415205544802;
   fWeightMatrix1to2[2][1] = -0.149872523151603;
   fWeightMatrix1to2[3][1] = -1.68751071932413;
   fWeightMatrix1to2[4][1] = -0.306883056032315;
   fWeightMatrix1to2[5][1] = 1.71408164375968;
   fWeightMatrix1to2[6][1] = 1.75586159503102;
   fWeightMatrix1to2[7][1] = 0.607460688178152;
   fWeightMatrix1to2[8][1] = 0.12137805053446;
   fWeightMatrix1to2[9][1] = 2.1441066480631;
   fWeightMatrix1to2[10][1] = -2.07211734301415;
   fWeightMatrix1to2[11][1] = -1.75942305718711;
   fWeightMatrix1to2[12][1] = -0.173478798656868;
   fWeightMatrix1to2[0][2] = -1.38313956740306;
   fWeightMatrix1to2[1][2] = 1.19293641810562;
   fWeightMatrix1to2[2][2] = 1.82844000986276;
   fWeightMatrix1to2[3][2] = -1.44810066773581;
   fWeightMatrix1to2[4][2] = 2.19292954462613;
   fWeightMatrix1to2[5][2] = -0.0982006077175703;
   fWeightMatrix1to2[6][2] = -1.60404059305;
   fWeightMatrix1to2[7][2] = -0.907328564867123;
   fWeightMatrix1to2[8][2] = 1.12455755961699;
   fWeightMatrix1to2[9][2] = 0.613285860559819;
   fWeightMatrix1to2[10][2] = 0.815734488538188;
   fWeightMatrix1to2[11][2] = -0.709975357772764;
   fWeightMatrix1to2[12][2] = 1.69501545024218;
   fWeightMatrix1to2[0][3] = -1.74233507238027;
   fWeightMatrix1to2[1][3] = 0.806376241290697;
   fWeightMatrix1to2[2][3] = -0.0641081317385574;
   fWeightMatrix1to2[3][3] = -1.62666656074141;
   fWeightMatrix1to2[4][3] = -1.36830592830132;
   fWeightMatrix1to2[5][3] = -1.8719904745063;
   fWeightMatrix1to2[6][3] = -0.253934346139742;
   fWeightMatrix1to2[7][3] = -1.96895111573183;
   fWeightMatrix1to2[8][3] = -1.15224226966355;
   fWeightMatrix1to2[9][3] = -1.8276425063575;
   fWeightMatrix1to2[10][3] = 0.183897492553803;
   fWeightMatrix1to2[11][3] = -0.93905955658285;
   fWeightMatrix1to2[12][3] = -1.70031762279789;
   fWeightMatrix1to2[0][4] = 1.64880839559106;
   fWeightMatrix1to2[1][4] = -0.936118107283814;
   fWeightMatrix1to2[2][4] = -0.044947548367413;
   fWeightMatrix1to2[3][4] = -0.776200357322533;
   fWeightMatrix1to2[4][4] = -1.99684575793781;
   fWeightMatrix1to2[5][4] = 1.95369204131239;
   fWeightMatrix1to2[6][4] = 1.07445046093076;
   fWeightMatrix1to2[7][4] = -0.726003008925602;
   fWeightMatrix1to2[8][4] = -1.28774175128798;
   fWeightMatrix1to2[9][4] = -1.49356338092342;
   fWeightMatrix1to2[10][4] = -0.591552100606773;
   fWeightMatrix1to2[11][4] = -1.44776099609057;
   fWeightMatrix1to2[12][4] = 0.302079451974553;
   fWeightMatrix1to2[0][5] = 0.149562669269106;
   fWeightMatrix1to2[1][5] = 1.74421497686643;
   fWeightMatrix1to2[2][5] = 0.0903639247556698;
   fWeightMatrix1to2[3][5] = 0.384538924366652;
   fWeightMatrix1to2[4][5] = 1.00934351956958;
   fWeightMatrix1to2[5][5] = -1.80551340117392;
   fWeightMatrix1to2[6][5] = 0.894401996487896;
   fWeightMatrix1to2[7][5] = 1.36042568607461;
   fWeightMatrix1to2[8][5] = -0.293255795088804;
   fWeightMatrix1to2[9][5] = -1.04218380633349;
   fWeightMatrix1to2[10][5] = 0.781486451410207;
   fWeightMatrix1to2[11][5] = 0.622340530810502;
   fWeightMatrix1to2[12][5] = 0.426016160987195;
   fWeightMatrix1to2[0][6] = -0.441944446826862;
   fWeightMatrix1to2[1][6] = -0.814433172989555;
   fWeightMatrix1to2[2][6] = 1.40734626563117;
   fWeightMatrix1to2[3][6] = 1.23118210896495;
   fWeightMatrix1to2[4][6] = 1.61633318723998;
   fWeightMatrix1to2[5][6] = -0.288932335643176;
   fWeightMatrix1to2[6][6] = 0.709339922506515;
   fWeightMatrix1to2[7][6] = -0.434538198086316;
   fWeightMatrix1to2[8][6] = -1.5312806684632;
   fWeightMatrix1to2[9][6] = -0.282539432502834;
   fWeightMatrix1to2[10][6] = -1.90565804976788;
   fWeightMatrix1to2[11][6] = -1.8490038498467;
   fWeightMatrix1to2[12][6] = -1.57971961610397;
   fWeightMatrix1to2[0][7] = 1.25613239123312;
   fWeightMatrix1to2[1][7] = -1.59749897240218;
   fWeightMatrix1to2[2][7] = 1.55362957930492;
   fWeightMatrix1to2[3][7] = -1.34841158548639;
   fWeightMatrix1to2[4][7] = -0.083973575262939;
   fWeightMatrix1to2[5][7] = -1.15249330497313;
   fWeightMatrix1to2[6][7] = 0.667534629039039;
   fWeightMatrix1to2[7][7] = 0.610862230309104;
   fWeightMatrix1to2[8][7] = -2.61024779158421;
   fWeightMatrix1to2[9][7] = 0.296721213709758;
   fWeightMatrix1to2[10][7] = 0.236766246393202;
   fWeightMatrix1to2[11][7] = -2.06027830002338;
   fWeightMatrix1to2[12][7] = -1.40698724708669;
   fWeightMatrix1to2[0][8] = -1.80057768225845;
   fWeightMatrix1to2[1][8] = -0.642720279597872;
   fWeightMatrix1to2[2][8] = 1.87815208464912;
   fWeightMatrix1to2[3][8] = -0.810873882520007;
   fWeightMatrix1to2[4][8] = 0.113182580428813;
   fWeightMatrix1to2[5][8] = -0.858971015492336;
   fWeightMatrix1to2[6][8] = -1.0519709540733;
   fWeightMatrix1to2[7][8] = -1.39851840080931;
   fWeightMatrix1to2[8][8] = -1.21045247753866;
   fWeightMatrix1to2[9][8] = -0.570087187465014;
   fWeightMatrix1to2[10][8] = 0.625503468936364;
   fWeightMatrix1to2[11][8] = -1.44455375050106;
   fWeightMatrix1to2[12][8] = -1.24928621284062;
   fWeightMatrix1to2[0][9] = 1.83660180144655;
   fWeightMatrix1to2[1][9] = 0.356838220412439;
   fWeightMatrix1to2[2][9] = -0.68313311703314;
   fWeightMatrix1to2[3][9] = 1.98719219802028;
   fWeightMatrix1to2[4][9] = -3.0144445728994;
   fWeightMatrix1to2[5][9] = 1.36359540137285;
   fWeightMatrix1to2[6][9] = 1.00068182673655;
   fWeightMatrix1to2[7][9] = -1.13601187276722;
   fWeightMatrix1to2[8][9] = -1.39502129901126;
   fWeightMatrix1to2[9][9] = -0.151645156299769;
   fWeightMatrix1to2[10][9] = -1.02294763981195;
   fWeightMatrix1to2[11][9] = 0.735626472463538;
   fWeightMatrix1to2[12][9] = 1.86897389170416;
   fWeightMatrix1to2[0][10] = 1.44578113323744;
   fWeightMatrix1to2[1][10] = 1.60002405256099;
   fWeightMatrix1to2[2][10] = -1.37514467520582;
   fWeightMatrix1to2[3][10] = 0.885748689413502;
   fWeightMatrix1to2[4][10] = -2.18092547507634;
   fWeightMatrix1to2[5][10] = 0.607050848929184;
   fWeightMatrix1to2[6][10] = -2.01951502837045;
   fWeightMatrix1to2[7][10] = -1.72191011992647;
   fWeightMatrix1to2[8][10] = 0.362346135333153;
   fWeightMatrix1to2[9][10] = 0.987556728176009;
   fWeightMatrix1to2[10][10] = 0.830330452047521;
   fWeightMatrix1to2[11][10] = 1.55816111780198;
   fWeightMatrix1to2[12][10] = 0.447970522859051;
   fWeightMatrix1to2[0][11] = -0.0866474927032359;
   fWeightMatrix1to2[1][11] = -0.236204292312345;
   fWeightMatrix1to2[2][11] = 0.158495254607955;
   fWeightMatrix1to2[3][11] = 1.6748747699988;
   fWeightMatrix1to2[4][11] = -2.07248770236596;
   fWeightMatrix1to2[5][11] = 0.35498565488037;
   fWeightMatrix1to2[6][11] = -1.58644317863383;
   fWeightMatrix1to2[7][11] = -0.156978140685207;
   fWeightMatrix1to2[8][11] = 0.127568729889287;
   fWeightMatrix1to2[9][11] = 0.233354597649526;
   fWeightMatrix1to2[10][11] = -0.897847941842287;
   fWeightMatrix1to2[11][11] = 1.25653869799264;
   fWeightMatrix1to2[12][11] = 1.52639477815559;
   fWeightMatrix1to2[0][12] = 1.0522358070911;
   fWeightMatrix1to2[1][12] = -0.252171395870525;
   fWeightMatrix1to2[2][12] = -1.16096726029438;
   fWeightMatrix1to2[3][12] = -1.635263724442;
   fWeightMatrix1to2[4][12] = -3.14340817274058;
   fWeightMatrix1to2[5][12] = 1.11481873034362;
   fWeightMatrix1to2[6][12] = -0.572703315447069;
   fWeightMatrix1to2[7][12] = -1.19967257633811;
   fWeightMatrix1to2[8][12] = 1.24429229981359;
   fWeightMatrix1to2[9][12] = -2.27935217016354;
   fWeightMatrix1to2[10][12] = -0.771315059054882;
   fWeightMatrix1to2[11][12] = -1.71107127484096;
   fWeightMatrix1to2[12][12] = 0.89114873844485;
   fWeightMatrix1to2[0][13] = -1.44572656594471;
   fWeightMatrix1to2[1][13] = -2.07345883865931;
   fWeightMatrix1to2[2][13] = -0.561524870431682;
   fWeightMatrix1to2[3][13] = -0.715099959792454;
   fWeightMatrix1to2[4][13] = -1.06158495210532;
   fWeightMatrix1to2[5][13] = 1.22400682791898;
   fWeightMatrix1to2[6][13] = -1.30568203078967;
   fWeightMatrix1to2[7][13] = -1.4275390896585;
   fWeightMatrix1to2[8][13] = 1.66536208466822;
   fWeightMatrix1to2[9][13] = 0.624899860755463;
   fWeightMatrix1to2[10][13] = 0.311539868200914;
   fWeightMatrix1to2[11][13] = -0.347181615843111;
   fWeightMatrix1to2[12][13] = 1.30933613683589;
   fWeightMatrix1to2[0][14] = 1.81840136335637;
   fWeightMatrix1to2[1][14] = 1.01888666374302;
   fWeightMatrix1to2[2][14] = -0.929527068391188;
   fWeightMatrix1to2[3][14] = -0.958436131317102;
   fWeightMatrix1to2[4][14] = -2.37898374696851;
   fWeightMatrix1to2[5][14] = 0.913471878700588;
   fWeightMatrix1to2[6][14] = 0.496817684691102;
   fWeightMatrix1to2[7][14] = 0.242440674677446;
   fWeightMatrix1to2[8][14] = 1.1682874067528;
   fWeightMatrix1to2[9][14] = 0.776989940823808;
   fWeightMatrix1to2[10][14] = 2.01690562482649;
   fWeightMatrix1to2[11][14] = -0.873086420222;
   fWeightMatrix1to2[12][14] = 1.79148625299087;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.0728991592771833;
   fWeightMatrix2to3[0][1] = -1.51644301034441;
   fWeightMatrix2to3[0][2] = 0.207255275262103;
   fWeightMatrix2to3[0][3] = 0.019897620687664;
   fWeightMatrix2to3[0][4] = 1.00283992350116;
   fWeightMatrix2to3[0][5] = -0.00653830232680545;
   fWeightMatrix2to3[0][6] = -0.00332419926575528;
   fWeightMatrix2to3[0][7] = -0.0181234323880952;
   fWeightMatrix2to3[0][8] = 0.325042920910686;
   fWeightMatrix2to3[0][9] = -0.142930412691946;
   fWeightMatrix2to3[0][10] = 0.792355113046321;
   fWeightMatrix2to3[0][11] = -0.966034400287218;
   fWeightMatrix2to3[0][12] = -0.560877063813844;
   fWeightMatrix2to3[0][13] = 1.89922609361028;
}

inline double ReadMLP1_EC_10x10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1_EC_10x10::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1_EC_10x10::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1_EC_10x10::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
