// Class: ReadMLP2_25_EC_2x2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Tue Aug 11 15:28:24 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 3833


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,8.6678237915]
ClusterParameters.end         ClusterParameters.end             'F'    [2.28382730484,41.6208267212]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,22.9432506561]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.956362843513]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.134572803974,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.911372303963,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.00212071835995,0.999994933605]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.99998831749]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.899647772312,39.0703201294]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.140908256173,0.874496161938]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,104]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [153.614868164,920122.4375]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [0,20.9365119934]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP2_25_EC_2x2 : public IClassifierReader {

 public:

   // constructor
   ReadMLP2_25_EC_2x2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP2_25_EC_2x2" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 8.66782379150391;
      fVmin[1] = 2.28382730484009;
      fVmax[1] = 41.6208267211914;
      fVmin[2] = 0;
      fVmax[2] = 22.9432506561279;
      fVmin[3] = 0;
      fVmax[3] = 0.956362843513489;
      fVmin[4] = 0.134572803974152;
      fVmax[4] = 1;
      fVmin[5] = 0.911372303962708;
      fVmax[5] = 1;
      fVmin[6] = 0.0021207183599472;
      fVmax[6] = 0.999994933605194;
      fVmin[7] = 0;
      fVmax[7] = 0.999988317489624;
      fVmin[8] = 0.899647772312164;
      fVmax[8] = 39.0703201293945;
      fVmin[9] = 0.140908256173134;
      fVmax[9] = 0.874496161937714;
      fVmin[10] = 5;
      fVmax[10] = 104;
      fVmin[11] = 153.614868164062;
      fVmax[11] = 920122.4375;
      fVmin[12] = 0;
      fVmax[12] = 20.9365119934082;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP2_25_EC_2x2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP2_25_EC_2x2::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.333728864992524;
   fWeightMatrix0to1[1][0] = 1.98233291328622;
   fWeightMatrix0to1[2][0] = 0.658173044919549;
   fWeightMatrix0to1[3][0] = 0.944046728966437;
   fWeightMatrix0to1[4][0] = -1.15277463649065;
   fWeightMatrix0to1[5][0] = -1.40969851336427;
   fWeightMatrix0to1[6][0] = -0.640558378282171;
   fWeightMatrix0to1[7][0] = 1.34399722798251;
   fWeightMatrix0to1[8][0] = -1.76845960407905;
   fWeightMatrix0to1[9][0] = -0.382181709860446;
   fWeightMatrix0to1[10][0] = -1.47955410441281;
   fWeightMatrix0to1[11][0] = -0.130957355284215;
   fWeightMatrix0to1[12][0] = -0.94806998659155;
   fWeightMatrix0to1[13][0] = -0.124209024170718;
   fWeightMatrix0to1[0][1] = -0.665383773935726;
   fWeightMatrix0to1[1][1] = 0.679289173350045;
   fWeightMatrix0to1[2][1] = -0.553493469969353;
   fWeightMatrix0to1[3][1] = 1.49432314535714;
   fWeightMatrix0to1[4][1] = 0.520011744226391;
   fWeightMatrix0to1[5][1] = 1.32555182756026;
   fWeightMatrix0to1[6][1] = -0.315383371338951;
   fWeightMatrix0to1[7][1] = -1.05092359120485;
   fWeightMatrix0to1[8][1] = 0.429064007146648;
   fWeightMatrix0to1[9][1] = 0.381729515603794;
   fWeightMatrix0to1[10][1] = -1.20937600162864;
   fWeightMatrix0to1[11][1] = -0.40642564263212;
   fWeightMatrix0to1[12][1] = 1.45389578255376;
   fWeightMatrix0to1[13][1] = -1.24334183130258;
   fWeightMatrix0to1[0][2] = -1.76928643762911;
   fWeightMatrix0to1[1][2] = 0.139290208199182;
   fWeightMatrix0to1[2][2] = 0.729932001937884;
   fWeightMatrix0to1[3][2] = 1.36624481895117;
   fWeightMatrix0to1[4][2] = 0.0757379418655397;
   fWeightMatrix0to1[5][2] = -0.0941677974183882;
   fWeightMatrix0to1[6][2] = 0.200982914452132;
   fWeightMatrix0to1[7][2] = -0.723359897336529;
   fWeightMatrix0to1[8][2] = -1.56064280638804;
   fWeightMatrix0to1[9][2] = 1.8485657719592;
   fWeightMatrix0to1[10][2] = -1.1334774664565;
   fWeightMatrix0to1[11][2] = 1.27318483947001;
   fWeightMatrix0to1[12][2] = 1.56851372701585;
   fWeightMatrix0to1[13][2] = 0.849286938134389;
   fWeightMatrix0to1[0][3] = 2.24872895350282;
   fWeightMatrix0to1[1][3] = 1.2084217777847;
   fWeightMatrix0to1[2][3] = -0.861768503346136;
   fWeightMatrix0to1[3][3] = -1.82600611764927;
   fWeightMatrix0to1[4][3] = -0.0607103864426478;
   fWeightMatrix0to1[5][3] = -0.249729928111101;
   fWeightMatrix0to1[6][3] = 1.65954690661881;
   fWeightMatrix0to1[7][3] = 2.21462825703538;
   fWeightMatrix0to1[8][3] = 1.08048035211386;
   fWeightMatrix0to1[9][3] = -0.273252532521791;
   fWeightMatrix0to1[10][3] = -1.51309944402051;
   fWeightMatrix0to1[11][3] = 0.847583978290639;
   fWeightMatrix0to1[12][3] = -1.68588524941229;
   fWeightMatrix0to1[13][3] = -0.695277716086566;
   fWeightMatrix0to1[0][4] = -1.43624289013102;
   fWeightMatrix0to1[1][4] = -1.76461352679571;
   fWeightMatrix0to1[2][4] = 1.82047090609012;
   fWeightMatrix0to1[3][4] = 0.73834539087875;
   fWeightMatrix0to1[4][4] = -1.6751628328286;
   fWeightMatrix0to1[5][4] = 0.360135204765651;
   fWeightMatrix0to1[6][4] = -0.335552103373044;
   fWeightMatrix0to1[7][4] = 1.05858219998433;
   fWeightMatrix0to1[8][4] = 1.74770377282459;
   fWeightMatrix0to1[9][4] = -0.587932216584906;
   fWeightMatrix0to1[10][4] = 0.441615022830257;
   fWeightMatrix0to1[11][4] = -1.28886710807721;
   fWeightMatrix0to1[12][4] = -0.0608082006939166;
   fWeightMatrix0to1[13][4] = -0.824772392521376;
   fWeightMatrix0to1[0][5] = -0.731993094167604;
   fWeightMatrix0to1[1][5] = -1.43903381139705;
   fWeightMatrix0to1[2][5] = 1.21234966196712;
   fWeightMatrix0to1[3][5] = 0.919238749475789;
   fWeightMatrix0to1[4][5] = 1.24061974311634;
   fWeightMatrix0to1[5][5] = -0.103912347372804;
   fWeightMatrix0to1[6][5] = -1.97788530267295;
   fWeightMatrix0to1[7][5] = -1.15367852895075;
   fWeightMatrix0to1[8][5] = 1.46239621028542;
   fWeightMatrix0to1[9][5] = 0.499848057205744;
   fWeightMatrix0to1[10][5] = 2.23326249009363;
   fWeightMatrix0to1[11][5] = 0.927816265517197;
   fWeightMatrix0to1[12][5] = -0.0968473236353804;
   fWeightMatrix0to1[13][5] = -0.487547109384963;
   fWeightMatrix0to1[0][6] = -1.40509202882281;
   fWeightMatrix0to1[1][6] = -0.208865088199048;
   fWeightMatrix0to1[2][6] = 1.6477787758707;
   fWeightMatrix0to1[3][6] = -0.764779354797412;
   fWeightMatrix0to1[4][6] = -1.42448566734655;
   fWeightMatrix0to1[5][6] = -1.41544203894555;
   fWeightMatrix0to1[6][6] = -0.351921947915339;
   fWeightMatrix0to1[7][6] = 0.277019959702133;
   fWeightMatrix0to1[8][6] = 1.96746888851285;
   fWeightMatrix0to1[9][6] = -2.79678217311712;
   fWeightMatrix0to1[10][6] = -0.553298859873472;
   fWeightMatrix0to1[11][6] = 1.43356734988332;
   fWeightMatrix0to1[12][6] = -1.11132306484876;
   fWeightMatrix0to1[13][6] = -1.6314695672986;
   fWeightMatrix0to1[0][7] = -2.03693314145001;
   fWeightMatrix0to1[1][7] = 0.092747424857797;
   fWeightMatrix0to1[2][7] = -1.31031972492286;
   fWeightMatrix0to1[3][7] = -1.12946844482385;
   fWeightMatrix0to1[4][7] = 0.100313858251539;
   fWeightMatrix0to1[5][7] = 1.82338297788873;
   fWeightMatrix0to1[6][7] = -1.15290800035208;
   fWeightMatrix0to1[7][7] = 1.81242886073497;
   fWeightMatrix0to1[8][7] = -0.565136880692707;
   fWeightMatrix0to1[9][7] = 0.0128022117250326;
   fWeightMatrix0to1[10][7] = -0.0164416398541419;
   fWeightMatrix0to1[11][7] = 0.299533589687026;
   fWeightMatrix0to1[12][7] = -1.4084568316256;
   fWeightMatrix0to1[13][7] = 0.41708575809976;
   fWeightMatrix0to1[0][8] = -0.164611972173801;
   fWeightMatrix0to1[1][8] = 0.456897232837513;
   fWeightMatrix0to1[2][8] = -1.4069456463934;
   fWeightMatrix0to1[3][8] = 2.40827162679998;
   fWeightMatrix0to1[4][8] = 1.37499905614104;
   fWeightMatrix0to1[5][8] = -0.615902180405964;
   fWeightMatrix0to1[6][8] = 0.728175445694268;
   fWeightMatrix0to1[7][8] = -1.52908524261893;
   fWeightMatrix0to1[8][8] = -1.477959138359;
   fWeightMatrix0to1[9][8] = 1.45898222507223;
   fWeightMatrix0to1[10][8] = -0.523082094858802;
   fWeightMatrix0to1[11][8] = 1.89596787259707;
   fWeightMatrix0to1[12][8] = 2.37528919202531;
   fWeightMatrix0to1[13][8] = -0.138659901415463;
   fWeightMatrix0to1[0][9] = -0.143202978922657;
   fWeightMatrix0to1[1][9] = 0.160473138551693;
   fWeightMatrix0to1[2][9] = -1.62364297760751;
   fWeightMatrix0to1[3][9] = 1.7418828767726;
   fWeightMatrix0to1[4][9] = 0.0772446240950822;
   fWeightMatrix0to1[5][9] = -1.57881351476954;
   fWeightMatrix0to1[6][9] = 0.684743406149509;
   fWeightMatrix0to1[7][9] = -0.584948499981817;
   fWeightMatrix0to1[8][9] = 0.0920183868930504;
   fWeightMatrix0to1[9][9] = -0.181222196180014;
   fWeightMatrix0to1[10][9] = 1.64525523211968;
   fWeightMatrix0to1[11][9] = -1.89509692692171;
   fWeightMatrix0to1[12][9] = 1.11380589121741;
   fWeightMatrix0to1[13][9] = 1.50436809130392;
   fWeightMatrix0to1[0][10] = 1.35494613505177;
   fWeightMatrix0to1[1][10] = 0.163976599916594;
   fWeightMatrix0to1[2][10] = -1.59008181851053;
   fWeightMatrix0to1[3][10] = -0.55179742280874;
   fWeightMatrix0to1[4][10] = -2.48393907269304;
   fWeightMatrix0to1[5][10] = 1.49896858036765;
   fWeightMatrix0to1[6][10] = 1.14456641169715;
   fWeightMatrix0to1[7][10] = -0.134202222464987;
   fWeightMatrix0to1[8][10] = -0.470630233613393;
   fWeightMatrix0to1[9][10] = -2.20915845830728;
   fWeightMatrix0to1[10][10] = -1.52198760668181;
   fWeightMatrix0to1[11][10] = 0.530491633310146;
   fWeightMatrix0to1[12][10] = 1.64911914264308;
   fWeightMatrix0to1[13][10] = -0.481677436748554;
   fWeightMatrix0to1[0][11] = -0.642468425059206;
   fWeightMatrix0to1[1][11] = 0.282051649132675;
   fWeightMatrix0to1[2][11] = 0.551420257428678;
   fWeightMatrix0to1[3][11] = 0.371269401694377;
   fWeightMatrix0to1[4][11] = 0.782559782454534;
   fWeightMatrix0to1[5][11] = -1.63782502397325;
   fWeightMatrix0to1[6][11] = 1.51117059944264;
   fWeightMatrix0to1[7][11] = 0.210829523451337;
   fWeightMatrix0to1[8][11] = 0.0716591776931678;
   fWeightMatrix0to1[9][11] = 0.41723970873626;
   fWeightMatrix0to1[10][11] = 0.713519769244253;
   fWeightMatrix0to1[11][11] = -0.793958824512392;
   fWeightMatrix0to1[12][11] = 0.199927362122889;
   fWeightMatrix0to1[13][11] = 1.10997932253044;
   fWeightMatrix0to1[0][12] = -0.881923661179321;
   fWeightMatrix0to1[1][12] = -0.57245928135667;
   fWeightMatrix0to1[2][12] = 1.60991355391345;
   fWeightMatrix0to1[3][12] = 0.897685089821911;
   fWeightMatrix0to1[4][12] = -0.433446004292311;
   fWeightMatrix0to1[5][12] = 1.44381705258704;
   fWeightMatrix0to1[6][12] = 1.80727986356818;
   fWeightMatrix0to1[7][12] = -2.16937838433883;
   fWeightMatrix0to1[8][12] = 0.442760645815651;
   fWeightMatrix0to1[9][12] = -0.531510057248024;
   fWeightMatrix0to1[10][12] = 0.407846429424125;
   fWeightMatrix0to1[11][12] = -1.7516298414462;
   fWeightMatrix0to1[12][12] = -1.29586050318288;
   fWeightMatrix0to1[13][12] = 1.08887859156542;
   fWeightMatrix0to1[0][13] = 1.228529752388;
   fWeightMatrix0to1[1][13] = -1.73420817488385;
   fWeightMatrix0to1[2][13] = 0.172656393951841;
   fWeightMatrix0to1[3][13] = -0.196586158754287;
   fWeightMatrix0to1[4][13] = 1.0701912836429;
   fWeightMatrix0to1[5][13] = 2.18768717994776;
   fWeightMatrix0to1[6][13] = -0.515431448107637;
   fWeightMatrix0to1[7][13] = -0.489784615116454;
   fWeightMatrix0to1[8][13] = -0.346971928640941;
   fWeightMatrix0to1[9][13] = 2.13921843149572;
   fWeightMatrix0to1[10][13] = 1.92029922311278;
   fWeightMatrix0to1[11][13] = 1.4153958045562;
   fWeightMatrix0to1[12][13] = 0.383863637716628;
   fWeightMatrix0to1[13][13] = -1.08141591642226;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.92575779599805;
   fWeightMatrix1to2[1][0] = 1.07882854828418;
   fWeightMatrix1to2[2][0] = 0.112034261239659;
   fWeightMatrix1to2[3][0] = -1.33306497881237;
   fWeightMatrix1to2[4][0] = -0.926231597875189;
   fWeightMatrix1to2[5][0] = 0.317936008668228;
   fWeightMatrix1to2[6][0] = 0.237036544828405;
   fWeightMatrix1to2[7][0] = -1.98186667676813;
   fWeightMatrix1to2[8][0] = 1.62775910794054;
   fWeightMatrix1to2[9][0] = 1.11496689794727;
   fWeightMatrix1to2[10][0] = -0.462702334178527;
   fWeightMatrix1to2[11][0] = -0.400337498463339;
   fWeightMatrix1to2[12][0] = 1.52966735635867;
   fWeightMatrix1to2[0][1] = 0.803653499428596;
   fWeightMatrix1to2[1][1] = 0.291983279322268;
   fWeightMatrix1to2[2][1] = 0.0794086294433971;
   fWeightMatrix1to2[3][1] = -2.11691673950854;
   fWeightMatrix1to2[4][1] = -0.800933924212132;
   fWeightMatrix1to2[5][1] = 1.619958814046;
   fWeightMatrix1to2[6][1] = 1.58329438601875;
   fWeightMatrix1to2[7][1] = 0.982620258795452;
   fWeightMatrix1to2[8][1] = 0.507793942539683;
   fWeightMatrix1to2[9][1] = 2.03102811794526;
   fWeightMatrix1to2[10][1] = -1.95892924382553;
   fWeightMatrix1to2[11][1] = -1.48518069422706;
   fWeightMatrix1to2[12][1] = -0.310352156364499;
   fWeightMatrix1to2[0][2] = -1.28281140557696;
   fWeightMatrix1to2[1][2] = 1.0200244018251;
   fWeightMatrix1to2[2][2] = 1.35694498137605;
   fWeightMatrix1to2[3][2] = -1.0551126484696;
   fWeightMatrix1to2[4][2] = 0.677408208387455;
   fWeightMatrix1to2[5][2] = -0.0113225616216597;
   fWeightMatrix1to2[6][2] = -1.78869117488757;
   fWeightMatrix1to2[7][2] = -1.06879640509094;
   fWeightMatrix1to2[8][2] = 0.692610766334076;
   fWeightMatrix1to2[9][2] = 0.292866753871877;
   fWeightMatrix1to2[10][2] = 1.03881817330632;
   fWeightMatrix1to2[11][2] = -1.03433877711198;
   fWeightMatrix1to2[12][2] = 1.77489243340957;
   fWeightMatrix1to2[0][3] = -1.11203265283101;
   fWeightMatrix1to2[1][3] = 0.589446236957741;
   fWeightMatrix1to2[2][3] = -0.144232467817879;
   fWeightMatrix1to2[3][3] = -1.57359324551056;
   fWeightMatrix1to2[4][3] = -1.07963673907206;
   fWeightMatrix1to2[5][3] = -1.84671459416087;
   fWeightMatrix1to2[6][3] = -0.361237370061727;
   fWeightMatrix1to2[7][3] = -1.62494394224761;
   fWeightMatrix1to2[8][3] = -1.8035059125239;
   fWeightMatrix1to2[9][3] = -1.83252315114893;
   fWeightMatrix1to2[10][3] = -0.0744767869865829;
   fWeightMatrix1to2[11][3] = -0.660211666216266;
   fWeightMatrix1to2[12][3] = -1.89947133443057;
   fWeightMatrix1to2[0][4] = 1.91708186152041;
   fWeightMatrix1to2[1][4] = -0.897249614781094;
   fWeightMatrix1to2[2][4] = 0.243009238418542;
   fWeightMatrix1to2[3][4] = -0.978125298479002;
   fWeightMatrix1to2[4][4] = -0.998054830429693;
   fWeightMatrix1to2[5][4] = 1.7775244388824;
   fWeightMatrix1to2[6][4] = 1.10357120875339;
   fWeightMatrix1to2[7][4] = -1.28977454795069;
   fWeightMatrix1to2[8][4] = -1.49060648199535;
   fWeightMatrix1to2[9][4] = -1.26134070753101;
   fWeightMatrix1to2[10][4] = -0.605025839934534;
   fWeightMatrix1to2[11][4] = -1.58562916130971;
   fWeightMatrix1to2[12][4] = 0.315091263623124;
   fWeightMatrix1to2[0][5] = 0.369585212048712;
   fWeightMatrix1to2[1][5] = 1.97078182710187;
   fWeightMatrix1to2[2][5] = 0.0929534852237234;
   fWeightMatrix1to2[3][5] = 0.445021378702914;
   fWeightMatrix1to2[4][5] = -0.236445670861915;
   fWeightMatrix1to2[5][5] = -1.9186781044577;
   fWeightMatrix1to2[6][5] = 1.04036818255779;
   fWeightMatrix1to2[7][5] = 0.896408399890802;
   fWeightMatrix1to2[8][5] = -0.757125743702955;
   fWeightMatrix1to2[9][5] = -0.960867685018438;
   fWeightMatrix1to2[10][5] = 0.683873344632387;
   fWeightMatrix1to2[11][5] = 1.1322803582757;
   fWeightMatrix1to2[12][5] = 0.758742574781336;
   fWeightMatrix1to2[0][6] = -0.615905456335052;
   fWeightMatrix1to2[1][6] = -0.496392110290813;
   fWeightMatrix1to2[2][6] = 1.56745066376201;
   fWeightMatrix1to2[3][6] = 0.846772941379359;
   fWeightMatrix1to2[4][6] = 1.00891207239012;
   fWeightMatrix1to2[5][6] = -0.349858236755438;
   fWeightMatrix1to2[6][6] = 1.12326542764444;
   fWeightMatrix1to2[7][6] = -0.163593381149043;
   fWeightMatrix1to2[8][6] = -1.08224624094273;
   fWeightMatrix1to2[9][6] = -0.494510828456851;
   fWeightMatrix1to2[10][6] = -1.82749340777932;
   fWeightMatrix1to2[11][6] = -1.53869151752637;
   fWeightMatrix1to2[12][6] = -1.70593766386023;
   fWeightMatrix1to2[0][7] = 1.5636112901168;
   fWeightMatrix1to2[1][7] = -1.62354121298159;
   fWeightMatrix1to2[2][7] = 1.79024437266874;
   fWeightMatrix1to2[3][7] = -1.5999199221951;
   fWeightMatrix1to2[4][7] = 0.420853463216859;
   fWeightMatrix1to2[5][7] = -1.24310476176212;
   fWeightMatrix1to2[6][7] = 0.553665437754131;
   fWeightMatrix1to2[7][7] = 0.847102463813724;
   fWeightMatrix1to2[8][7] = -1.48870818240946;
   fWeightMatrix1to2[9][7] = 0.841133107388383;
   fWeightMatrix1to2[10][7] = 0.372267090872147;
   fWeightMatrix1to2[11][7] = -2.23172399449806;
   fWeightMatrix1to2[12][7] = -1.25175869733159;
   fWeightMatrix1to2[0][8] = -1.56172959236018;
   fWeightMatrix1to2[1][8] = -0.650477461359563;
   fWeightMatrix1to2[2][8] = 1.6112187941361;
   fWeightMatrix1to2[3][8] = -0.544456072857965;
   fWeightMatrix1to2[4][8] = 0.316101475548265;
   fWeightMatrix1to2[5][8] = -0.791659417378345;
   fWeightMatrix1to2[6][8] = -1.0700655265847;
   fWeightMatrix1to2[7][8] = -1.67332482760894;
   fWeightMatrix1to2[8][8] = -1.07562502356364;
   fWeightMatrix1to2[9][8] = -1.02787288275013;
   fWeightMatrix1to2[10][8] = 1.08233871189878;
   fWeightMatrix1to2[11][8] = -1.20852126382833;
   fWeightMatrix1to2[12][8] = -1.03215311904284;
   fWeightMatrix1to2[0][9] = 1.61968055510897;
   fWeightMatrix1to2[1][9] = 0.159688973011706;
   fWeightMatrix1to2[2][9] = -0.975098049834985;
   fWeightMatrix1to2[3][9] = 1.79066514806538;
   fWeightMatrix1to2[4][9] = -3.16759149004558;
   fWeightMatrix1to2[5][9] = 1.45559302071878;
   fWeightMatrix1to2[6][9] = 0.802550759886728;
   fWeightMatrix1to2[7][9] = -1.55762898691469;
   fWeightMatrix1to2[8][9] = -1.25348137818879;
   fWeightMatrix1to2[9][9] = -0.585056914490799;
   fWeightMatrix1to2[10][9] = -1.01991291553731;
   fWeightMatrix1to2[11][9] = 0.737690821537112;
   fWeightMatrix1to2[12][9] = 1.69897608129749;
   fWeightMatrix1to2[0][10] = 1.52572095530506;
   fWeightMatrix1to2[1][10] = 1.72257953443473;
   fWeightMatrix1to2[2][10] = -1.57215954744094;
   fWeightMatrix1to2[3][10] = 1.27177850328971;
   fWeightMatrix1to2[4][10] = -2.03723404257927;
   fWeightMatrix1to2[5][10] = 0.682532451533281;
   fWeightMatrix1to2[6][10] = -2.00497124732487;
   fWeightMatrix1to2[7][10] = -2.040209626705;
   fWeightMatrix1to2[8][10] = -0.358784766128392;
   fWeightMatrix1to2[9][10] = 1.19211343543531;
   fWeightMatrix1to2[10][10] = 0.640269203937182;
   fWeightMatrix1to2[11][10] = 1.20241948604789;
   fWeightMatrix1to2[12][10] = 0.457076812946682;
   fWeightMatrix1to2[0][11] = 0.0361930499480635;
   fWeightMatrix1to2[1][11] = -0.534392840817117;
   fWeightMatrix1to2[2][11] = -0.0101191734865525;
   fWeightMatrix1to2[3][11] = 1.96718073597269;
   fWeightMatrix1to2[4][11] = -1.68805138169544;
   fWeightMatrix1to2[5][11] = 0.400286216528083;
   fWeightMatrix1to2[6][11] = -1.90671167728315;
   fWeightMatrix1to2[7][11] = -0.644487519324249;
   fWeightMatrix1to2[8][11] = -0.351016076343245;
   fWeightMatrix1to2[9][11] = 0.280259185229666;
   fWeightMatrix1to2[10][11] = -0.601715990795488;
   fWeightMatrix1to2[11][11] = 1.18037727337499;
   fWeightMatrix1to2[12][11] = 1.85736643822574;
   fWeightMatrix1to2[0][12] = 1.68793837394889;
   fWeightMatrix1to2[1][12] = -0.356238513656121;
   fWeightMatrix1to2[2][12] = -1.29876090467729;
   fWeightMatrix1to2[3][12] = -1.4332025278835;
   fWeightMatrix1to2[4][12] = -1.80763220085469;
   fWeightMatrix1to2[5][12] = 1.21996390995148;
   fWeightMatrix1to2[6][12] = -0.406613931285835;
   fWeightMatrix1to2[7][12] = -1.4266530955461;
   fWeightMatrix1to2[8][12] = 0.307302251182413;
   fWeightMatrix1to2[9][12] = -1.96833382965536;
   fWeightMatrix1to2[10][12] = -0.921791473921909;
   fWeightMatrix1to2[11][12] = -1.35228004667563;
   fWeightMatrix1to2[12][12] = 0.828357014311396;
   fWeightMatrix1to2[0][13] = -1.57883074567668;
   fWeightMatrix1to2[1][13] = -1.90368122596148;
   fWeightMatrix1to2[2][13] = -0.378388005872604;
   fWeightMatrix1to2[3][13] = -1.07626872912338;
   fWeightMatrix1to2[4][13] = -1.50838014647875;
   fWeightMatrix1to2[5][13] = 1.12755149292832;
   fWeightMatrix1to2[6][13] = -1.27175419023544;
   fWeightMatrix1to2[7][13] = -1.09211871480163;
   fWeightMatrix1to2[8][13] = 2.01981036036615;
   fWeightMatrix1to2[9][13] = 0.475846293816665;
   fWeightMatrix1to2[10][13] = 0.0350561482792992;
   fWeightMatrix1to2[11][13] = -0.0644403133584058;
   fWeightMatrix1to2[12][13] = 1.15876308063918;
   fWeightMatrix1to2[0][14] = 1.95476601223229;
   fWeightMatrix1to2[1][14] = 0.694709557111978;
   fWeightMatrix1to2[2][14] = -1.15708816800274;
   fWeightMatrix1to2[3][14] = -0.522457537179467;
   fWeightMatrix1to2[4][14] = -1.85898512834635;
   fWeightMatrix1to2[5][14] = 1.00990578779548;
   fWeightMatrix1to2[6][14] = 0.688071945794152;
   fWeightMatrix1to2[7][14] = -0.128413220527222;
   fWeightMatrix1to2[8][14] = 0.78514222155064;
   fWeightMatrix1to2[9][14] = 0.907634634097877;
   fWeightMatrix1to2[10][14] = 1.87404786083139;
   fWeightMatrix1to2[11][14] = -1.1633641391;
   fWeightMatrix1to2[12][14] = 1.92827799845526;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.820228613718789;
   fWeightMatrix2to3[0][1] = -1.23666085363987;
   fWeightMatrix2to3[0][2] = -0.250649389783672;
   fWeightMatrix2to3[0][3] = -0.338243661977853;
   fWeightMatrix2to3[0][4] = 0.734725478962194;
   fWeightMatrix2to3[0][5] = 0.019815648625585;
   fWeightMatrix2to3[0][6] = 1.0934143774623;
   fWeightMatrix2to3[0][7] = 0.307968989952719;
   fWeightMatrix2to3[0][8] = -0.545054340920399;
   fWeightMatrix2to3[0][9] = 0.22615341158744;
   fWeightMatrix2to3[0][10] = 0.957085145193171;
   fWeightMatrix2to3[0][11] = 0.221299349960777;
   fWeightMatrix2to3[0][12] = -0.509756039107773;
   fWeightMatrix2to3[0][13] = 2.28578209784798;
}

inline double ReadMLP2_25_EC_2x2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP2_25_EC_2x2::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP2_25_EC_2x2::Clear() 
{
   // nothing to clear
}
inline double ReadMLP2_25_EC_2x2::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
