#ifndef _ECALGARLICMLP_HH_
#define _ECALGARLICMLP_HH_

#include "Estimator0_25_B_MLP.class.C"
#include "Estimator0_35_B_MLP.class.C"
#include "Estimator0_5_B_MLP.class.C"
#include "Estimator0_75_B_MLP.class.C"
#include "Estimator1_B_MLP.class.C"
#include "Estimator1_25_B_MLP.class.C"
#include "Estimator1_5_B_MLP.class.C"
#include "Estimator1_75_B_MLP.class.C"
#include "Estimator2_25_B_MLP.class.C"
#include "Estimator3_B_MLP.class.C"
#include "Estimator5_B_MLP.class.C"
#include "Estimator10_B_MLP.class.C"
#include "Estimator20_B_MLP.class.C"
//#include "Estimator50_B_MLP.class.C"

#include "Estimator0_25_EC_MLP.class.C"
#include "Estimator0_35_EC_MLP.class.C"
#include "Estimator0_5_EC_MLP.class.C"
#include "Estimator0_75_EC_MLP.class.C"
#include "Estimator1_EC_MLP.class.C"
#include "Estimator1_25_EC_MLP.class.C"
#include "Estimator1_5_EC_MLP.class.C"
#include "Estimator1_75_EC_MLP.class.C"
#include "Estimator2_25_EC_MLP.class.C"
#include "Estimator3_EC_MLP.class.C"
#include "Estimator5_EC_MLP.class.C"
#include "Estimator10_EC_MLP.class.C"
#include "Estimator20_EC_MLP.class.C"
//#include "Estimator50_EC_MLP.class.C"


#include "Estimator0_25_B_1x1_MLP.class.C"
#include "Estimator0_35_B_1x1_MLP.class.C"
#include "Estimator0_5_B_1x1_MLP.class.C"
#include "Estimator0_75_B_1x1_MLP.class.C"
#include "Estimator1_B_1x1_MLP.class.C"
#include "Estimator1_25_B_1x1_MLP.class.C"
#include "Estimator1_5_B_1x1_MLP.class.C"
#include "Estimator1_75_B_1x1_MLP.class.C"
#include "Estimator2_25_B_1x1_MLP.class.C"
#include "Estimator3_B_1x1_MLP.class.C"
#include "Estimator10_B_1x1_MLP.class.C"

#include "Estimator0_25_EC_1x1_MLP.class.C"
#include "Estimator0_35_EC_1x1_MLP.class.C"
#include "Estimator0_5_EC_1x1_MLP.class.C"
#include "Estimator0_75_EC_1x1_MLP.class.C"
#include "Estimator1_EC_1x1_MLP.class.C"
#include "Estimator1_25_EC_1x1_MLP.class.C"
#include "Estimator1_5_EC_1x1_MLP.class.C"
#include "Estimator1_75_EC_1x1_MLP.class.C"
#include "Estimator2_25_EC_1x1_MLP.class.C"
#include "Estimator3_EC_1x1_MLP.class.C"
#include "Estimator10_EC_1x1_MLP.class.C"

#include "Estimator0_25_B_2x2_MLP.class.C"
#include "Estimator0_35_B_2x2_MLP.class.C"
#include "Estimator0_5_B_2x2_MLP.class.C"
#include "Estimator0_75_B_2x2_MLP.class.C"
#include "Estimator1_B_2x2_MLP.class.C"
#include "Estimator1_25_B_2x2_MLP.class.C"
#include "Estimator1_5_B_2x2_MLP.class.C"
#include "Estimator1_75_B_2x2_MLP.class.C"
#include "Estimator2_25_B_2x2_MLP.class.C"
#include "Estimator3_B_2x2_MLP.class.C"
#include "Estimator10_B_2x2_MLP.class.C"

#include "Estimator0_25_EC_2x2_MLP.class.C"
#include "Estimator0_35_EC_2x2_MLP.class.C"
#include "Estimator0_5_EC_2x2_MLP.class.C"
#include "Estimator0_75_EC_2x2_MLP.class.C"
#include "Estimator1_EC_2x2_MLP.class.C"
#include "Estimator1_25_EC_2x2_MLP.class.C"
#include "Estimator1_5_EC_2x2_MLP.class.C"
#include "Estimator1_75_EC_2x2_MLP.class.C"
#include "Estimator2_25_EC_2x2_MLP.class.C"
#include "Estimator3_EC_2x2_MLP.class.C"
#include "Estimator10_EC_2x2_MLP.class.C"

#include "Estimator0_25_B_10x10_MLP.class.C"
#include "Estimator0_35_B_10x10_MLP.class.C"
#include "Estimator0_5_B_10x10_MLP.class.C"
#include "Estimator0_75_B_10x10_MLP.class.C"
#include "Estimator1_B_10x10_MLP.class.C"
#include "Estimator1_25_B_10x10_MLP.class.C"
#include "Estimator1_5_B_10x10_MLP.class.C"
#include "Estimator1_75_B_10x10_MLP.class.C"
#include "Estimator2_25_B_10x10_MLP.class.C"
#include "Estimator3_B_10x10_MLP.class.C"
#include "Estimator10_B_10x10_MLP.class.C"

#include "Estimator0_25_EC_10x10_MLP.class.C"
#include "Estimator0_35_EC_10x10_MLP.class.C"
#include "Estimator0_5_EC_10x10_MLP.class.C"
#include "Estimator0_75_EC_10x10_MLP.class.C"
#include "Estimator1_EC_10x10_MLP.class.C"
#include "Estimator1_25_EC_10x10_MLP.class.C"
#include "Estimator1_5_EC_10x10_MLP.class.C"
#include "Estimator1_75_EC_10x10_MLP.class.C"
#include "Estimator2_25_EC_10x10_MLP.class.C"
#include "Estimator3_EC_10x10_MLP.class.C"
#include "Estimator10_EC_10x10_MLP.class.C"

#endif
