// Class: ReadMLP1_5_EC_1x1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Mon Aug 10 12:00:32 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 2174


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,8.7111825943]
ClusterParameters.end         ClusterParameters.end             'F'    [4.79454278946,33.7956962585]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,21.998714447]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.968771219254]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0498718954623,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.541569590569,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.0105645600706,0.999998092651]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999998509884]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.779958963394,41.9809379578]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.138539165258,0.887112557888]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,76]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [54.7728042603,729781.625]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [0,21.998714447]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP1_5_EC_1x1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1_5_EC_1x1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1_5_EC_1x1" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 8.71118259429932;
      fVmin[1] = 4.79454278945923;
      fVmax[1] = 33.7956962585449;
      fVmin[2] = 0;
      fVmax[2] = 21.9987144470215;
      fVmin[3] = 0;
      fVmax[3] = 0.96877121925354;
      fVmin[4] = 0.0498718954622746;
      fVmax[4] = 1;
      fVmin[5] = 0.541569590568542;
      fVmax[5] = 1;
      fVmin[6] = 0.0105645600706339;
      fVmax[6] = 0.999998092651367;
      fVmin[7] = 0;
      fVmax[7] = 0.999998509883881;
      fVmin[8] = 0.779958963394165;
      fVmax[8] = 41.9809379577637;
      fVmin[9] = 0.138539165258408;
      fVmax[9] = 0.887112557888031;
      fVmin[10] = 5;
      fVmax[10] = 76;
      fVmin[11] = 54.7728042602539;
      fVmax[11] = 729781.625;
      fVmin[12] = 0;
      fVmax[12] = 21.9987144470215;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP1_5_EC_1x1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP1_5_EC_1x1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.416244883340009;
   fWeightMatrix0to1[1][0] = 1.96776734130473;
   fWeightMatrix0to1[2][0] = 0.458928164686176;
   fWeightMatrix0to1[3][0] = 1.85069113569552;
   fWeightMatrix0to1[4][0] = -1.72277936997094;
   fWeightMatrix0to1[5][0] = -1.09441114360007;
   fWeightMatrix0to1[6][0] = -0.525423278443475;
   fWeightMatrix0to1[7][0] = 1.74283570168517;
   fWeightMatrix0to1[8][0] = -1.71282950714449;
   fWeightMatrix0to1[9][0] = -0.280598384509555;
   fWeightMatrix0to1[10][0] = -1.73954413162263;
   fWeightMatrix0to1[11][0] = -0.0588854918023536;
   fWeightMatrix0to1[12][0] = -1.27326717696554;
   fWeightMatrix0to1[13][0] = -0.601988693706703;
   fWeightMatrix0to1[0][1] = -0.648019900744857;
   fWeightMatrix0to1[1][1] = 0.683457424496947;
   fWeightMatrix0to1[2][1] = -0.686067963253436;
   fWeightMatrix0to1[3][1] = 1.64883649394945;
   fWeightMatrix0to1[4][1] = 0.221436458947695;
   fWeightMatrix0to1[5][1] = 1.40126574792165;
   fWeightMatrix0to1[6][1] = -0.354916103672689;
   fWeightMatrix0to1[7][1] = -0.905976009439281;
   fWeightMatrix0to1[8][1] = 1.42055062364947;
   fWeightMatrix0to1[9][1] = -0.481826060169791;
   fWeightMatrix0to1[10][1] = -1.23919643061815;
   fWeightMatrix0to1[11][1] = -0.371174763539651;
   fWeightMatrix0to1[12][1] = 1.08963111818961;
   fWeightMatrix0to1[13][1] = -1.00452862056256;
   fWeightMatrix0to1[0][2] = -1.88739398013533;
   fWeightMatrix0to1[1][2] = 0.135187389573285;
   fWeightMatrix0to1[2][2] = 0.396763601347944;
   fWeightMatrix0to1[3][2] = 1.49203714778184;
   fWeightMatrix0to1[4][2] = -0.208615679844898;
   fWeightMatrix0to1[5][2] = -0.574212306674348;
   fWeightMatrix0to1[6][2] = 0.234552541249657;
   fWeightMatrix0to1[7][2] = -0.595539151350679;
   fWeightMatrix0to1[8][2] = -0.958928704960343;
   fWeightMatrix0to1[9][2] = 1.89277464547834;
   fWeightMatrix0to1[10][2] = -1.12509747348215;
   fWeightMatrix0to1[11][2] = 1.08822610855024;
   fWeightMatrix0to1[12][2] = 1.46475143848121;
   fWeightMatrix0to1[13][2] = 0.924098743024481;
   fWeightMatrix0to1[0][3] = 1.70918867765626;
   fWeightMatrix0to1[1][3] = 1.25690873167497;
   fWeightMatrix0to1[2][3] = -0.779737824229535;
   fWeightMatrix0to1[3][3] = -1.73529412990689;
   fWeightMatrix0to1[4][3] = 0.576566955184725;
   fWeightMatrix0to1[5][3] = -0.0436224134075397;
   fWeightMatrix0to1[6][3] = 1.73324712462542;
   fWeightMatrix0to1[7][3] = 1.74244841472718;
   fWeightMatrix0to1[8][3] = 1.78014349046261;
   fWeightMatrix0to1[9][3] = 1.04527932143724;
   fWeightMatrix0to1[10][3] = -1.47544428776745;
   fWeightMatrix0to1[11][3] = 1.32788142767651;
   fWeightMatrix0to1[12][3] = -2.2929155458426;
   fWeightMatrix0to1[13][3] = -0.956654297280261;
   fWeightMatrix0to1[0][4] = -0.92329049306167;
   fWeightMatrix0to1[1][4] = -1.7427015443492;
   fWeightMatrix0to1[2][4] = 1.87379118010244;
   fWeightMatrix0to1[3][4] = 0.62304201575093;
   fWeightMatrix0to1[4][4] = -1.82901854144774;
   fWeightMatrix0to1[5][4] = 0.402806828829598;
   fWeightMatrix0to1[6][4] = -0.194430365034657;
   fWeightMatrix0to1[7][4] = 1.42262303789753;
   fWeightMatrix0to1[8][4] = 1.47162245570433;
   fWeightMatrix0to1[9][4] = -1.47603354434499;
   fWeightMatrix0to1[10][4] = 0.152130676391861;
   fWeightMatrix0to1[11][4] = -0.920802274654586;
   fWeightMatrix0to1[12][4] = -0.0756868427228032;
   fWeightMatrix0to1[13][4] = -0.847331801378371;
   fWeightMatrix0to1[0][5] = -0.183506492929913;
   fWeightMatrix0to1[1][5] = -1.44109147164369;
   fWeightMatrix0to1[2][5] = 1.18919034055443;
   fWeightMatrix0to1[3][5] = 0.960389717632408;
   fWeightMatrix0to1[4][5] = 1.26392895784009;
   fWeightMatrix0to1[5][5] = -0.329145215484807;
   fWeightMatrix0to1[6][5] = -1.9962549045991;
   fWeightMatrix0to1[7][5] = -1.4270115159968;
   fWeightMatrix0to1[8][5] = 0.797791773382681;
   fWeightMatrix0to1[9][5] = 0.815804309536819;
   fWeightMatrix0to1[10][5] = 1.94823464079643;
   fWeightMatrix0to1[11][5] = 0.905448534651242;
   fWeightMatrix0to1[12][5] = 0.362952325018442;
   fWeightMatrix0to1[13][5] = -0.741377953287956;
   fWeightMatrix0to1[0][6] = -0.380938572472526;
   fWeightMatrix0to1[1][6] = -0.21345852087832;
   fWeightMatrix0to1[2][6] = 1.67614528282464;
   fWeightMatrix0to1[3][6] = -1.26418747597634;
   fWeightMatrix0to1[4][6] = -1.84408727081151;
   fWeightMatrix0to1[5][6] = -1.83570489282416;
   fWeightMatrix0to1[6][6] = -0.299552897979203;
   fWeightMatrix0to1[7][6] = 0.836063410678198;
   fWeightMatrix0to1[8][6] = 2.08096706321785;
   fWeightMatrix0to1[9][6] = -2.34217104720149;
   fWeightMatrix0to1[10][6] = -0.904922258010249;
   fWeightMatrix0to1[11][6] = 1.4727915877002;
   fWeightMatrix0to1[12][6] = -2.40429345309852;
   fWeightMatrix0to1[13][6] = -1.27727373689409;
   fWeightMatrix0to1[0][7] = -0.76071250124855;
   fWeightMatrix0to1[1][7] = 0.141197517831045;
   fWeightMatrix0to1[2][7] = -1.41377601586956;
   fWeightMatrix0to1[3][7] = -1.24203326318051;
   fWeightMatrix0to1[4][7] = 0.26671898392139;
   fWeightMatrix0to1[5][7] = 2.52601425429144;
   fWeightMatrix0to1[6][7] = -1.14046712758063;
   fWeightMatrix0to1[7][7] = 1.49950929229606;
   fWeightMatrix0to1[8][7] = -0.540997492164498;
   fWeightMatrix0to1[9][7] = -0.786607053148968;
   fWeightMatrix0to1[10][7] = 0.26035584736232;
   fWeightMatrix0to1[11][7] = 0.457131879089355;
   fWeightMatrix0to1[12][7] = -1.53937468043303;
   fWeightMatrix0to1[13][7] = 0.590293974686762;
   fWeightMatrix0to1[0][8] = 0.027593562657179;
   fWeightMatrix0to1[1][8] = 0.446288486454099;
   fWeightMatrix0to1[2][8] = -1.58719177037107;
   fWeightMatrix0to1[3][8] = 1.84967618674549;
   fWeightMatrix0to1[4][8] = 0.469101656476666;
   fWeightMatrix0to1[5][8] = -1.15124081061598;
   fWeightMatrix0to1[6][8] = 0.688976657914634;
   fWeightMatrix0to1[7][8] = -1.34023330461835;
   fWeightMatrix0to1[8][8] = -1.41847574184771;
   fWeightMatrix0to1[9][8] = 0.156065474429894;
   fWeightMatrix0to1[10][8] = -0.441646100274912;
   fWeightMatrix0to1[11][8] = 1.46652020248331;
   fWeightMatrix0to1[12][8] = 0.761014777904167;
   fWeightMatrix0to1[13][8] = 0.0189761972037378;
   fWeightMatrix0to1[0][9] = -0.517723758230421;
   fWeightMatrix0to1[1][9] = 0.15500009822286;
   fWeightMatrix0to1[2][9] = -1.65765297096037;
   fWeightMatrix0to1[3][9] = 1.17322389631071;
   fWeightMatrix0to1[4][9] = 0.352615565058711;
   fWeightMatrix0to1[5][9] = -1.80338545141923;
   fWeightMatrix0to1[6][9] = 0.594682377651166;
   fWeightMatrix0to1[7][9] = -0.93413794390747;
   fWeightMatrix0to1[8][9] = -0.248661462540158;
   fWeightMatrix0to1[9][9] = -0.0845981130941548;
   fWeightMatrix0to1[10][9] = 1.60215388764143;
   fWeightMatrix0to1[11][9] = -2.21149722816584;
   fWeightMatrix0to1[12][9] = -0.507044748212244;
   fWeightMatrix0to1[13][9] = 1.44765621311409;
   fWeightMatrix0to1[0][10] = 1.43418709443477;
   fWeightMatrix0to1[1][10] = 0.153787977411485;
   fWeightMatrix0to1[2][10] = -1.47436257521018;
   fWeightMatrix0to1[3][10] = -0.271294122625569;
   fWeightMatrix0to1[4][10] = -1.53182096127228;
   fWeightMatrix0to1[5][10] = 1.13040030748399;
   fWeightMatrix0to1[6][10] = 1.05257585556343;
   fWeightMatrix0to1[7][10] = -0.413557545341183;
   fWeightMatrix0to1[8][10] = 0.456360367931545;
   fWeightMatrix0to1[9][10] = -2.09021208626255;
   fWeightMatrix0to1[10][10] = -1.42533465183212;
   fWeightMatrix0to1[11][10] = 0.349411652905122;
   fWeightMatrix0to1[12][10] = 1.60402428847394;
   fWeightMatrix0to1[13][10] = -0.441611725229936;
   fWeightMatrix0to1[0][11] = -1.13529465357681;
   fWeightMatrix0to1[1][11] = 0.304325693484851;
   fWeightMatrix0to1[2][11] = 0.570642224881068;
   fWeightMatrix0to1[3][11] = 0.656377145149985;
   fWeightMatrix0to1[4][11] = 0.770236902848758;
   fWeightMatrix0to1[5][11] = -1.61576065232718;
   fWeightMatrix0to1[6][11] = 1.50945282421052;
   fWeightMatrix0to1[7][11] = 0.195674654544448;
   fWeightMatrix0to1[8][11] = 0.745467383025324;
   fWeightMatrix0to1[9][11] = 0.750141589013995;
   fWeightMatrix0to1[10][11] = 0.987316855659392;
   fWeightMatrix0to1[11][11] = -0.749056244055496;
   fWeightMatrix0to1[12][11] = 0.00617908369041856;
   fWeightMatrix0to1[13][11] = 1.10676082349904;
   fWeightMatrix0to1[0][12] = -1.13189891121164;
   fWeightMatrix0to1[1][12] = -0.547716877955397;
   fWeightMatrix0to1[2][12] = 1.26454009419673;
   fWeightMatrix0to1[3][12] = 0.864641532327368;
   fWeightMatrix0to1[4][12] = -0.266881254416756;
   fWeightMatrix0to1[5][12] = 0.849543231028204;
   fWeightMatrix0to1[6][12] = 1.86109624047059;
   fWeightMatrix0to1[7][12] = -2.35006200462884;
   fWeightMatrix0to1[8][12] = 1.27770111718767;
   fWeightMatrix0to1[9][12] = -0.40602540396324;
   fWeightMatrix0to1[10][12] = 0.613149423219721;
   fWeightMatrix0to1[11][12] = -1.85063677628843;
   fWeightMatrix0to1[12][12] = -1.04945327149199;
   fWeightMatrix0to1[13][12] = 1.21357867713458;
   fWeightMatrix0to1[0][13] = 2.42439529272622;
   fWeightMatrix0to1[1][13] = -1.7950454331742;
   fWeightMatrix0to1[2][13] = 0.307623228224792;
   fWeightMatrix0to1[3][13] = -0.742906341182738;
   fWeightMatrix0to1[4][13] = 0.292893073898142;
   fWeightMatrix0to1[5][13] = 2.06315121190467;
   fWeightMatrix0to1[6][13] = -0.637605499637585;
   fWeightMatrix0to1[7][13] = -0.0294601764445745;
   fWeightMatrix0to1[8][13] = -1.11672753450368;
   fWeightMatrix0to1[9][13] = 1.62699823781147;
   fWeightMatrix0to1[10][13] = 1.61162996165618;
   fWeightMatrix0to1[11][13] = 1.03582637471395;
   fWeightMatrix0to1[12][13] = -0.267271465077069;
   fWeightMatrix0to1[13][13] = -0.654957346448805;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.81784244441163;
   fWeightMatrix1to2[1][0] = 1.04831176256035;
   fWeightMatrix1to2[2][0] = 0.483152130270651;
   fWeightMatrix1to2[3][0] = -1.08784438807837;
   fWeightMatrix1to2[4][0] = -0.527145988624496;
   fWeightMatrix1to2[5][0] = 0.278397304656878;
   fWeightMatrix1to2[6][0] = -0.0462150451573862;
   fWeightMatrix1to2[7][0] = -1.95587565549397;
   fWeightMatrix1to2[8][0] = 1.51438772475559;
   fWeightMatrix1to2[9][0] = 0.732862421317361;
   fWeightMatrix1to2[10][0] = -0.426750858683403;
   fWeightMatrix1to2[11][0] = -0.135531639919173;
   fWeightMatrix1to2[12][0] = 1.60534479192603;
   fWeightMatrix1to2[0][1] = 0.994879571683625;
   fWeightMatrix1to2[1][1] = 0.322788222962789;
   fWeightMatrix1to2[2][1] = -0.0700604335612978;
   fWeightMatrix1to2[3][1] = -2.23799122629683;
   fWeightMatrix1to2[4][1] = -0.710810150535993;
   fWeightMatrix1to2[5][1] = 1.63300708265519;
   fWeightMatrix1to2[6][1] = 1.43803410054285;
   fWeightMatrix1to2[7][1] = 0.787805999204505;
   fWeightMatrix1to2[8][1] = 0.165023141169557;
   fWeightMatrix1to2[9][1] = 1.61663030846245;
   fWeightMatrix1to2[10][1] = -1.99943731555108;
   fWeightMatrix1to2[11][1] = -1.31889184265599;
   fWeightMatrix1to2[12][1] = -0.211652441119868;
   fWeightMatrix1to2[0][2] = -1.26453797903664;
   fWeightMatrix1to2[1][2] = 1.06531561146288;
   fWeightMatrix1to2[2][2] = 1.62284853105605;
   fWeightMatrix1to2[3][2] = -1.09829376243937;
   fWeightMatrix1to2[4][2] = 0.0777249126997333;
   fWeightMatrix1to2[5][2] = -0.152704369171164;
   fWeightMatrix1to2[6][2] = -1.77215946053125;
   fWeightMatrix1to2[7][2] = -0.934162178660811;
   fWeightMatrix1to2[8][2] = 1.04298451555954;
   fWeightMatrix1to2[9][2] = 0.227369910871703;
   fWeightMatrix1to2[10][2] = 0.826576152528416;
   fWeightMatrix1to2[11][2] = -1.16249325487072;
   fWeightMatrix1to2[12][2] = 1.72193602741171;
   fWeightMatrix1to2[0][3] = -1.76763073418048;
   fWeightMatrix1to2[1][3] = 0.666393409598698;
   fWeightMatrix1to2[2][3] = 0.0931278454433956;
   fWeightMatrix1to2[3][3] = -1.25881261825961;
   fWeightMatrix1to2[4][3] = -1.14119125136459;
   fWeightMatrix1to2[5][3] = -2.03375761858359;
   fWeightMatrix1to2[6][3] = -0.0538753684844364;
   fWeightMatrix1to2[7][3] = -1.87407319652388;
   fWeightMatrix1to2[8][3] = -1.62266490425714;
   fWeightMatrix1to2[9][3] = -2.00132471421182;
   fWeightMatrix1to2[10][3] = 0.242528601842237;
   fWeightMatrix1to2[11][3] = -1.02486982470772;
   fWeightMatrix1to2[12][3] = -1.69702637395903;
   fWeightMatrix1to2[0][4] = 1.4333895197663;
   fWeightMatrix1to2[1][4] = -0.922843790527326;
   fWeightMatrix1to2[2][4] = 0.148245611609403;
   fWeightMatrix1to2[3][4] = -1.06950543561803;
   fWeightMatrix1to2[4][4] = -0.659775168236998;
   fWeightMatrix1to2[5][4] = 1.69264434483625;
   fWeightMatrix1to2[6][4] = 1.29674634315687;
   fWeightMatrix1to2[7][4] = -1.20351578965687;
   fWeightMatrix1to2[8][4] = -1.54601237003066;
   fWeightMatrix1to2[9][4] = -1.2004104005626;
   fWeightMatrix1to2[10][4] = -0.635874164359084;
   fWeightMatrix1to2[11][4] = -1.65202607070248;
   fWeightMatrix1to2[12][4] = 0.286351683488928;
   fWeightMatrix1to2[0][5] = -0.161089214590445;
   fWeightMatrix1to2[1][5] = 1.94957343547669;
   fWeightMatrix1to2[2][5] = -0.49166821053705;
   fWeightMatrix1to2[3][5] = 0.473795749038291;
   fWeightMatrix1to2[4][5] = -1.43036739840278;
   fWeightMatrix1to2[5][5] = -1.79017881076554;
   fWeightMatrix1to2[6][5] = 1.0627165016624;
   fWeightMatrix1to2[7][5] = 1.15502207991349;
   fWeightMatrix1to2[8][5] = -0.80037253592256;
   fWeightMatrix1to2[9][5] = -0.906693438211268;
   fWeightMatrix1to2[10][5] = 0.975585466800318;
   fWeightMatrix1to2[11][5] = 1.22114372733216;
   fWeightMatrix1to2[12][5] = 0.525800202274713;
   fWeightMatrix1to2[0][6] = -0.519735660295048;
   fWeightMatrix1to2[1][6] = -0.475792386163479;
   fWeightMatrix1to2[2][6] = 1.50915815888916;
   fWeightMatrix1to2[3][6] = 0.699829819552679;
   fWeightMatrix1to2[4][6] = 1.19919725499704;
   fWeightMatrix1to2[5][6] = -0.360374086700941;
   fWeightMatrix1to2[6][6] = 0.509629974622398;
   fWeightMatrix1to2[7][6] = -0.265209971472932;
   fWeightMatrix1to2[8][6] = -1.49706167394577;
   fWeightMatrix1to2[9][6] = -0.858826724699017;
   fWeightMatrix1to2[10][6] = -1.75805766973365;
   fWeightMatrix1to2[11][6] = -1.36229166839982;
   fWeightMatrix1to2[12][6] = -1.61543494632873;
   fWeightMatrix1to2[0][7] = 1.43259717099944;
   fWeightMatrix1to2[1][7] = -1.65703144704216;
   fWeightMatrix1to2[2][7] = 1.61248715337918;
   fWeightMatrix1to2[3][7] = -1.7967659640516;
   fWeightMatrix1to2[4][7] = 1.00543657702888;
   fWeightMatrix1to2[5][7] = -1.27915063877773;
   fWeightMatrix1to2[6][7] = 0.46880784473482;
   fWeightMatrix1to2[7][7] = 1.01860216536764;
   fWeightMatrix1to2[8][7] = -1.80296606409698;
   fWeightMatrix1to2[9][7] = -0.104796356949041;
   fWeightMatrix1to2[10][7] = 0.320722418606219;
   fWeightMatrix1to2[11][7] = -1.9487509714113;
   fWeightMatrix1to2[12][7] = -1.3940561922773;
   fWeightMatrix1to2[0][8] = -1.83491407757116;
   fWeightMatrix1to2[1][8] = -0.693530523183953;
   fWeightMatrix1to2[2][8] = 2.01407780190696;
   fWeightMatrix1to2[3][8] = -0.794405950517496;
   fWeightMatrix1to2[4][8] = 1.95625274977955;
   fWeightMatrix1to2[5][8] = -0.826405589695185;
   fWeightMatrix1to2[6][8] = -1.27734889929026;
   fWeightMatrix1to2[7][8] = -1.13194317779443;
   fWeightMatrix1to2[8][8] = -0.947855354935538;
   fWeightMatrix1to2[9][8] = -0.953925074336417;
   fWeightMatrix1to2[10][8] = 0.857986073959301;
   fWeightMatrix1to2[11][8] = -1.32136471848316;
   fWeightMatrix1to2[12][8] = -1.1388817806453;
   fWeightMatrix1to2[0][9] = 2.23310753720021;
   fWeightMatrix1to2[1][9] = 0.248683061579734;
   fWeightMatrix1to2[2][9] = -0.347251693453433;
   fWeightMatrix1to2[3][9] = 2.07238758080237;
   fWeightMatrix1to2[4][9] = -3.12485357454746;
   fWeightMatrix1to2[5][9] = 1.51441138664773;
   fWeightMatrix1to2[6][9] = 1.1734672925642;
   fWeightMatrix1to2[7][9] = -1.20161081676724;
   fWeightMatrix1to2[8][9] = -0.848718394400401;
   fWeightMatrix1to2[9][9] = -0.247948460464656;
   fWeightMatrix1to2[10][9] = -0.60166138108802;
   fWeightMatrix1to2[11][9] = 0.461442279766203;
   fWeightMatrix1to2[12][9] = 1.83507284719069;
   fWeightMatrix1to2[0][10] = 1.37275849805185;
   fWeightMatrix1to2[1][10] = 1.70177543606121;
   fWeightMatrix1to2[2][10] = -1.42823661312393;
   fWeightMatrix1to2[3][10] = 1.33379999055115;
   fWeightMatrix1to2[4][10] = -2.17561457660036;
   fWeightMatrix1to2[5][10] = 0.69211766423546;
   fWeightMatrix1to2[6][10] = -1.82312228960838;
   fWeightMatrix1to2[7][10] = -1.87583622934512;
   fWeightMatrix1to2[8][10] = -0.0182400245040551;
   fWeightMatrix1to2[9][10] = 1.59493961640672;
   fWeightMatrix1to2[10][10] = 0.715729711605698;
   fWeightMatrix1to2[11][10] = 1.05617584903496;
   fWeightMatrix1to2[12][10] = 0.371192358334765;
   fWeightMatrix1to2[0][11] = -0.175665459373507;
   fWeightMatrix1to2[1][11] = -0.568046850295366;
   fWeightMatrix1to2[2][11] = 0.0555255826975918;
   fWeightMatrix1to2[3][11] = 1.76007448899901;
   fWeightMatrix1to2[4][11] = -1.73847576265256;
   fWeightMatrix1to2[5][11] = 0.290631688891379;
   fWeightMatrix1to2[6][11] = -1.53449659815545;
   fWeightMatrix1to2[7][11] = -0.443081240704253;
   fWeightMatrix1to2[8][11] = 0.0745837772349278;
   fWeightMatrix1to2[9][11] = 0.79822901953413;
   fWeightMatrix1to2[10][11] = -1.12498840773596;
   fWeightMatrix1to2[11][11] = 1.02024627536106;
   fWeightMatrix1to2[12][11] = 1.76130957805086;
   fWeightMatrix1to2[0][12] = 0.943470459682179;
   fWeightMatrix1to2[1][12] = -0.328654118459887;
   fWeightMatrix1to2[2][12] = -0.960516201181992;
   fWeightMatrix1to2[3][12] = -1.23647292623933;
   fWeightMatrix1to2[4][12] = -1.76614060352679;
   fWeightMatrix1to2[5][12] = 0.908583455149832;
   fWeightMatrix1to2[6][12] = -0.480981236716416;
   fWeightMatrix1to2[7][12] = -1.37241075729656;
   fWeightMatrix1to2[8][12] = 0.462771941543114;
   fWeightMatrix1to2[9][12] = -1.37011406718925;
   fWeightMatrix1to2[10][12] = -0.862634785154398;
   fWeightMatrix1to2[11][12] = -1.60576651576315;
   fWeightMatrix1to2[12][12] = 0.922644836919509;
   fWeightMatrix1to2[0][13] = -1.3541641798498;
   fWeightMatrix1to2[1][13] = -1.89550735328935;
   fWeightMatrix1to2[2][13] = -0.515332332972104;
   fWeightMatrix1to2[3][13] = -1.00628845859673;
   fWeightMatrix1to2[4][13] = -1.45306009304003;
   fWeightMatrix1to2[5][13] = 1.1885658851593;
   fWeightMatrix1to2[6][13] = -1.09163732716588;
   fWeightMatrix1to2[7][13] = -1.25941907451791;
   fWeightMatrix1to2[8][13] = 1.67686979273795;
   fWeightMatrix1to2[9][13] = 0.195142280207159;
   fWeightMatrix1to2[10][13] = 0.537229976773965;
   fWeightMatrix1to2[11][13] = 0.096813946007328;
   fWeightMatrix1to2[12][13] = 1.25817340763399;
   fWeightMatrix1to2[0][14] = 1.76470032866757;
   fWeightMatrix1to2[1][14] = 0.663647127062555;
   fWeightMatrix1to2[2][14] = -1.0072406689305;
   fWeightMatrix1to2[3][14] = -0.395228540701297;
   fWeightMatrix1to2[4][14] = -1.94944130187026;
   fWeightMatrix1to2[5][14] = 0.98885869097787;
   fWeightMatrix1to2[6][14] = 0.836273143977214;
   fWeightMatrix1to2[7][14] = 0.0664644339530653;
   fWeightMatrix1to2[8][14] = 1.1288336881444;
   fWeightMatrix1to2[9][14] = 1.32098292758385;
   fWeightMatrix1to2[10][14] = 1.92049071530086;
   fWeightMatrix1to2[11][14] = -1.33002948896195;
   fWeightMatrix1to2[12][14] = 1.82948399380908;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.0500555808362881;
   fWeightMatrix2to3[0][1] = -1.72123389994932;
   fWeightMatrix2to3[0][2] = -0.165878384341891;
   fWeightMatrix2to3[0][3] = -0.0657914381972331;
   fWeightMatrix2to3[0][4] = 1.23166541540048;
   fWeightMatrix2to3[0][5] = 0.0161204822080478;
   fWeightMatrix2to3[0][6] = -0.0403278647547302;
   fWeightMatrix2to3[0][7] = -0.0386799907970626;
   fWeightMatrix2to3[0][8] = -0.110859219791617;
   fWeightMatrix2to3[0][9] = 0.0223087146824704;
   fWeightMatrix2to3[0][10] = 1.02218304082177;
   fWeightMatrix2to3[0][11] = 0.00239844130386525;
   fWeightMatrix2to3[0][12] = -0.96783049607489;
   fWeightMatrix2to3[0][13] = 1.82898912537034;
}

inline double ReadMLP1_5_EC_1x1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP1_5_EC_1x1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP1_5_EC_1x1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP1_5_EC_1x1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
