// Class: ReadMLP3_B
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Fri Aug  7 11:00:29 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 24757


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,12.3289442062]
ClusterParameters.end         ClusterParameters.end             'F'    [5.74623918533,36.0727729797]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,31.222486496]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.945516943932]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0,0.985564291477]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.215402781963,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.0227096620947,0.999999940395]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999999701977]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0.971844494343,28.2041664124]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.049552179873,0.931572794914]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [7,157]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [46.3425292969,1436199.625]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-10.492934227,29.7717819214]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP3_B : public IClassifierReader {

 public:

   // constructor
   ReadMLP3_B( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP3_B" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 12.3289442062378;
      fVmin[1] = 5.74623918533325;
      fVmax[1] = 36.0727729797363;
      fVmin[2] = 0;
      fVmax[2] = 31.2224864959717;
      fVmin[3] = 0;
      fVmax[3] = 0.94551694393158;
      fVmin[4] = 0;
      fVmax[4] = 0.985564291477203;
      fVmin[5] = 0.215402781963348;
      fVmax[5] = 1;
      fVmin[6] = 0.0227096620947123;
      fVmax[6] = 0.999999940395355;
      fVmin[7] = 0;
      fVmax[7] = 0.999999701976776;
      fVmin[8] = 0.971844494342804;
      fVmax[8] = 28.2041664123535;
      fVmin[9] = 0.0495521798729897;
      fVmax[9] = 0.931572794914246;
      fVmin[10] = 7;
      fVmax[10] = 157;
      fVmin[11] = 46.342529296875;
      fVmax[11] = 1436199.625;
      fVmin[12] = -10.4929342269897;
      fVmax[12] = 29.7717819213867;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP3_B() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP3_B::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.416114061531005;
   fWeightMatrix0to1[1][0] = 1.69278032232412;
   fWeightMatrix0to1[2][0] = -0.615138010139036;
   fWeightMatrix0to1[3][0] = 1.79744438246981;
   fWeightMatrix0to1[4][0] = -1.58001071597571;
   fWeightMatrix0to1[5][0] = -2.33532027718095;
   fWeightMatrix0to1[6][0] = -0.575020796453164;
   fWeightMatrix0to1[7][0] = 2.21739611282869;
   fWeightMatrix0to1[8][0] = -0.936818348014171;
   fWeightMatrix0to1[9][0] = -0.819196094324029;
   fWeightMatrix0to1[10][0] = -1.23601745475645;
   fWeightMatrix0to1[11][0] = -0.48267967861733;
   fWeightMatrix0to1[12][0] = -0.799859946279109;
   fWeightMatrix0to1[13][0] = -0.302482904077015;
   fWeightMatrix0to1[0][1] = -0.341714970935747;
   fWeightMatrix0to1[1][1] = 0.511553317766641;
   fWeightMatrix0to1[2][1] = -0.873656785129047;
   fWeightMatrix0to1[3][1] = 1.64068691057122;
   fWeightMatrix0to1[4][1] = 0.395248005236501;
   fWeightMatrix0to1[5][1] = 1.08694200191221;
   fWeightMatrix0to1[6][1] = -0.32917171766144;
   fWeightMatrix0to1[7][1] = -0.495110335303002;
   fWeightMatrix0to1[8][1] = 1.38204524990605;
   fWeightMatrix0to1[9][1] = 0.626675772323179;
   fWeightMatrix0to1[10][1] = -0.738041380857278;
   fWeightMatrix0to1[11][1] = -0.328396572264735;
   fWeightMatrix0to1[12][1] = 2.10351794888579;
   fWeightMatrix0to1[13][1] = -1.05116720838192;
   fWeightMatrix0to1[0][2] = -1.16748337020714;
   fWeightMatrix0to1[1][2] = 0.111427086333339;
   fWeightMatrix0to1[2][2] = -0.228930935064331;
   fWeightMatrix0to1[3][2] = 1.56164023436461;
   fWeightMatrix0to1[4][2] = -0.181820911902592;
   fWeightMatrix0to1[5][2] = -0.502317381278366;
   fWeightMatrix0to1[6][2] = 0.175266283382903;
   fWeightMatrix0to1[7][2] = 0.200344015552935;
   fWeightMatrix0to1[8][2] = -1.7203840719348;
   fWeightMatrix0to1[9][2] = 1.77216383108992;
   fWeightMatrix0to1[10][2] = -0.969357604907684;
   fWeightMatrix0to1[11][2] = 1.01493781365729;
   fWeightMatrix0to1[12][2] = 2.63295273663396;
   fWeightMatrix0to1[13][2] = 0.934079704014645;
   fWeightMatrix0to1[0][3] = 1.96896473845312;
   fWeightMatrix0to1[1][3] = 1.65063318398299;
   fWeightMatrix0to1[2][3] = -0.857479335098736;
   fWeightMatrix0to1[3][3] = -1.34591667637476;
   fWeightMatrix0to1[4][3] = 0.780361649709655;
   fWeightMatrix0to1[5][3] = -0.0391085415154048;
   fWeightMatrix0to1[6][3] = 1.81776607101726;
   fWeightMatrix0to1[7][3] = 3.35873343765185;
   fWeightMatrix0to1[8][3] = 2.99590892927449;
   fWeightMatrix0to1[9][3] = 0.168758415270417;
   fWeightMatrix0to1[10][3] = -2.13580736955173;
   fWeightMatrix0to1[11][3] = 0.973060493890543;
   fWeightMatrix0to1[12][3] = -2.07992108568135;
   fWeightMatrix0to1[13][3] = -1.13885296294233;
   fWeightMatrix0to1[0][4] = -2.54937277990412;
   fWeightMatrix0to1[1][4] = -1.41541081243216;
   fWeightMatrix0to1[2][4] = 2.22204596608993;
   fWeightMatrix0to1[3][4] = 0.639931822079796;
   fWeightMatrix0to1[4][4] = -1.70986281691703;
   fWeightMatrix0to1[5][4] = 0.642749598803312;
   fWeightMatrix0to1[6][4] = -0.0509989689654649;
   fWeightMatrix0to1[7][4] = 0.397489447582846;
   fWeightMatrix0to1[8][4] = 2.2817206546943;
   fWeightMatrix0to1[9][4] = -1.53451678012636;
   fWeightMatrix0to1[10][4] = -0.224029234439949;
   fWeightMatrix0to1[11][4] = -1.04795174264074;
   fWeightMatrix0to1[12][4] = -1.577082050139;
   fWeightMatrix0to1[13][4] = -0.904348526103159;
   fWeightMatrix0to1[0][5] = -1.29246434348548;
   fWeightMatrix0to1[1][5] = -1.10643463697116;
   fWeightMatrix0to1[2][5] = 0.71469239185799;
   fWeightMatrix0to1[3][5] = 0.780210480016096;
   fWeightMatrix0to1[4][5] = 1.09864094819817;
   fWeightMatrix0to1[5][5] = -1.12794974493172;
   fWeightMatrix0to1[6][5] = -1.77316197450768;
   fWeightMatrix0to1[7][5] = -1.96862747263167;
   fWeightMatrix0to1[8][5] = 0.331140219265953;
   fWeightMatrix0to1[9][5] = -0.567025442258054;
   fWeightMatrix0to1[10][5] = 1.90135360183711;
   fWeightMatrix0to1[11][5] = 0.809420790058696;
   fWeightMatrix0to1[12][5] = -1.38627160678186;
   fWeightMatrix0to1[13][5] = -0.804441721337043;
   fWeightMatrix0to1[0][6] = -1.20111903899153;
   fWeightMatrix0to1[1][6] = -0.453719787526429;
   fWeightMatrix0to1[2][6] = 1.15379801172664;
   fWeightMatrix0to1[3][6] = -1.65231952335138;
   fWeightMatrix0to1[4][6] = -1.96421151344105;
   fWeightMatrix0to1[5][6] = -1.64917280338608;
   fWeightMatrix0to1[6][6] = -0.45350122700379;
   fWeightMatrix0to1[7][6] = -0.388232411656419;
   fWeightMatrix0to1[8][6] = 3.61532734556551;
   fWeightMatrix0to1[9][6] = -1.91992278749017;
   fWeightMatrix0to1[10][6] = 0.0351294617750747;
   fWeightMatrix0to1[11][6] = 1.83906908539726;
   fWeightMatrix0to1[12][6] = -1.17662036409542;
   fWeightMatrix0to1[13][6] = -1.44545401261546;
   fWeightMatrix0to1[0][7] = -0.690809572309849;
   fWeightMatrix0to1[1][7] = 0.473875736365995;
   fWeightMatrix0to1[2][7] = -1.42503004286043;
   fWeightMatrix0to1[3][7] = -1.29003054357618;
   fWeightMatrix0to1[4][7] = 0.0885586924261145;
   fWeightMatrix0to1[5][7] = 2.50738984906868;
   fWeightMatrix0to1[6][7] = -0.854305918050725;
   fWeightMatrix0to1[7][7] = 0.876996364166183;
   fWeightMatrix0to1[8][7] = 0.504227724157738;
   fWeightMatrix0to1[9][7] = -0.898187422269874;
   fWeightMatrix0to1[10][7] = 0.174966073953308;
   fWeightMatrix0to1[11][7] = 0.708531332319482;
   fWeightMatrix0to1[12][7] = -1.03413378843052;
   fWeightMatrix0to1[13][7] = 0.226480619274444;
   fWeightMatrix0to1[0][8] = 0.520803553804601;
   fWeightMatrix0to1[1][8] = 0.394381930186729;
   fWeightMatrix0to1[2][8] = -1.42533518056922;
   fWeightMatrix0to1[3][8] = 2.00756084106157;
   fWeightMatrix0to1[4][8] = 0.490370031217933;
   fWeightMatrix0to1[5][8] = -0.555434487000657;
   fWeightMatrix0to1[6][8] = 0.727507014493989;
   fWeightMatrix0to1[7][8] = -0.784315260977442;
   fWeightMatrix0to1[8][8] = 0.0537502131929972;
   fWeightMatrix0to1[9][8] = 1.0597817722749;
   fWeightMatrix0to1[10][8] = -0.468811187841002;
   fWeightMatrix0to1[11][8] = 1.65470637894453;
   fWeightMatrix0to1[12][8] = 1.2988719282009;
   fWeightMatrix0to1[13][8] = -0.05263302084971;
   fWeightMatrix0to1[0][9] = -0.552844175108537;
   fWeightMatrix0to1[1][9] = 0.0645924532962916;
   fWeightMatrix0to1[2][9] = -1.18769289123384;
   fWeightMatrix0to1[3][9] = 1.22340384607788;
   fWeightMatrix0to1[4][9] = 0.312109368472709;
   fWeightMatrix0to1[5][9] = -1.41671229069913;
   fWeightMatrix0to1[6][9] = 0.550222703213652;
   fWeightMatrix0to1[7][9] = -0.727411085750121;
   fWeightMatrix0to1[8][9] = -0.674797761903935;
   fWeightMatrix0to1[9][9] = -0.0561847580521134;
   fWeightMatrix0to1[10][9] = 1.41917738453562;
   fWeightMatrix0to1[11][9] = -1.91414424812735;
   fWeightMatrix0to1[12][9] = 0.65199612818409;
   fWeightMatrix0to1[13][9] = 1.49936850786955;
   fWeightMatrix0to1[0][10] = 1.3847813699114;
   fWeightMatrix0to1[1][10] = 0.126529883280197;
   fWeightMatrix0to1[2][10] = -2.0511551457709;
   fWeightMatrix0to1[3][10] = -0.0429549784624116;
   fWeightMatrix0to1[4][10] = -1.71667762110197;
   fWeightMatrix0to1[5][10] = 0.985513642695934;
   fWeightMatrix0to1[6][10] = 1.13390729740983;
   fWeightMatrix0to1[7][10] = -1.11660058082772;
   fWeightMatrix0to1[8][10] = 0.177496913586032;
   fWeightMatrix0to1[9][10] = -4.48158541179988;
   fWeightMatrix0to1[10][10] = -1.42506290088512;
   fWeightMatrix0to1[11][10] = 0.383457699276516;
   fWeightMatrix0to1[12][10] = 2.697488498012;
   fWeightMatrix0to1[13][10] = -0.613437714499625;
   fWeightMatrix0to1[0][11] = -1.04912726203015;
   fWeightMatrix0to1[1][11] = 0.700841280680284;
   fWeightMatrix0to1[2][11] = 1.25207143473361;
   fWeightMatrix0to1[3][11] = 1.05957550061879;
   fWeightMatrix0to1[4][11] = 1.1965088930785;
   fWeightMatrix0to1[5][11] = -1.1462423691437;
   fWeightMatrix0to1[6][11] = 1.80892459277328;
   fWeightMatrix0to1[7][11] = 0.560149984541283;
   fWeightMatrix0to1[8][11] = 1.10869898513545;
   fWeightMatrix0to1[9][11] = -0.37405097608427;
   fWeightMatrix0to1[10][11] = 0.306310498234653;
   fWeightMatrix0to1[11][11] = -0.80047227443792;
   fWeightMatrix0to1[12][11] = -1.46963025932698;
   fWeightMatrix0to1[13][11] = 0.950752165219625;
   fWeightMatrix0to1[0][12] = -0.589318892708033;
   fWeightMatrix0to1[1][12] = -0.499319566501365;
   fWeightMatrix0to1[2][12] = 1.3362225267038;
   fWeightMatrix0to1[3][12] = 0.922812953161632;
   fWeightMatrix0to1[4][12] = -0.297087092368393;
   fWeightMatrix0to1[5][12] = 1.53133521279609;
   fWeightMatrix0to1[6][12] = 1.75016688688535;
   fWeightMatrix0to1[7][12] = -1.65043669177379;
   fWeightMatrix0to1[8][12] = 0.296223824496179;
   fWeightMatrix0to1[9][12] = -0.082983639024702;
   fWeightMatrix0to1[10][12] = 0.541858088004673;
   fWeightMatrix0to1[11][12] = -1.76225297101451;
   fWeightMatrix0to1[12][12] = -0.580171701297285;
   fWeightMatrix0to1[13][12] = 1.15637100198483;
   fWeightMatrix0to1[0][13] = 1.86033869222451;
   fWeightMatrix0to1[1][13] = -2.18996725978611;
   fWeightMatrix0to1[2][13] = -0.277263837803138;
   fWeightMatrix0to1[3][13] = -1.13179954658606;
   fWeightMatrix0to1[4][13] = -0.0521503147658404;
   fWeightMatrix0to1[5][13] = 1.43903388482087;
   fWeightMatrix0to1[6][13] = -0.677872176697582;
   fWeightMatrix0to1[7][13] = -0.514343798290813;
   fWeightMatrix0to1[8][13] = -1.77031746045215;
   fWeightMatrix0to1[9][13] = 2.63568333591524;
   fWeightMatrix0to1[10][13] = 2.53590065165386;
   fWeightMatrix0to1[11][13] = 1.30344301284178;
   fWeightMatrix0to1[12][13] = 1.19880825529035;
   fWeightMatrix0to1[13][13] = -0.668943536608627;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.182261022664692;
   fWeightMatrix1to2[1][0] = 0.922476272386804;
   fWeightMatrix1to2[2][0] = 1.12675705167712;
   fWeightMatrix1to2[3][0] = -1.16357817309866;
   fWeightMatrix1to2[4][0] = -2.19972509148618;
   fWeightMatrix1to2[5][0] = 0.192408945150685;
   fWeightMatrix1to2[6][0] = 0.0981157238195975;
   fWeightMatrix1to2[7][0] = -2.12886543835844;
   fWeightMatrix1to2[8][0] = 1.28620136254995;
   fWeightMatrix1to2[9][0] = 0.31557926547051;
   fWeightMatrix1to2[10][0] = -0.160199273980982;
   fWeightMatrix1to2[11][0] = -0.123241884483029;
   fWeightMatrix1to2[12][0] = 1.53885544713375;
   fWeightMatrix1to2[0][1] = 0.759004741071672;
   fWeightMatrix1to2[1][1] = 0.280103521310661;
   fWeightMatrix1to2[2][1] = -0.146645302340845;
   fWeightMatrix1to2[3][1] = -1.77135610813585;
   fWeightMatrix1to2[4][1] = -1.17905364985022;
   fWeightMatrix1to2[5][1] = 1.49427225892304;
   fWeightMatrix1to2[6][1] = 1.46757440362346;
   fWeightMatrix1to2[7][1] = 0.972356936312103;
   fWeightMatrix1to2[8][1] = 0.260737518596346;
   fWeightMatrix1to2[9][1] = 1.53510696523588;
   fWeightMatrix1to2[10][1] = -2.08933136373557;
   fWeightMatrix1to2[11][1] = -1.31115918114904;
   fWeightMatrix1to2[12][1] = -0.213746582303418;
   fWeightMatrix1to2[0][2] = -1.69114239619744;
   fWeightMatrix1to2[1][2] = 1.12119445886232;
   fWeightMatrix1to2[2][2] = 1.73869876237757;
   fWeightMatrix1to2[3][2] = -1.49689178264706;
   fWeightMatrix1to2[4][2] = 0.69504247677331;
   fWeightMatrix1to2[5][2] = -0.0925386367629429;
   fWeightMatrix1to2[6][2] = -1.55962784074649;
   fWeightMatrix1to2[7][2] = -0.935303450771604;
   fWeightMatrix1to2[8][2] = 0.960003883066613;
   fWeightMatrix1to2[9][2] = 0.393424822010803;
   fWeightMatrix1to2[10][2] = 0.82391283250411;
   fWeightMatrix1to2[11][2] = -1.17380423749281;
   fWeightMatrix1to2[12][2] = 1.81673730303056;
   fWeightMatrix1to2[0][3] = -2.15798353175292;
   fWeightMatrix1to2[1][3] = 0.574772234614562;
   fWeightMatrix1to2[2][3] = 0.0732445833328404;
   fWeightMatrix1to2[3][3] = -1.79433597807161;
   fWeightMatrix1to2[4][3] = -1.32247101007699;
   fWeightMatrix1to2[5][3] = -2.07186004721868;
   fWeightMatrix1to2[6][3] = -0.211657767538526;
   fWeightMatrix1to2[7][3] = -1.65220840474033;
   fWeightMatrix1to2[8][3] = -1.51008633830099;
   fWeightMatrix1to2[9][3] = -2.01367563667201;
   fWeightMatrix1to2[10][3] = 0.052165100236312;
   fWeightMatrix1to2[11][3] = -1.02102985477341;
   fWeightMatrix1to2[12][3] = -1.70364669292571;
   fWeightMatrix1to2[0][4] = 1.28661664057196;
   fWeightMatrix1to2[1][4] = -1.08296158784679;
   fWeightMatrix1to2[2][4] = 0.031514526627644;
   fWeightMatrix1to2[3][4] = -0.939562770637817;
   fWeightMatrix1to2[4][4] = 0.68473549665974;
   fWeightMatrix1to2[5][4] = 1.57298136434904;
   fWeightMatrix1to2[6][4] = 1.44935213703073;
   fWeightMatrix1to2[7][4] = -0.621147719133044;
   fWeightMatrix1to2[8][4] = -1.66672865852117;
   fWeightMatrix1to2[9][4] = -1.33637221774151;
   fWeightMatrix1to2[10][4] = -1.23836461001821;
   fWeightMatrix1to2[11][4] = -1.62603260491214;
   fWeightMatrix1to2[12][4] = 0.251058110368406;
   fWeightMatrix1to2[0][5] = 2.30689478639691;
   fWeightMatrix1to2[1][5] = 1.89989725653119;
   fWeightMatrix1to2[2][5] = -0.511383247938792;
   fWeightMatrix1to2[3][5] = 0.392446136671777;
   fWeightMatrix1to2[4][5] = -2.13629274338385;
   fWeightMatrix1to2[5][5] = -1.69065304068148;
   fWeightMatrix1to2[6][5] = 1.0261165181996;
   fWeightMatrix1to2[7][5] = 0.829055296977315;
   fWeightMatrix1to2[8][5] = -0.868501719944107;
   fWeightMatrix1to2[9][5] = -0.737928467652731;
   fWeightMatrix1to2[10][5] = 0.742880247143181;
   fWeightMatrix1to2[11][5] = 1.22901139970236;
   fWeightMatrix1to2[12][5] = 0.544346448710628;
   fWeightMatrix1to2[0][6] = -0.782297155056152;
   fWeightMatrix1to2[1][6] = -0.574720858760142;
   fWeightMatrix1to2[2][6] = 1.43615896114579;
   fWeightMatrix1to2[3][6] = 1.06104615677238;
   fWeightMatrix1to2[4][6] = 0.857991409094471;
   fWeightMatrix1to2[5][6] = -0.471414304135321;
   fWeightMatrix1to2[6][6] = 0.449548652955558;
   fWeightMatrix1to2[7][6] = 0.0807401009062733;
   fWeightMatrix1to2[8][6] = -1.39972857002114;
   fWeightMatrix1to2[9][6] = -0.886060573532794;
   fWeightMatrix1to2[10][6] = -1.85457426541392;
   fWeightMatrix1to2[11][6] = -1.37851642586164;
   fWeightMatrix1to2[12][6] = -1.62644296358414;
   fWeightMatrix1to2[0][7] = 1.51694910939337;
   fWeightMatrix1to2[1][7] = -1.67198475278996;
   fWeightMatrix1to2[2][7] = 2.23103864494653;
   fWeightMatrix1to2[3][7] = -1.35749512313069;
   fWeightMatrix1to2[4][7] = 1.80497420957836;
   fWeightMatrix1to2[5][7] = -1.32594122118925;
   fWeightMatrix1to2[6][7] = 0.664204443709874;
   fWeightMatrix1to2[7][7] = 1.13970357466416;
   fWeightMatrix1to2[8][7] = -1.96488670183747;
   fWeightMatrix1to2[9][7] = -0.0741141586700138;
   fWeightMatrix1to2[10][7] = 0.203743690824142;
   fWeightMatrix1to2[11][7] = -1.94470471787999;
   fWeightMatrix1to2[12][7] = -1.35876108024112;
   fWeightMatrix1to2[0][8] = -3.16163470218094;
   fWeightMatrix1to2[1][8] = -0.689757239926365;
   fWeightMatrix1to2[2][8] = 1.82819193430766;
   fWeightMatrix1to2[3][8] = -0.532792920558812;
   fWeightMatrix1to2[4][8] = 1.30439194860844;
   fWeightMatrix1to2[5][8] = -0.956455608106269;
   fWeightMatrix1to2[6][8] = -0.962283360976267;
   fWeightMatrix1to2[7][8] = -1.11260981424004;
   fWeightMatrix1to2[8][8] = -0.927117855006031;
   fWeightMatrix1to2[9][8] = -1.07035073177671;
   fWeightMatrix1to2[10][8] = 0.596084153515922;
   fWeightMatrix1to2[11][8] = -1.33972857899783;
   fWeightMatrix1to2[12][8] = -1.12189067598054;
   fWeightMatrix1to2[0][9] = 2.38940993852414;
   fWeightMatrix1to2[1][9] = 0.317379941049441;
   fWeightMatrix1to2[2][9] = 0.313044344578565;
   fWeightMatrix1to2[3][9] = 2.06653146484902;
   fWeightMatrix1to2[4][9] = -2.64526357214976;
   fWeightMatrix1to2[5][9] = 1.37057344930081;
   fWeightMatrix1to2[6][9] = 1.17190165481795;
   fWeightMatrix1to2[7][9] = -1.04427542550981;
   fWeightMatrix1to2[8][9] = -1.02487939770394;
   fWeightMatrix1to2[9][9] = -0.19256604825337;
   fWeightMatrix1to2[10][9] = -0.960235992003607;
   fWeightMatrix1to2[11][9] = 0.487642309673084;
   fWeightMatrix1to2[12][9] = 1.82483378965932;
   fWeightMatrix1to2[0][10] = 1.45081842669289;
   fWeightMatrix1to2[1][10] = 1.67080775263478;
   fWeightMatrix1to2[2][10] = -1.62129258540219;
   fWeightMatrix1to2[3][10] = 0.937193815157536;
   fWeightMatrix1to2[4][10] = -1.43375370220455;
   fWeightMatrix1to2[5][10] = 0.85485867776199;
   fWeightMatrix1to2[6][10] = -1.85861287093244;
   fWeightMatrix1to2[7][10] = -2.00783191318916;
   fWeightMatrix1to2[8][10] = -0.12745741499454;
   fWeightMatrix1to2[9][10] = 1.7878589132651;
   fWeightMatrix1to2[10][10] = 0.84512259553289;
   fWeightMatrix1to2[11][10] = 1.05719891082088;
   fWeightMatrix1to2[12][10] = 0.350752870521481;
   fWeightMatrix1to2[0][11] = 0.0644796142211956;
   fWeightMatrix1to2[1][11] = -0.459261733636527;
   fWeightMatrix1to2[2][11] = 0.119730300456952;
   fWeightMatrix1to2[3][11] = 1.71936918002014;
   fWeightMatrix1to2[4][11] = -1.66106427328655;
   fWeightMatrix1to2[5][11] = 0.553459697549008;
   fWeightMatrix1to2[6][11] = -1.56318274822904;
   fWeightMatrix1to2[7][11] = -0.656570180959093;
   fWeightMatrix1to2[8][11] = 0.183748920240128;
   fWeightMatrix1to2[9][11] = 0.417319217522217;
   fWeightMatrix1to2[10][11] = -0.806729150063026;
   fWeightMatrix1to2[11][11] = 0.974183158124426;
   fWeightMatrix1to2[12][11] = 1.77094051270317;
   fWeightMatrix1to2[0][12] = 2.15550352264664;
   fWeightMatrix1to2[1][12] = -0.349328036331251;
   fWeightMatrix1to2[2][12] = -1.06141841419359;
   fWeightMatrix1to2[3][12] = -1.6343473723872;
   fWeightMatrix1to2[4][12] = -1.86982278358308;
   fWeightMatrix1to2[5][12] = 1.17530149566269;
   fWeightMatrix1to2[6][12] = -0.585832209331895;
   fWeightMatrix1to2[7][12] = -1.35500791177122;
   fWeightMatrix1to2[8][12] = 0.585530043637851;
   fWeightMatrix1to2[9][12] = -1.56134922865152;
   fWeightMatrix1to2[10][12] = -0.760916250573094;
   fWeightMatrix1to2[11][12] = -1.62509599879489;
   fWeightMatrix1to2[12][12] = 0.902436832358639;
   fWeightMatrix1to2[0][13] = -1.67598535792668;
   fWeightMatrix1to2[1][13] = -1.98549972293844;
   fWeightMatrix1to2[2][13] = -0.599861087436291;
   fWeightMatrix1to2[3][13] = -0.789657023320053;
   fWeightMatrix1to2[4][13] = -1.78274330896224;
   fWeightMatrix1to2[5][13] = 0.952459173571288;
   fWeightMatrix1to2[6][13] = -1.3042576452992;
   fWeightMatrix1to2[7][13] = -1.00095642893503;
   fWeightMatrix1to2[8][13] = 1.77541029110277;
   fWeightMatrix1to2[9][13] = 0.28270798259406;
   fWeightMatrix1to2[10][13] = 0.22997422598946;
   fWeightMatrix1to2[11][13] = 0.107065040521661;
   fWeightMatrix1to2[12][13] = 1.24673551524949;
   fWeightMatrix1to2[0][14] = 1.99768420792333;
   fWeightMatrix1to2[1][14] = 0.775353691683197;
   fWeightMatrix1to2[2][14] = -0.928464403532281;
   fWeightMatrix1to2[3][14] = -0.78138075355606;
   fWeightMatrix1to2[4][14] = -1.60506771637796;
   fWeightMatrix1to2[5][14] = 1.1342500822461;
   fWeightMatrix1to2[6][14] = 0.707193172545106;
   fWeightMatrix1to2[7][14] = -0.182833594276917;
   fWeightMatrix1to2[8][14] = 1.0336741890093;
   fWeightMatrix1to2[9][14] = 1.27946061139602;
   fWeightMatrix1to2[10][14] = 2.01088994805562;
   fWeightMatrix1to2[11][14] = -1.34651444664927;
   fWeightMatrix1to2[12][14] = 1.8396708951501;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.607135897462533;
   fWeightMatrix2to3[0][1] = -1.94895016276557;
   fWeightMatrix2to3[0][2] = -0.671043605335845;
   fWeightMatrix2to3[0][3] = 0.0178583641562498;
   fWeightMatrix2to3[0][4] = 0.376722549757042;
   fWeightMatrix2to3[0][5] = -0.017171008623593;
   fWeightMatrix2to3[0][6] = 0.00123365315685265;
   fWeightMatrix2to3[0][7] = 0.0151127134548636;
   fWeightMatrix2to3[0][8] = -0.306389178091492;
   fWeightMatrix2to3[0][9] = 0.0135256554580756;
   fWeightMatrix2to3[0][10] = 1.26364515918495;
   fWeightMatrix2to3[0][11] = -0.0609394361071687;
   fWeightMatrix2to3[0][12] = -1.21197861267401;
   fWeightMatrix2to3[0][13] = 1.58204885496422;
}

inline double ReadMLP3_B::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP3_B::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP3_B::Clear() 
{
   // nothing to clear
}
inline double ReadMLP3_B::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
