// Class: ReadMLP2_25_B
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Fri Aug  7 11:08:21 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 19206


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,12.5105209351]
ClusterParameters.end         ClusterParameters.end             'F'    [1.55608689785,36.1423797607]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,29.1968593597]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.961471557617]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.177515119314,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.0286866668612,0.999999940395]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999999523163]
ClusterParameters.Width       ClusterParameters.Width           'F'    [1.18911576271,22.9364185333]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.0441980548203,0.915699660778]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,174]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [130.01272583,1495418.375]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-10.4672365189,27.7816944122]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP2_25_B : public IClassifierReader {

 public:

   // constructor
   ReadMLP2_25_B( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP2_25_B" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 12.5105209350586;
      fVmin[1] = 1.55608689785004;
      fVmax[1] = 36.1423797607422;
      fVmin[2] = 0;
      fVmax[2] = 29.1968593597412;
      fVmin[3] = 0;
      fVmax[3] = 0.961471557617188;
      fVmin[4] = 0;
      fVmax[4] = 1;
      fVmin[5] = 0.177515119314194;
      fVmax[5] = 1;
      fVmin[6] = 0.0286866668611765;
      fVmax[6] = 0.999999940395355;
      fVmin[7] = 0;
      fVmax[7] = 0.999999523162842;
      fVmin[8] = 1.18911576271057;
      fVmax[8] = 22.9364185333252;
      fVmin[9] = 0.0441980548202991;
      fVmax[9] = 0.915699660778046;
      fVmin[10] = 5;
      fVmax[10] = 174;
      fVmin[11] = 130.012725830078;
      fVmax[11] = 1495418.375;
      fVmin[12] = -10.4672365188599;
      fVmax[12] = 27.7816944122314;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP2_25_B() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP2_25_B::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.352170223604744;
   fWeightMatrix0to1[1][0] = 1.71437035472249;
   fWeightMatrix0to1[2][0] = -0.295004446659918;
   fWeightMatrix0to1[3][0] = 1.43600694984519;
   fWeightMatrix0to1[4][0] = -2.56837940830037;
   fWeightMatrix0to1[5][0] = -1.02770935267462;
   fWeightMatrix0to1[6][0] = -0.604225094330603;
   fWeightMatrix0to1[7][0] = 1.98821435398133;
   fWeightMatrix0to1[8][0] = -2.13404108385311;
   fWeightMatrix0to1[9][0] = -0.599333476741468;
   fWeightMatrix0to1[10][0] = -1.48646505298515;
   fWeightMatrix0to1[11][0] = -0.511561357204363;
   fWeightMatrix0to1[12][0] = -0.311935645172997;
   fWeightMatrix0to1[13][0] = -0.331474257770673;
   fWeightMatrix0to1[0][1] = 0.757281396771414;
   fWeightMatrix0to1[1][1] = 0.505723801589135;
   fWeightMatrix0to1[2][1] = -1.31190579466788;
   fWeightMatrix0to1[3][1] = 1.66892186493072;
   fWeightMatrix0to1[4][1] = 0.672811873583071;
   fWeightMatrix0to1[5][1] = 1.67042796309174;
   fWeightMatrix0to1[6][1] = -0.229995160929404;
   fWeightMatrix0to1[7][1] = -0.824433792425643;
   fWeightMatrix0to1[8][1] = 2.20636966892698;
   fWeightMatrix0to1[9][1] = 0.586328312867294;
   fWeightMatrix0to1[10][1] = -0.874776186596931;
   fWeightMatrix0to1[11][1] = -0.405281861186774;
   fWeightMatrix0to1[12][1] = 1.41046962608123;
   fWeightMatrix0to1[13][1] = -1.32394856224008;
   fWeightMatrix0to1[0][2] = -0.667163826477435;
   fWeightMatrix0to1[1][2] = 0.125979599090497;
   fWeightMatrix0to1[2][2] = 0.322759239308398;
   fWeightMatrix0to1[3][2] = 1.51484549066192;
   fWeightMatrix0to1[4][2] = -0.638575008421645;
   fWeightMatrix0to1[5][2] = 0.113922484406029;
   fWeightMatrix0to1[6][2] = 0.232674646903665;
   fWeightMatrix0to1[7][2] = 0.121503283983343;
   fWeightMatrix0to1[8][2] = -0.720059682285511;
   fWeightMatrix0to1[9][2] = 1.3004298823268;
   fWeightMatrix0to1[10][2] = -1.07600933236498;
   fWeightMatrix0to1[11][2] = 0.919133381047077;
   fWeightMatrix0to1[12][2] = 2.80730586107112;
   fWeightMatrix0to1[13][2] = 1.43539228224982;
   fWeightMatrix0to1[0][3] = 2.15497764307452;
   fWeightMatrix0to1[1][3] = 1.64698574785275;
   fWeightMatrix0to1[2][3] = -1.15408393301723;
   fWeightMatrix0to1[3][3] = -1.77088661968705;
   fWeightMatrix0to1[4][3] = 0.638722608140438;
   fWeightMatrix0to1[5][3] = -0.0120518014967814;
   fWeightMatrix0to1[6][3] = 1.80486264873797;
   fWeightMatrix0to1[7][3] = 1.78011278520399;
   fWeightMatrix0to1[8][3] = 2.61201394142285;
   fWeightMatrix0to1[9][3] = -0.198018547959024;
   fWeightMatrix0to1[10][3] = -1.98429540792579;
   fWeightMatrix0to1[11][3] = 0.968105825035814;
   fWeightMatrix0to1[12][3] = -3.49711944594973;
   fWeightMatrix0to1[13][3] = -1.04239195114956;
   fWeightMatrix0to1[0][4] = -2.64928684153003;
   fWeightMatrix0to1[1][4] = -1.425954397921;
   fWeightMatrix0to1[2][4] = 1.87854181031121;
   fWeightMatrix0to1[3][4] = 0.232550513582907;
   fWeightMatrix0to1[4][4] = -0.97082464644214;
   fWeightMatrix0to1[5][4] = 0.222744312577958;
   fWeightMatrix0to1[6][4] = -0.104669320157174;
   fWeightMatrix0to1[7][4] = 0.62673186510846;
   fWeightMatrix0to1[8][4] = 3.28242644656572;
   fWeightMatrix0to1[9][4] = -0.674650675945401;
   fWeightMatrix0to1[10][4] = -0.0783396978133535;
   fWeightMatrix0to1[11][4] = -0.997114983962317;
   fWeightMatrix0to1[12][4] = -0.334747710549546;
   fWeightMatrix0to1[13][4] = -0.157027231224979;
   fWeightMatrix0to1[0][5] = -1.18058936694224;
   fWeightMatrix0to1[1][5] = -1.25277842758237;
   fWeightMatrix0to1[2][5] = 0.948025332275101;
   fWeightMatrix0to1[3][5] = 0.787842942580036;
   fWeightMatrix0to1[4][5] = 1.24674060629675;
   fWeightMatrix0to1[5][5] = -0.899351567415993;
   fWeightMatrix0to1[6][5] = -1.7856004893572;
   fWeightMatrix0to1[7][5] = -2.21793625459493;
   fWeightMatrix0to1[8][5] = 0.651207927293816;
   fWeightMatrix0to1[9][5] = -0.0439755510295888;
   fWeightMatrix0to1[10][5] = 1.96650498551638;
   fWeightMatrix0to1[11][5] = 0.928963353706939;
   fWeightMatrix0to1[12][5] = -0.357182167999045;
   fWeightMatrix0to1[13][5] = -0.0998835094311281;
   fWeightMatrix0to1[0][6] = -0.852291483544208;
   fWeightMatrix0to1[1][6] = -0.590351811140973;
   fWeightMatrix0to1[2][6] = 1.33037427242348;
   fWeightMatrix0to1[3][6] = -1.27832195243314;
   fWeightMatrix0to1[4][6] = -1.80606838668754;
   fWeightMatrix0to1[5][6] = -2.07196428394488;
   fWeightMatrix0to1[6][6] = -0.403764112201789;
   fWeightMatrix0to1[7][6] = -0.736309744233463;
   fWeightMatrix0to1[8][6] = 3.55824610265489;
   fWeightMatrix0to1[9][6] = -3.00774194103133;
   fWeightMatrix0to1[10][6] = -0.336347770685219;
   fWeightMatrix0to1[11][6] = 1.71914261488585;
   fWeightMatrix0to1[12][6] = -1.40129447161609;
   fWeightMatrix0to1[13][6] = -1.22885331887637;
   fWeightMatrix0to1[0][7] = -0.650009326132242;
   fWeightMatrix0to1[1][7] = 0.230290396836389;
   fWeightMatrix0to1[2][7] = -1.35770196959423;
   fWeightMatrix0to1[3][7] = -1.44494937677869;
   fWeightMatrix0to1[4][7] = 2.23083053875747;
   fWeightMatrix0to1[5][7] = 2.85876245691419;
   fWeightMatrix0to1[6][7] = -0.960386148429382;
   fWeightMatrix0to1[7][7] = 1.0857035063342;
   fWeightMatrix0to1[8][7] = 0.698467274974274;
   fWeightMatrix0to1[9][7] = -0.493535930603988;
   fWeightMatrix0to1[10][7] = -0.0981105978571314;
   fWeightMatrix0to1[11][7] = 0.379271057171551;
   fWeightMatrix0to1[12][7] = -2.52158981243366;
   fWeightMatrix0to1[13][7] = 0.186984829486702;
   fWeightMatrix0to1[0][8] = 0.986503604021452;
   fWeightMatrix0to1[1][8] = 0.332822423404905;
   fWeightMatrix0to1[2][8] = -1.3971198719446;
   fWeightMatrix0to1[3][8] = 2.08837776264879;
   fWeightMatrix0to1[4][8] = 0.502050059118085;
   fWeightMatrix0to1[5][8] = -0.449776806190298;
   fWeightMatrix0to1[6][8] = 0.641032585163575;
   fWeightMatrix0to1[7][8] = -0.888450313300339;
   fWeightMatrix0to1[8][8] = 0.411231444812317;
   fWeightMatrix0to1[9][8] = 0.117115465902309;
   fWeightMatrix0to1[10][8] = -0.320845322818373;
   fWeightMatrix0to1[11][8] = 1.5396822500961;
   fWeightMatrix0to1[12][8] = 0.917969998527555;
   fWeightMatrix0to1[13][8] = -0.680082981467495;
   fWeightMatrix0to1[0][9] = -0.0972171421078179;
   fWeightMatrix0to1[1][9] = 0.187752958137198;
   fWeightMatrix0to1[2][9] = -1.46341708143915;
   fWeightMatrix0to1[3][9] = 1.27235350500078;
   fWeightMatrix0to1[4][9] = 0.722621838734813;
   fWeightMatrix0to1[5][9] = -1.38462234884939;
   fWeightMatrix0to1[6][9] = 0.516166484778372;
   fWeightMatrix0to1[7][9] = -0.991053510916232;
   fWeightMatrix0to1[8][9] = 0.286152656589565;
   fWeightMatrix0to1[9][9] = 0.268343426705171;
   fWeightMatrix0to1[10][9] = 1.54315840710364;
   fWeightMatrix0to1[11][9] = -1.78972624081291;
   fWeightMatrix0to1[12][9] = 0.567425390256671;
   fWeightMatrix0to1[13][9] = 0.567057377102063;
   fWeightMatrix0to1[0][10] = 0.745109197473203;
   fWeightMatrix0to1[1][10] = 0.291339054743358;
   fWeightMatrix0to1[2][10] = -1.50175619878827;
   fWeightMatrix0to1[3][10] = -0.127383832232658;
   fWeightMatrix0to1[4][10] = -1.94681627602291;
   fWeightMatrix0to1[5][10] = 1.5495528677038;
   fWeightMatrix0to1[6][10] = 1.11783420434478;
   fWeightMatrix0to1[7][10] = -0.259310259513557;
   fWeightMatrix0to1[8][10] = -0.564415935774049;
   fWeightMatrix0to1[9][10] = -5.58002997729027;
   fWeightMatrix0to1[10][10] = -1.51045479477847;
   fWeightMatrix0to1[11][10] = 0.243243425096548;
   fWeightMatrix0to1[12][10] = 1.51900468792889;
   fWeightMatrix0to1[13][10] = -0.643297384398175;
   fWeightMatrix0to1[0][11] = -1.48597654052383;
   fWeightMatrix0to1[1][11] = 0.611088135069048;
   fWeightMatrix0to1[2][11] = 0.900951508743842;
   fWeightMatrix0to1[3][11] = 0.6983640753395;
   fWeightMatrix0to1[4][11] = 1.06957739404741;
   fWeightMatrix0to1[5][11] = -1.30985271801793;
   fWeightMatrix0to1[6][11] = 1.8371469771378;
   fWeightMatrix0to1[7][11] = 1.16278485188768;
   fWeightMatrix0to1[8][11] = 1.00564463529218;
   fWeightMatrix0to1[9][11] = 0.774443956285955;
   fWeightMatrix0to1[10][11] = 0.609329184419635;
   fWeightMatrix0to1[11][11] = -1.01508893278746;
   fWeightMatrix0to1[12][11] = -1.3008296924735;
   fWeightMatrix0to1[13][11] = 0.637062681491938;
   fWeightMatrix0to1[0][12] = -0.221423757942374;
   fWeightMatrix0to1[1][12] = -0.485358855000975;
   fWeightMatrix0to1[2][12] = 1.69448767743233;
   fWeightMatrix0to1[3][12] = 1.00199802649699;
   fWeightMatrix0to1[4][12] = -0.336876478335187;
   fWeightMatrix0to1[5][12] = 1.59420992777772;
   fWeightMatrix0to1[6][12] = 1.80223332491427;
   fWeightMatrix0to1[7][12] = -1.6353754565722;
   fWeightMatrix0to1[8][12] = 1.45267060091208;
   fWeightMatrix0to1[9][12] = -0.508491071626057;
   fWeightMatrix0to1[10][12] = 0.531781380949974;
   fWeightMatrix0to1[11][12] = -1.82833974267696;
   fWeightMatrix0to1[12][12] = -0.648088044656226;
   fWeightMatrix0to1[13][12] = 1.53840100027627;
   fWeightMatrix0to1[0][13] = 2.4778499483423;
   fWeightMatrix0to1[1][13] = -2.21176659081953;
   fWeightMatrix0to1[2][13] = -0.219768564925967;
   fWeightMatrix0to1[3][13] = -0.715313687811002;
   fWeightMatrix0to1[4][13] = 0.334649475198777;
   fWeightMatrix0to1[5][13] = 1.66977791029939;
   fWeightMatrix0to1[6][13] = -0.699146744335332;
   fWeightMatrix0to1[7][13] = -1.15053421752019;
   fWeightMatrix0to1[8][13] = -1.94591847803303;
   fWeightMatrix0to1[9][13] = 1.26678022103043;
   fWeightMatrix0to1[10][13] = 2.11810749875042;
   fWeightMatrix0to1[11][13] = 1.51952450821072;
   fWeightMatrix0to1[12][13] = 1.71175631465337;
   fWeightMatrix0to1[13][13] = -0.342106611893671;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.55090654805826;
   fWeightMatrix1to2[1][0] = 0.881366990491647;
   fWeightMatrix1to2[2][0] = 0.4660224051981;
   fWeightMatrix1to2[3][0] = -1.83019981944727;
   fWeightMatrix1to2[4][0] = -1.7292230710436;
   fWeightMatrix1to2[5][0] = 0.242366998496654;
   fWeightMatrix1to2[6][0] = 0.326634642193096;
   fWeightMatrix1to2[7][0] = -2.16958896653328;
   fWeightMatrix1to2[8][0] = 1.42927241117475;
   fWeightMatrix1to2[9][0] = 0.865679883573713;
   fWeightMatrix1to2[10][0] = -0.118931892733302;
   fWeightMatrix1to2[11][0] = 0.0185608159062067;
   fWeightMatrix1to2[12][0] = 1.54647616920719;
   fWeightMatrix1to2[0][1] = 1.17854120015815;
   fWeightMatrix1to2[1][1] = 0.245598575103326;
   fWeightMatrix1to2[2][1] = -0.0703873419373175;
   fWeightMatrix1to2[3][1] = -1.73370732758551;
   fWeightMatrix1to2[4][1] = -0.605541250518484;
   fWeightMatrix1to2[5][1] = 1.65758304410973;
   fWeightMatrix1to2[6][1] = 1.44972173551934;
   fWeightMatrix1to2[7][1] = 0.823546590777007;
   fWeightMatrix1to2[8][1] = 0.326819874149854;
   fWeightMatrix1to2[9][1] = 2.70544744030456;
   fWeightMatrix1to2[10][1] = -2.00122395997756;
   fWeightMatrix1to2[11][1] = -1.26221595329319;
   fWeightMatrix1to2[12][1] = -0.197715352126865;
   fWeightMatrix1to2[0][2] = -1.50335752811734;
   fWeightMatrix1to2[1][2] = 1.07363368228441;
   fWeightMatrix1to2[2][2] = 1.68766756011758;
   fWeightMatrix1to2[3][2] = -1.5794498978197;
   fWeightMatrix1to2[4][2] = 0.535172046622328;
   fWeightMatrix1to2[5][2] = 0.0707758998874073;
   fWeightMatrix1to2[6][2] = -1.67799050060557;
   fWeightMatrix1to2[7][2] = -0.857799793043689;
   fWeightMatrix1to2[8][2] = 1.002744233689;
   fWeightMatrix1to2[9][2] = 0.0163773213556847;
   fWeightMatrix1to2[10][2] = 0.764087183994604;
   fWeightMatrix1to2[11][2] = -1.19894786814065;
   fWeightMatrix1to2[12][2] = 1.74025501851424;
   fWeightMatrix1to2[0][3] = -1.64382459443124;
   fWeightMatrix1to2[1][3] = 0.586041180966726;
   fWeightMatrix1to2[2][3] = 0.13075889228264;
   fWeightMatrix1to2[3][3] = -1.62392164198409;
   fWeightMatrix1to2[4][3] = -0.5997246701277;
   fWeightMatrix1to2[5][3] = -1.88365227795623;
   fWeightMatrix1to2[6][3] = -0.308078690952899;
   fWeightMatrix1to2[7][3] = -1.81285778090058;
   fWeightMatrix1to2[8][3] = -1.40448326849082;
   fWeightMatrix1to2[9][3] = -1.27060557213149;
   fWeightMatrix1to2[10][3] = 0.116786617772255;
   fWeightMatrix1to2[11][3] = -0.934155828901564;
   fWeightMatrix1to2[12][3] = -1.63414616730134;
   fWeightMatrix1to2[0][4] = 0.735876171406557;
   fWeightMatrix1to2[1][4] = -0.664803280625236;
   fWeightMatrix1to2[2][4] = 0.106023498801103;
   fWeightMatrix1to2[3][4] = -0.13607903210104;
   fWeightMatrix1to2[4][4] = -1.52952904244287;
   fWeightMatrix1to2[5][4] = 1.86020152858563;
   fWeightMatrix1to2[6][4] = 1.34449088745148;
   fWeightMatrix1to2[7][4] = -0.972056268620731;
   fWeightMatrix1to2[8][4] = -1.63477532504287;
   fWeightMatrix1to2[9][4] = -0.879945661769978;
   fWeightMatrix1to2[10][4] = -0.933109007625769;
   fWeightMatrix1to2[11][4] = -1.79171240899922;
   fWeightMatrix1to2[12][4] = 0.349921526552713;
   fWeightMatrix1to2[0][5] = 0.511070891224528;
   fWeightMatrix1to2[1][5] = 1.99043930338957;
   fWeightMatrix1to2[2][5] = -0.760235588030286;
   fWeightMatrix1to2[3][5] = 0.51058564826787;
   fWeightMatrix1to2[4][5] = -1.92824791451241;
   fWeightMatrix1to2[5][5] = -1.94589120434539;
   fWeightMatrix1to2[6][5] = 1.10282021054857;
   fWeightMatrix1to2[7][5] = 1.17962359054053;
   fWeightMatrix1to2[8][5] = -1.01319814190341;
   fWeightMatrix1to2[9][5] = -1.27729936920004;
   fWeightMatrix1to2[10][5] = 0.784774871608613;
   fWeightMatrix1to2[11][5] = 1.04342970823992;
   fWeightMatrix1to2[12][5] = 0.524535962904965;
   fWeightMatrix1to2[0][6] = -0.315304312828267;
   fWeightMatrix1to2[1][6] = -0.545247192856313;
   fWeightMatrix1to2[2][6] = 1.51356244530663;
   fWeightMatrix1to2[3][6] = 1.11939340673832;
   fWeightMatrix1to2[4][6] = 1.3178487564992;
   fWeightMatrix1to2[5][6] = -0.358450446621868;
   fWeightMatrix1to2[6][6] = 0.365322045306665;
   fWeightMatrix1to2[7][6] = -0.237183681739947;
   fWeightMatrix1to2[8][6] = -1.33687229250083;
   fWeightMatrix1to2[9][6] = 0.272918447910092;
   fWeightMatrix1to2[10][6] = -2.04299445277358;
   fWeightMatrix1to2[11][6] = -1.34371660087467;
   fWeightMatrix1to2[12][6] = -1.61215615764278;
   fWeightMatrix1to2[0][7] = 1.88631119241336;
   fWeightMatrix1to2[1][7] = -1.8303654592875;
   fWeightMatrix1to2[2][7] = 1.90542060988798;
   fWeightMatrix1to2[3][7] = -1.31209243913061;
   fWeightMatrix1to2[4][7] = 0.825291752079902;
   fWeightMatrix1to2[5][7] = -1.14756281555444;
   fWeightMatrix1to2[6][7] = 0.472542621890047;
   fWeightMatrix1to2[7][7] = 0.87729169059533;
   fWeightMatrix1to2[8][7] = -1.67222758720342;
   fWeightMatrix1to2[9][7] = 0.6067426837612;
   fWeightMatrix1to2[10][7] = 0.177416144553179;
   fWeightMatrix1to2[11][7] = -1.95447173831663;
   fWeightMatrix1to2[12][7] = -1.47042434598475;
   fWeightMatrix1to2[0][8] = -1.80794950641451;
   fWeightMatrix1to2[1][8] = -0.735736159985064;
   fWeightMatrix1to2[2][8] = 1.71835430294773;
   fWeightMatrix1to2[3][8] = -0.870015483409922;
   fWeightMatrix1to2[4][8] = 2.99303089781362;
   fWeightMatrix1to2[5][8] = -0.868451076452581;
   fWeightMatrix1to2[6][8] = -1.13536689314075;
   fWeightMatrix1to2[7][8] = -1.09572383905057;
   fWeightMatrix1to2[8][8] = -0.770653907463098;
   fWeightMatrix1to2[9][8] = -0.890323233257134;
   fWeightMatrix1to2[10][8] = 0.535638254635422;
   fWeightMatrix1to2[11][8] = -1.41473926586423;
   fWeightMatrix1to2[12][8] = -1.17665447926896;
   fWeightMatrix1to2[0][9] = 1.89754279459362;
   fWeightMatrix1to2[1][9] = 0.235675502071277;
   fWeightMatrix1to2[2][9] = 0.157601787820841;
   fWeightMatrix1to2[3][9] = 2.00524602559718;
   fWeightMatrix1to2[4][9] = -4.13201899747209;
   fWeightMatrix1to2[5][9] = 1.29136873080601;
   fWeightMatrix1to2[6][9] = 1.10165240931528;
   fWeightMatrix1to2[7][9] = -1.15376973852475;
   fWeightMatrix1to2[8][9] = -0.303648796262746;
   fWeightMatrix1to2[9][9] = 0.58152456831937;
   fWeightMatrix1to2[10][9] = -1.11073645156393;
   fWeightMatrix1to2[11][9] = 0.515509438259476;
   fWeightMatrix1to2[12][9] = 1.83153442373192;
   fWeightMatrix1to2[0][10] = 1.18624665286656;
   fWeightMatrix1to2[1][10] = 1.80812391520146;
   fWeightMatrix1to2[2][10] = -1.4467593042617;
   fWeightMatrix1to2[3][10] = 0.632618526548133;
   fWeightMatrix1to2[4][10] = -2.12500031240255;
   fWeightMatrix1to2[5][10] = 0.658665141244421;
   fWeightMatrix1to2[6][10] = -1.79991326728354;
   fWeightMatrix1to2[7][10] = -1.82677095945605;
   fWeightMatrix1to2[8][10] = -0.190773935774562;
   fWeightMatrix1to2[9][10] = 0.556652991000549;
   fWeightMatrix1to2[10][10] = 0.707260279540018;
   fWeightMatrix1to2[11][10] = 1.02445949703401;
   fWeightMatrix1to2[12][10] = 0.337327175939218;
   fWeightMatrix1to2[0][11] = -0.290657925963617;
   fWeightMatrix1to2[1][11] = -0.507498700728531;
   fWeightMatrix1to2[2][11] = 0.0173718266776063;
   fWeightMatrix1to2[3][11] = 1.59852066475329;
   fWeightMatrix1to2[4][11] = -1.66255735039153;
   fWeightMatrix1to2[5][11] = 0.373803203591559;
   fWeightMatrix1to2[6][11] = -1.47794910751348;
   fWeightMatrix1to2[7][11] = -0.466802929501184;
   fWeightMatrix1to2[8][11] = -0.141885965582538;
   fWeightMatrix1to2[9][11] = -0.397869263666593;
   fWeightMatrix1to2[10][11] = -0.742897917574769;
   fWeightMatrix1to2[11][11] = 0.948052867828649;
   fWeightMatrix1to2[12][11] = 1.74073415390002;
   fWeightMatrix1to2[0][12] = 0.718602828657217;
   fWeightMatrix1to2[1][12] = -0.223289882216315;
   fWeightMatrix1to2[2][12] = -0.979605248027126;
   fWeightMatrix1to2[3][12] = -1.76878618349056;
   fWeightMatrix1to2[4][12] = -2.25486662351496;
   fWeightMatrix1to2[5][12] = 0.870371527174695;
   fWeightMatrix1to2[6][12] = -0.437303705386818;
   fWeightMatrix1to2[7][12] = -1.40364595429552;
   fWeightMatrix1to2[8][12] = 0.905623044549049;
   fWeightMatrix1to2[9][12] = -1.70107022351914;
   fWeightMatrix1to2[10][12] = -0.717606195303802;
   fWeightMatrix1to2[11][12] = -1.61198483264138;
   fWeightMatrix1to2[12][12] = 0.984993111803977;
   fWeightMatrix1to2[0][13] = -1.19641489184749;
   fWeightMatrix1to2[1][13] = -1.84211273133811;
   fWeightMatrix1to2[2][13] = -0.502248705140742;
   fWeightMatrix1to2[3][13] = -0.665406451391855;
   fWeightMatrix1to2[4][13] = -1.55732623186029;
   fWeightMatrix1to2[5][13] = 1.13302750516328;
   fWeightMatrix1to2[6][13] = -1.29310721044444;
   fWeightMatrix1to2[7][13] = -1.21742850052151;
   fWeightMatrix1to2[8][13] = 1.85806320066529;
   fWeightMatrix1to2[9][13] = 1.19077050042291;
   fWeightMatrix1to2[10][13] = 0.344127524648034;
   fWeightMatrix1to2[11][13] = 0.142419169004423;
   fWeightMatrix1to2[12][13] = 1.263593921635;
   fWeightMatrix1to2[0][14] = 1.57393183957123;
   fWeightMatrix1to2[1][14] = 0.743804060540844;
   fWeightMatrix1to2[2][14] = -1.00632053701717;
   fWeightMatrix1to2[3][14] = -0.851626326382639;
   fWeightMatrix1to2[4][14] = -2.06616358384597;
   fWeightMatrix1to2[5][14] = 0.976958290022356;
   fWeightMatrix1to2[6][14] = 0.806763739867871;
   fWeightMatrix1to2[7][14] = 0.0657561277058051;
   fWeightMatrix1to2[8][14] = 0.971586277141613;
   fWeightMatrix1to2[9][14] = 0.231906587119309;
   fWeightMatrix1to2[10][14] = 2.0710839386943;
   fWeightMatrix1to2[11][14] = -1.37719554267402;
   fWeightMatrix1to2[12][14] = 1.82537471656463;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.0415820048465592;
   fWeightMatrix2to3[0][1] = -2.00406843677404;
   fWeightMatrix2to3[0][2] = -0.386296977398821;
   fWeightMatrix2to3[0][3] = 0.0403373675286941;
   fWeightMatrix2to3[0][4] = 0.944737683530826;
   fWeightMatrix2to3[0][5] = 0.0156005229941841;
   fWeightMatrix2to3[0][6] = 0.000460778948844315;
   fWeightMatrix2to3[0][7] = 0.0279426599698029;
   fWeightMatrix2to3[0][8] = -0.016766973694544;
   fWeightMatrix2to3[0][9] = -0.010895641472715;
   fWeightMatrix2to3[0][10] = 1.17359603924048;
   fWeightMatrix2to3[0][11] = 0.14779986352327;
   fWeightMatrix2to3[0][12] = -1.26866333799963;
   fWeightMatrix2to3[0][13] = 1.52712338894376;
}

inline double ReadMLP2_25_B::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP2_25_B::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP2_25_B::Clear() 
{
   // nothing to clear
}
inline double ReadMLP2_25_B::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
