// Class: ReadMLP0_35_EC_1x1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Mon Aug 10 10:12:04 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 5579


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
ClusterParameters.start       ClusterParameters.start           'F'    [0,17.0874652863]
ClusterParameters.end         ClusterParameters.end             'F'    [1.42898857594,28.8517303467]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,21.2599811554]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,1]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.096879914403,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.614085555077,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.000381350546377,0.999971985817]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999971628189]
ClusterParameters.Width       ClusterParameters.Width           'F'    [0,36.9814491272]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0,0.930239200592]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [5,26]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [0,480113.125]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-1.07036209106,18.2654132843]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP0_35_EC_1x1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP0_35_EC_1x1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP0_35_EC_1x1" ),
        fStatusIsClean( true ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 17.0874652862549;
      fVmin[1] = 1.42898857593536;
      fVmax[1] = 28.8517303466797;
      fVmin[2] = 0;
      fVmax[2] = 21.2599811553955;
      fVmin[3] = 0;
      fVmax[3] = 1;
      fVmin[4] = 0.0968799144029617;
      fVmax[4] = 1;
      fVmin[5] = 0.614085555076599;
      fVmax[5] = 1;
      fVmin[6] = 0.00038135054637678;
      fVmax[6] = 0.999971985816956;
      fVmin[7] = 0;
      fVmax[7] = 0.999971628189087;
      fVmin[8] = 0;
      fVmax[8] = 36.9814491271973;
      fVmin[9] = 0;
      fVmax[9] = 0.930239200592041;
      fVmin[10] = 5;
      fVmax[10] = 26;
      fVmin[11] = 0;
      fVmax[11] = 480113.125;
      fVmin[12] = -1.07036209106445;
      fVmax[12] = 18.2654132843018;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP0_35_EC_1x1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[15][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][14];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP0_35_EC_1x1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.138433613867759;
   fWeightMatrix0to1[1][0] = 1.95017609079021;
   fWeightMatrix0to1[2][0] = 0.831094893263548;
   fWeightMatrix0to1[3][0] = 2.01864212700553;
   fWeightMatrix0to1[4][0] = -1.15791103660743;
   fWeightMatrix0to1[5][0] = -1.12212257594133;
   fWeightMatrix0to1[6][0] = -0.797656661164939;
   fWeightMatrix0to1[7][0] = 1.91574352708105;
   fWeightMatrix0to1[8][0] = -2.01380364015535;
   fWeightMatrix0to1[9][0] = -1.35417817539175;
   fWeightMatrix0to1[10][0] = -2.04704459556952;
   fWeightMatrix0to1[11][0] = -0.379324169806525;
   fWeightMatrix0to1[12][0] = -1.08527139572421;
   fWeightMatrix0to1[13][0] = -3.63359014565126;
   fWeightMatrix0to1[0][1] = -0.158559843472008;
   fWeightMatrix0to1[1][1] = 0.658618771122112;
   fWeightMatrix0to1[2][1] = -0.618541527732385;
   fWeightMatrix0to1[3][1] = 1.35768314744924;
   fWeightMatrix0to1[4][1] = 2.38872189825328;
   fWeightMatrix0to1[5][1] = 1.57450364026321;
   fWeightMatrix0to1[6][1] = -0.336138956216784;
   fWeightMatrix0to1[7][1] = -0.571462464471455;
   fWeightMatrix0to1[8][1] = 0.825450150009009;
   fWeightMatrix0to1[9][1] = -0.396779566204269;
   fWeightMatrix0to1[10][1] = -0.783496420776275;
   fWeightMatrix0to1[11][1] = 2.97770644600721;
   fWeightMatrix0to1[12][1] = -1.15823164920045;
   fWeightMatrix0to1[13][1] = 0.762437305928971;
   fWeightMatrix0to1[0][2] = -1.57613126799664;
   fWeightMatrix0to1[1][2] = 0.160858290811769;
   fWeightMatrix0to1[2][2] = -0.223354548948823;
   fWeightMatrix0to1[3][2] = 1.43265155010588;
   fWeightMatrix0to1[4][2] = 1.17420743880905;
   fWeightMatrix0to1[5][2] = 0.143498797078875;
   fWeightMatrix0to1[6][2] = 0.27257514352069;
   fWeightMatrix0to1[7][2] = -0.534069393565679;
   fWeightMatrix0to1[8][2] = -2.2546611891064;
   fWeightMatrix0to1[9][2] = 1.93885123443715;
   fWeightMatrix0to1[10][2] = -1.428932625004;
   fWeightMatrix0to1[11][2] = 1.83771013093197;
   fWeightMatrix0to1[12][2] = 1.3270511000551;
   fWeightMatrix0to1[13][2] = -0.879839885606136;
   fWeightMatrix0to1[0][3] = 1.46383174765377;
   fWeightMatrix0to1[1][3] = 1.09214097012657;
   fWeightMatrix0to1[2][3] = 0.0140326021170688;
   fWeightMatrix0to1[3][3] = -1.15482892940557;
   fWeightMatrix0to1[4][3] = -0.322141714694676;
   fWeightMatrix0to1[5][3] = 0.59428412352453;
   fWeightMatrix0to1[6][3] = 1.4056241904986;
   fWeightMatrix0to1[7][3] = 1.69363249699951;
   fWeightMatrix0to1[8][3] = 0.892367496300083;
   fWeightMatrix0to1[9][3] = 0.279954729046828;
   fWeightMatrix0to1[10][3] = -2.15710141799015;
   fWeightMatrix0to1[11][3] = 0.687169342725159;
   fWeightMatrix0to1[12][3] = -0.293740356905548;
   fWeightMatrix0to1[13][3] = -0.562768769080762;
   fWeightMatrix0to1[0][4] = -2.07853825173939;
   fWeightMatrix0to1[1][4] = -1.8678007147238;
   fWeightMatrix0to1[2][4] = 0.716837597801679;
   fWeightMatrix0to1[3][4] = 0.782282361265176;
   fWeightMatrix0to1[4][4] = -0.789569510343578;
   fWeightMatrix0to1[5][4] = 0.084605902334511;
   fWeightMatrix0to1[6][4] = -0.447434914423429;
   fWeightMatrix0to1[7][4] = 0.278773688481131;
   fWeightMatrix0to1[8][4] = 1.00457659982519;
   fWeightMatrix0to1[9][4] = -0.314141194534574;
   fWeightMatrix0to1[10][4] = 0.193042836720099;
   fWeightMatrix0to1[11][4] = 1.50490077219275;
   fWeightMatrix0to1[12][4] = -0.109264055359656;
   fWeightMatrix0to1[13][4] = -0.328759328479609;
   fWeightMatrix0to1[0][5] = -1.71284634456318;
   fWeightMatrix0to1[1][5] = -1.60787338370479;
   fWeightMatrix0to1[2][5] = -0.0229997556777918;
   fWeightMatrix0to1[3][5] = 1.06378371089196;
   fWeightMatrix0to1[4][5] = 1.7453214528077;
   fWeightMatrix0to1[5][5] = 0.0418082720652492;
   fWeightMatrix0to1[6][5] = -2.13533826915272;
   fWeightMatrix0to1[7][5] = -2.40494217949625;
   fWeightMatrix0to1[8][5] = 0.292626672231683;
   fWeightMatrix0to1[9][5] = 0.780921525716278;
   fWeightMatrix0to1[10][5] = 2.0549036655466;
   fWeightMatrix0to1[11][5] = 0.192662023848795;
   fWeightMatrix0to1[12][5] = -0.649154412105371;
   fWeightMatrix0to1[13][5] = -1.28084697938092;
   fWeightMatrix0to1[0][6] = -0.795473811559521;
   fWeightMatrix0to1[1][6] = -0.259994565748489;
   fWeightMatrix0to1[2][6] = -1.6342869055035;
   fWeightMatrix0to1[3][6] = -1.53251889111455;
   fWeightMatrix0to1[4][6] = -1.41371704742954;
   fWeightMatrix0to1[5][6] = -1.03910742093521;
   fWeightMatrix0to1[6][6] = -0.274925695412215;
   fWeightMatrix0to1[7][6] = -0.00653653971550064;
   fWeightMatrix0to1[8][6] = 0.634330311668538;
   fWeightMatrix0to1[9][6] = -4.30966061115273;
   fWeightMatrix0to1[10][6] = -0.868029547755021;
   fWeightMatrix0to1[11][6] = 1.34005484080955;
   fWeightMatrix0to1[12][6] = -1.9175792596962;
   fWeightMatrix0to1[13][6] = -0.500012101676828;
   fWeightMatrix0to1[0][7] = -0.737668745607965;
   fWeightMatrix0to1[1][7] = -0.01838203150896;
   fWeightMatrix0to1[2][7] = -2.0382162648557;
   fWeightMatrix0to1[3][7] = -1.74936693731533;
   fWeightMatrix0to1[4][7] = 1.64339032495007;
   fWeightMatrix0to1[5][7] = 0.638355592325514;
   fWeightMatrix0to1[6][7] = -1.26107817206229;
   fWeightMatrix0to1[7][7] = 1.10821151502025;
   fWeightMatrix0to1[8][7] = -0.190328211450055;
   fWeightMatrix0to1[9][7] = 0.0193249436708372;
   fWeightMatrix0to1[10][7] = -0.252805382588488;
   fWeightMatrix0to1[11][7] = 0.264352192662675;
   fWeightMatrix0to1[12][7] = -0.33753044719957;
   fWeightMatrix0to1[13][7] = -0.80150276338367;
   fWeightMatrix0to1[0][8] = 0.657326821939631;
   fWeightMatrix0to1[1][8] = 0.448377684520413;
   fWeightMatrix0to1[2][8] = -3.4297360946509;
   fWeightMatrix0to1[3][8] = 1.66325231254019;
   fWeightMatrix0to1[4][8] = 0.263729865193823;
   fWeightMatrix0to1[5][8] = -1.22991096448138;
   fWeightMatrix0to1[6][8] = 0.804294045470658;
   fWeightMatrix0to1[7][8] = -0.598164031535803;
   fWeightMatrix0to1[8][8] = -2.50816904640532;
   fWeightMatrix0to1[9][8] = -0.0988558435395639;
   fWeightMatrix0to1[10][8] = -0.387899999868917;
   fWeightMatrix0to1[11][8] = 2.61763001304015;
   fWeightMatrix0to1[12][8] = -0.0583377575597233;
   fWeightMatrix0to1[13][8] = 1.63091610270922;
   fWeightMatrix0to1[0][9] = -0.979376007496289;
   fWeightMatrix0to1[1][9] = 0.124951102128177;
   fWeightMatrix0to1[2][9] = -1.74231148797842;
   fWeightMatrix0to1[3][9] = 1.36759655670442;
   fWeightMatrix0to1[4][9] = -0.464842810251508;
   fWeightMatrix0to1[5][9] = -2.16418534240594;
   fWeightMatrix0to1[6][9] = 0.645573269365709;
   fWeightMatrix0to1[7][9] = -1.02550807949276;
   fWeightMatrix0to1[8][9] = 1.09185231726462;
   fWeightMatrix0to1[9][9] = 0.435712673185354;
   fWeightMatrix0to1[10][9] = 1.58071687234871;
   fWeightMatrix0to1[11][9] = -1.09118059418188;
   fWeightMatrix0to1[12][9] = -1.56491521966532;
   fWeightMatrix0to1[13][9] = 0.0815347895995131;
   fWeightMatrix0to1[0][10] = 2.13771893524179;
   fWeightMatrix0to1[1][10] = 0.145906713665629;
   fWeightMatrix0to1[2][10] = -0.554869762235058;
   fWeightMatrix0to1[3][10] = -0.691545821185324;
   fWeightMatrix0to1[4][10] = -1.97953890274371;
   fWeightMatrix0to1[5][10] = 2.35557850535047;
   fWeightMatrix0to1[6][10] = 1.25286567336213;
   fWeightMatrix0to1[7][10] = -0.198809710651372;
   fWeightMatrix0to1[8][10] = 0.11826497346711;
   fWeightMatrix0to1[9][10] = -0.803801400621024;
   fWeightMatrix0to1[10][10] = -1.00468514736471;
   fWeightMatrix0to1[11][10] = -0.46136956902227;
   fWeightMatrix0to1[12][10] = 4.66434914008518;
   fWeightMatrix0to1[13][10] = -0.893227638026357;
   fWeightMatrix0to1[0][11] = 0.357250685130908;
   fWeightMatrix0to1[1][11] = 0.234013972706698;
   fWeightMatrix0to1[2][11] = -0.693043091882687;
   fWeightMatrix0to1[3][11] = 0.648206032542744;
   fWeightMatrix0to1[4][11] = 0.340892624243706;
   fWeightMatrix0to1[5][11] = -1.67483597051642;
   fWeightMatrix0to1[6][11] = 1.49170356830308;
   fWeightMatrix0to1[7][11] = 1.41101266356636;
   fWeightMatrix0to1[8][11] = 0.504155786023581;
   fWeightMatrix0to1[9][11] = -0.80034871499818;
   fWeightMatrix0to1[10][11] = 1.16268829193136;
   fWeightMatrix0to1[11][11] = -0.159848855838817;
   fWeightMatrix0to1[12][11] = -2.18650853442104;
   fWeightMatrix0to1[13][11] = 0.502959075503697;
   fWeightMatrix0to1[0][12] = -0.373789717580375;
   fWeightMatrix0to1[1][12] = -0.634822979521203;
   fWeightMatrix0to1[2][12] = 1.00538462351897;
   fWeightMatrix0to1[3][12] = 0.777073389624044;
   fWeightMatrix0to1[4][12] = 0.0330133276640058;
   fWeightMatrix0to1[5][12] = 1.36079763181159;
   fWeightMatrix0to1[6][12] = 1.81479715477321;
   fWeightMatrix0to1[7][12] = -1.72423245130458;
   fWeightMatrix0to1[8][12] = 1.06017979361978;
   fWeightMatrix0to1[9][12] = -0.0511668902059757;
   fWeightMatrix0to1[10][12] = 0.627820912422145;
   fWeightMatrix0to1[11][12] = -0.940960067031367;
   fWeightMatrix0to1[12][12] = -1.05838843021426;
   fWeightMatrix0to1[13][12] = 1.71445283313367;
   fWeightMatrix0to1[0][13] = 0.882498696156616;
   fWeightMatrix0to1[1][13] = -1.56475272646269;
   fWeightMatrix0to1[2][13] = -0.753856965823616;
   fWeightMatrix0to1[3][13] = -0.974017840582722;
   fWeightMatrix0to1[4][13] = 1.19009048095086;
   fWeightMatrix0to1[5][13] = 2.04599973159175;
   fWeightMatrix0to1[6][13] = -0.230381649755517;
   fWeightMatrix0to1[7][13] = -1.13476208290939;
   fWeightMatrix0to1[8][13] = -2.19946387424511;
   fWeightMatrix0to1[9][13] = 1.80582178778793;
   fWeightMatrix0to1[10][13] = 1.58913482528527;
   fWeightMatrix0to1[11][13] = 1.08933015706256;
   fWeightMatrix0to1[12][13] = -0.441984998633901;
   fWeightMatrix0to1[13][13] = -0.303139874595254;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.97003502572072;
   fWeightMatrix1to2[1][0] = 0.523263089672508;
   fWeightMatrix1to2[2][0] = 0.461865319588875;
   fWeightMatrix1to2[3][0] = -1.45277223972313;
   fWeightMatrix1to2[4][0] = -0.76698900800559;
   fWeightMatrix1to2[5][0] = -0.307161171818982;
   fWeightMatrix1to2[6][0] = 0.391784689085773;
   fWeightMatrix1to2[7][0] = -1.49881009480779;
   fWeightMatrix1to2[8][0] = 1.01136022101004;
   fWeightMatrix1to2[9][0] = 1.74188393470741;
   fWeightMatrix1to2[10][0] = -0.529509092856444;
   fWeightMatrix1to2[11][0] = 0.0742826934786158;
   fWeightMatrix1to2[12][0] = 1.3667237808336;
   fWeightMatrix1to2[0][1] = 0.980629625364764;
   fWeightMatrix1to2[1][1] = -0.144064476134058;
   fWeightMatrix1to2[2][1] = 0.0713870462703749;
   fWeightMatrix1to2[3][1] = -2.02967774256368;
   fWeightMatrix1to2[4][1] = -1.10116313030923;
   fWeightMatrix1to2[5][1] = 1.36065615453279;
   fWeightMatrix1to2[6][1] = 1.50743663477976;
   fWeightMatrix1to2[7][1] = 0.849268684289961;
   fWeightMatrix1to2[8][1] = -0.0509320967726891;
   fWeightMatrix1to2[9][1] = 2.63452208957797;
   fWeightMatrix1to2[10][1] = -1.90163937150195;
   fWeightMatrix1to2[11][1] = -1.21137261856595;
   fWeightMatrix1to2[12][1] = -0.417151933344868;
   fWeightMatrix1to2[0][2] = -1.34520034591174;
   fWeightMatrix1to2[1][2] = 0.730344107425349;
   fWeightMatrix1to2[2][2] = 3.00673170730432;
   fWeightMatrix1to2[3][2] = -1.20614871754946;
   fWeightMatrix1to2[4][2] = -1.13754028336665;
   fWeightMatrix1to2[5][2] = 0.666983357808239;
   fWeightMatrix1to2[6][2] = -1.61493604517877;
   fWeightMatrix1to2[7][2] = -0.664649972032384;
   fWeightMatrix1to2[8][2] = 1.50147118870713;
   fWeightMatrix1to2[9][2] = -0.158304289438137;
   fWeightMatrix1to2[10][2] = 0.755555535734255;
   fWeightMatrix1to2[11][2] = -1.26678748422118;
   fWeightMatrix1to2[12][2] = 1.46066961821737;
   fWeightMatrix1to2[0][3] = -2.30933342258225;
   fWeightMatrix1to2[1][3] = 0.453741188931742;
   fWeightMatrix1to2[2][3] = 0.181610345747336;
   fWeightMatrix1to2[3][3] = -1.44496513056026;
   fWeightMatrix1to2[4][3] = -2.0052264821991;
   fWeightMatrix1to2[5][3] = -1.08388651280308;
   fWeightMatrix1to2[6][3] = -0.332671738248434;
   fWeightMatrix1to2[7][3] = -1.90862117490193;
   fWeightMatrix1to2[8][3] = -0.620639594953046;
   fWeightMatrix1to2[9][3] = -1.15191905976473;
   fWeightMatrix1to2[10][3] = 0.0223277653947003;
   fWeightMatrix1to2[11][3] = -1.0338074622993;
   fWeightMatrix1to2[12][3] = -1.87950390181242;
   fWeightMatrix1to2[0][4] = 1.48230871474877;
   fWeightMatrix1to2[1][4] = -0.399257198144805;
   fWeightMatrix1to2[2][4] = 1.32534440407467;
   fWeightMatrix1to2[3][4] = -1.01307131347045;
   fWeightMatrix1to2[4][4] = -2.12965187719229;
   fWeightMatrix1to2[5][4] = 2.47459617818551;
   fWeightMatrix1to2[6][4] = 0.640494431226356;
   fWeightMatrix1to2[7][4] = -1.31626557910078;
   fWeightMatrix1to2[8][4] = -1.64346771966559;
   fWeightMatrix1to2[9][4] = -1.29970351964203;
   fWeightMatrix1to2[10][4] = -0.526171275800352;
   fWeightMatrix1to2[11][4] = -1.67212838274253;
   fWeightMatrix1to2[12][4] = 0.623241149926232;
   fWeightMatrix1to2[0][5] = 0.298207467724607;
   fWeightMatrix1to2[1][5] = 1.9547589657916;
   fWeightMatrix1to2[2][5] = -0.704487471448389;
   fWeightMatrix1to2[3][5] = 0.360232454026382;
   fWeightMatrix1to2[4][5] = 1.22093170865232;
   fWeightMatrix1to2[5][5] = -2.28930107350708;
   fWeightMatrix1to2[6][5] = 0.635264417132667;
   fWeightMatrix1to2[7][5] = 1.08659210572985;
   fWeightMatrix1to2[8][5] = -1.1137537154927;
   fWeightMatrix1to2[9][5] = -1.31908105596654;
   fWeightMatrix1to2[10][5] = 0.972688918924292;
   fWeightMatrix1to2[11][5] = 1.11913846230227;
   fWeightMatrix1to2[12][5] = 0.664623088974925;
   fWeightMatrix1to2[0][6] = -0.536508509357902;
   fWeightMatrix1to2[1][6] = -0.890632972579298;
   fWeightMatrix1to2[2][6] = 1.68424595344241;
   fWeightMatrix1to2[3][6] = 0.914439873063819;
   fWeightMatrix1to2[4][6] = 0.812955496209407;
   fWeightMatrix1to2[5][6] = -0.698493833838181;
   fWeightMatrix1to2[6][6] = 0.404360959544051;
   fWeightMatrix1to2[7][6] = -0.198323661199428;
   fWeightMatrix1to2[8][6] = -1.70858562779517;
   fWeightMatrix1to2[9][6] = 1.18169639018781;
   fWeightMatrix1to2[10][6] = -2.05694490658799;
   fWeightMatrix1to2[11][6] = -1.27686725320188;
   fWeightMatrix1to2[12][6] = -1.82085220412098;
   fWeightMatrix1to2[0][7] = 1.6503517850854;
   fWeightMatrix1to2[1][7] = -2.13928419707005;
   fWeightMatrix1to2[2][7] = 2.18370725118722;
   fWeightMatrix1to2[3][7] = -1.65745564062929;
   fWeightMatrix1to2[4][7] = 0.965570464593427;
   fWeightMatrix1to2[5][7] = -1.43118710922045;
   fWeightMatrix1to2[6][7] = 0.566091283333206;
   fWeightMatrix1to2[7][7] = 0.967783378448648;
   fWeightMatrix1to2[8][7] = -1.83543051822602;
   fWeightMatrix1to2[9][7] = 0.489047110072992;
   fWeightMatrix1to2[10][7] = 0.421690241423892;
   fWeightMatrix1to2[11][7] = -1.89064042606936;
   fWeightMatrix1to2[12][7] = -1.46727620262127;
   fWeightMatrix1to2[0][8] = -1.48324238025624;
   fWeightMatrix1to2[1][8] = -0.736453065283618;
   fWeightMatrix1to2[2][8] = 1.85333231189863;
   fWeightMatrix1to2[3][8] = -0.667905892114561;
   fWeightMatrix1to2[4][8] = 2.00804131605995;
   fWeightMatrix1to2[5][8] = -1.95636892483278;
   fWeightMatrix1to2[6][8] = 0.137206877700497;
   fWeightMatrix1to2[7][8] = -1.24103765203027;
   fWeightMatrix1to2[8][8] = -1.41987861421112;
   fWeightMatrix1to2[9][8] = -1.21399826355441;
   fWeightMatrix1to2[10][8] = 0.887090906009269;
   fWeightMatrix1to2[11][8] = -1.35649893105296;
   fWeightMatrix1to2[12][8] = -0.948369166512764;
   fWeightMatrix1to2[0][9] = 1.49279633682175;
   fWeightMatrix1to2[1][9] = 0.254684645534723;
   fWeightMatrix1to2[2][9] = -0.253599965374026;
   fWeightMatrix1to2[3][9] = 1.87314007930795;
   fWeightMatrix1to2[4][9] = -1.25898926808109;
   fWeightMatrix1to2[5][9] = 1.52870228669186;
   fWeightMatrix1to2[6][9] = 0.0278250360278211;
   fWeightMatrix1to2[7][9] = -1.13025348481154;
   fWeightMatrix1to2[8][9] = -1.18967488500059;
   fWeightMatrix1to2[9][9] = 0.335905973679694;
   fWeightMatrix1to2[10][9] = -0.904129748041558;
   fWeightMatrix1to2[11][9] = 0.451549443011281;
   fWeightMatrix1to2[12][9] = 1.64997039066809;
   fWeightMatrix1to2[0][10] = 1.4651629049031;
   fWeightMatrix1to2[1][10] = 2.18113787766255;
   fWeightMatrix1to2[2][10] = -1.5941696962868;
   fWeightMatrix1to2[3][10] = 1.11831019915617;
   fWeightMatrix1to2[4][10] = -1.94088620512085;
   fWeightMatrix1to2[5][10] = 0.584847001486335;
   fWeightMatrix1to2[6][10] = -1.9040108969386;
   fWeightMatrix1to2[7][10] = -1.94895106948706;
   fWeightMatrix1to2[8][10] = 0.13197661288609;
   fWeightMatrix1to2[9][10] = 0.6124292368505;
   fWeightMatrix1to2[10][10] = 0.582131449170499;
   fWeightMatrix1to2[11][10] = 0.959416098352589;
   fWeightMatrix1to2[12][10] = 0.588208741605659;
   fWeightMatrix1to2[0][11] = -0.0623864453305446;
   fWeightMatrix1to2[1][11] = -0.153219536735356;
   fWeightMatrix1to2[2][11] = -1.28686351357094;
   fWeightMatrix1to2[3][11] = 1.81351514409207;
   fWeightMatrix1to2[4][11] = -2.49087393399616;
   fWeightMatrix1to2[5][11] = 0.98071491501904;
   fWeightMatrix1to2[6][11] = -1.43075961003276;
   fWeightMatrix1to2[7][11] = -0.573764666906366;
   fWeightMatrix1to2[8][11] = 1.76718633475572;
   fWeightMatrix1to2[9][11] = 0.0956241493786111;
   fWeightMatrix1to2[10][11] = -1.05848371654776;
   fWeightMatrix1to2[11][11] = 0.988093152347526;
   fWeightMatrix1to2[12][11] = 1.69318605159903;
   fWeightMatrix1to2[0][12] = 0.373608757311437;
   fWeightMatrix1to2[1][12] = -0.401843483615952;
   fWeightMatrix1to2[2][12] = -1.64883456952349;
   fWeightMatrix1to2[3][12] = -1.38720480454718;
   fWeightMatrix1to2[4][12] = -1.32559247095638;
   fWeightMatrix1to2[5][12] = 2.48195248700105;
   fWeightMatrix1to2[6][12] = -1.69215744838828;
   fWeightMatrix1to2[7][12] = -1.06116280868695;
   fWeightMatrix1to2[8][12] = 1.56751911012937;
   fWeightMatrix1to2[9][12] = -1.0570530914161;
   fWeightMatrix1to2[10][12] = -1.03249714485043;
   fWeightMatrix1to2[11][12] = -1.63147700010174;
   fWeightMatrix1to2[12][12] = 0.657797506425343;
   fWeightMatrix1to2[0][13] = -1.4273720741646;
   fWeightMatrix1to2[1][13] = -1.59888890301369;
   fWeightMatrix1to2[2][13] = -0.8606379583457;
   fWeightMatrix1to2[3][13] = -0.939213597373031;
   fWeightMatrix1to2[4][13] = -2.15501857866714;
   fWeightMatrix1to2[5][13] = 1.82442813608459;
   fWeightMatrix1to2[6][13] = -1.60010006059072;
   fWeightMatrix1to2[7][13] = -1.35010352494015;
   fWeightMatrix1to2[8][13] = 1.74283821436091;
   fWeightMatrix1to2[9][13] = 0.800901530614018;
   fWeightMatrix1to2[10][13] = 0.206604967583323;
   fWeightMatrix1to2[11][13] = 0.0569405867929689;
   fWeightMatrix1to2[12][13] = 1.11040297740414;
   fWeightMatrix1to2[0][14] = 1.7757765841757;
   fWeightMatrix1to2[1][14] = 1.13138140032803;
   fWeightMatrix1to2[2][14] = -1.15078646364991;
   fWeightMatrix1to2[3][14] = -0.610312225533728;
   fWeightMatrix1to2[4][14] = -1.55867293099967;
   fWeightMatrix1to2[5][14] = 1.26944929104076;
   fWeightMatrix1to2[6][14] = 0.756856911617542;
   fWeightMatrix1to2[7][14] = 0.00872082715332978;
   fWeightMatrix1to2[8][14] = 1.34486942254439;
   fWeightMatrix1to2[9][14] = 0.29796357484235;
   fWeightMatrix1to2[10][14] = 1.72491158903893;
   fWeightMatrix1to2[11][14] = -1.43975610164152;
   fWeightMatrix1to2[12][14] = 2.03494230817771;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.0781488466752887;
   fWeightMatrix2to3[0][1] = -1.83333172801913;
   fWeightMatrix2to3[0][2] = -0.959252007693756;
   fWeightMatrix2to3[0][3] = 0.047277347730896;
   fWeightMatrix2to3[0][4] = 0.646889953470806;
   fWeightMatrix2to3[0][5] = -0.330995000231151;
   fWeightMatrix2to3[0][6] = -0.211822208461164;
   fWeightMatrix2to3[0][7] = 0.00452810375060776;
   fWeightMatrix2to3[0][8] = -0.201204651482057;
   fWeightMatrix2to3[0][9] = 0.609776484301899;
   fWeightMatrix2to3[0][10] = 0.633954479540062;
   fWeightMatrix2to3[0][11] = -0.0737224934780227;
   fWeightMatrix2to3[0][12] = -0.832232460687624;
   fWeightMatrix2to3[0][13] = 1.57578238054696;
}

inline double ReadMLP0_35_EC_1x1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP0_35_EC_1x1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP0_35_EC_1x1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP0_35_EC_1x1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
