// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Thu Jul 16 17:13:03 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 50839


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
ClusterParameters.start       ClusterParameters.start           'F'    [0,11.2528982162]
ClusterParameters.end         ClusterParameters.end             'F'    [9.56640911102,37.4384040833]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,22.7046489716]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0.0100881867111,0.865555822849]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.779325067997,0.998850345612]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.894343554974,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.215171545744,0.999999940395]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999995172024]
ClusterParameters.Es3/ClusterParameters.Etot_g   ClusterParameters.Es3_D_ClusterParameters.Etot_g     'F'    [0,0.987814426422]
ClusterParameters.Width       ClusterParameters.Width           'F'    [8.811170578,27.2961177826]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.171093583107,0.821816027164]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [35,208]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [7974.98046875,908527.375]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-2.92332053185,21.9502944946]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fStatusIsClean( true ),
        fNvars( 14 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Es3/ClusterParameters.Etot_g", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 11.2528982162476;
      fVmin[1] = 9.56640911102295;
      fVmax[1] = 37.438404083252;
      fVmin[2] = 0;
      fVmax[2] = 22.7046489715576;
      fVmin[3] = 0.0100881867110729;
      fVmax[3] = 0.865555822849274;
      fVmin[4] = 0.779325067996979;
      fVmax[4] = 0.998850345611572;
      fVmin[5] = 0.894343554973602;
      fVmax[5] = 1;
      fVmin[6] = 0.215171545743942;
      fVmax[6] = 0.999999940395355;
      fVmin[7] = 0;
      fVmax[7] = 0.999995172023773;
      fVmin[8] = 0;
      fVmax[8] = 0.987814426422119;
      fVmin[9] = 8.81117057800293;
      fVmax[9] = 27.2961177825928;
      fVmin[10] = 0.171093583106995;
      fVmax[10] = 0.821816027164459;
      fVmin[11] = 35;
      fVmax[11] = 208;
      fVmin[12] = 7974.98046875;
      fVmax[12] = 908527.375;
      fVmin[13] = -2.92332053184509;
      fVmax[13] = 21.9502944946289;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[16][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[15][16];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][15];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 15; fWeights[2] = new double[15]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.345219640789524;
   fWeightMatrix0to1[1][0] = 1.95614978329633;
   fWeightMatrix0to1[2][0] = 0.892096631892991;
   fWeightMatrix0to1[3][0] = 1.72339457885414;
   fWeightMatrix0to1[4][0] = -2.22712585357102;
   fWeightMatrix0to1[5][0] = -1.5016447590923;
   fWeightMatrix0to1[6][0] = -0.830831313456822;
   fWeightMatrix0to1[7][0] = 1.93085839553008;
   fWeightMatrix0to1[8][0] = -1.40211063056508;
   fWeightMatrix0to1[9][0] = -1.0772470866456;
   fWeightMatrix0to1[10][0] = -1.55666751736647;
   fWeightMatrix0to1[11][0] = -0.121275438960154;
   fWeightMatrix0to1[12][0] = -1.28104074678657;
   fWeightMatrix0to1[13][0] = -0.465633487177035;
   fWeightMatrix0to1[14][0] = -0.647486903125743;
   fWeightMatrix0to1[0][1] = 0.742769313591148;
   fWeightMatrix0to1[1][1] = -0.537625168253925;
   fWeightMatrix0to1[2][1] = 1.72822860457645;
   fWeightMatrix0to1[3][1] = 0.199854312619133;
   fWeightMatrix0to1[4][1] = 1.34163794978216;
   fWeightMatrix0to1[5][1] = -0.324144534864203;
   fWeightMatrix0to1[6][1] = -0.635906073820295;
   fWeightMatrix0to1[7][1] = 0.667132269131214;
   fWeightMatrix0to1[8][1] = 0.129890864625279;
   fWeightMatrix0to1[9][1] = -1.12086798872762;
   fWeightMatrix0to1[10][1] = -0.211618725453135;
   fWeightMatrix0to1[11][1] = 1.49102024365569;
   fWeightMatrix0to1[12][1] = -1.08534042439612;
   fWeightMatrix0to1[13][1] = -1.87948859124863;
   fWeightMatrix0to1[14][1] = 0.186693242608566;
   fWeightMatrix0to1[0][2] = 0.702296492665218;
   fWeightMatrix0to1[1][2] = 1.68179267245462;
   fWeightMatrix0to1[2][2] = -0.345485960727897;
   fWeightMatrix0to1[3][2] = -0.263367616154642;
   fWeightMatrix0to1[4][2] = 0.26552050140051;
   fWeightMatrix0to1[5][2] = -0.257010434252381;
   fWeightMatrix0to1[6][2] = -1.24924768971982;
   fWeightMatrix0to1[7][2] = 1.70879836580085;
   fWeightMatrix0to1[8][2] = -1.15029659517458;
   fWeightMatrix0to1[9][2] = 1.23742463645459;
   fWeightMatrix0to1[10][2] = 1.31015523761626;
   fWeightMatrix0to1[11][2] = 0.93057969591;
   fWeightMatrix0to1[12][2] = 1.94471255379326;
   fWeightMatrix0to1[13][2] = 1.18639155834125;
   fWeightMatrix0to1[14][2] = -0.82262719037926;
   fWeightMatrix0to1[0][3] = -1.61353851375945;
   fWeightMatrix0to1[1][3] = 0.708682248184958;
   fWeightMatrix0to1[2][3] = 0.0454052770360772;
   fWeightMatrix0to1[3][3] = 1.31761526597771;
   fWeightMatrix0to1[4][3] = 1.45779179938246;
   fWeightMatrix0to1[5][3] = 1.60016091889843;
   fWeightMatrix0to1[6][3] = 1.50152153992997;
   fWeightMatrix0to1[7][3] = -1.67141340100951;
   fWeightMatrix0to1[8][3] = 1.35033538708464;
   fWeightMatrix0to1[9][3] = -1.60934026747598;
   fWeightMatrix0to1[10][3] = -0.907140499561534;
   fWeightMatrix0to1[11][3] = -1.375117078991;
   fWeightMatrix0to1[12][3] = -1.66390263461647;
   fWeightMatrix0to1[13][3] = 1.49060636840251;
   fWeightMatrix0to1[14][3] = 0.666964091710944;
   fWeightMatrix0to1[0][4] = -1.48833821802371;
   fWeightMatrix0to1[1][4] = 0.356191472280473;
   fWeightMatrix0to1[2][4] = -0.293039824332323;
   fWeightMatrix0to1[3][4] = 0.49128417412309;
   fWeightMatrix0to1[4][4] = 1.63485358413119;
   fWeightMatrix0to1[5][4] = -0.330690074871763;
   fWeightMatrix0to1[6][4] = 0.372197878896036;
   fWeightMatrix0to1[7][4] = -1.25906501000178;
   fWeightMatrix0to1[8][4] = 0.784837455774861;
   fWeightMatrix0to1[9][4] = -1.25762365418164;
   fWeightMatrix0to1[10][4] = -0.958894362921332;
   fWeightMatrix0to1[11][4] = -1.58103097743837;
   fWeightMatrix0to1[12][4] = 0.73658354722575;
   fWeightMatrix0to1[13][4] = 1.15792142162247;
   fWeightMatrix0to1[14][4] = 1.66375212735229;
   fWeightMatrix0to1[0][5] = -0.172297373324965;
   fWeightMatrix0to1[1][5] = -2.05074080078193;
   fWeightMatrix0to1[2][5] = -1.92771578566519;
   fWeightMatrix0to1[3][5] = 0.787967837525953;
   fWeightMatrix0to1[4][5] = 0.650693250487553;
   fWeightMatrix0to1[5][5] = 1.98058685366671;
   fWeightMatrix0to1[6][5] = 0.921361881058703;
   fWeightMatrix0to1[7][5] = 0.910611280827238;
   fWeightMatrix0to1[8][5] = -0.704766699007309;
   fWeightMatrix0to1[9][5] = -1.02924492221195;
   fWeightMatrix0to1[10][5] = -0.241988104371527;
   fWeightMatrix0to1[11][5] = 0.633039902679305;
   fWeightMatrix0to1[12][5] = -1.29241605125944;
   fWeightMatrix0to1[13][5] = -1.55283737162095;
   fWeightMatrix0to1[14][5] = -1.61164063916251;
   fWeightMatrix0to1[0][6] = 0.167737091151811;
   fWeightMatrix0to1[1][6] = -0.333957317107666;
   fWeightMatrix0to1[2][6] = 1.59353268864822;
   fWeightMatrix0to1[3][6] = -1.73467569657649;
   fWeightMatrix0to1[4][6] = -0.649796159527161;
   fWeightMatrix0to1[5][6] = 1.63337775698799;
   fWeightMatrix0to1[6][6] = -0.426471906237434;
   fWeightMatrix0to1[7][6] = -1.68124221413702;
   fWeightMatrix0to1[8][6] = -1.38244067467053;
   fWeightMatrix0to1[9][6] = 0.0685632260159429;
   fWeightMatrix0to1[10][6] = -2.03277969020089;
   fWeightMatrix0to1[11][6] = -1.99604623101815;
   fWeightMatrix0to1[12][6] = 0.677213361591086;
   fWeightMatrix0to1[13][6] = 1.71969484052247;
   fWeightMatrix0to1[14][6] = -1.0622768788602;
   fWeightMatrix0to1[0][7] = 1.62020981818375;
   fWeightMatrix0to1[1][7] = -0.93346911861866;
   fWeightMatrix0to1[2][7] = -0.790737600810492;
   fWeightMatrix0to1[3][7] = -0.0317777172527125;
   fWeightMatrix0to1[4][7] = 0.25426584075123;
   fWeightMatrix0to1[5][7] = -1.7655418814113;
   fWeightMatrix0to1[6][7] = 0.144163798403197;
   fWeightMatrix0to1[7][7] = 0.297539908211719;
   fWeightMatrix0to1[8][7] = 0.389838451071795;
   fWeightMatrix0to1[9][7] = -1.59078725971947;
   fWeightMatrix0to1[10][7] = 1.53432122321408;
   fWeightMatrix0to1[11][7] = 0.203755398103842;
   fWeightMatrix0to1[12][7] = -0.900949751305545;
   fWeightMatrix0to1[13][7] = 0.797560169802378;
   fWeightMatrix0to1[14][7] = -0.697558048184077;
   fWeightMatrix0to1[0][8] = -1.61292911885524;
   fWeightMatrix0to1[1][8] = 0.163286775559435;
   fWeightMatrix0to1[2][8] = -0.319296910248518;
   fWeightMatrix0to1[3][8] = 2.17875231252126;
   fWeightMatrix0to1[4][8] = 0.610632926646755;
   fWeightMatrix0to1[5][8] = -0.00247534919459566;
   fWeightMatrix0to1[6][8] = -0.671761727226076;
   fWeightMatrix0to1[7][8] = 0.183438306066722;
   fWeightMatrix0to1[8][8] = -1.86536077623769;
   fWeightMatrix0to1[9][8] = 1.14388552690339;
   fWeightMatrix0to1[10][8] = 0.272367143906096;
   fWeightMatrix0to1[11][8] = -1.43873092307059;
   fWeightMatrix0to1[12][8] = 0.753076381777411;
   fWeightMatrix0to1[13][8] = -1.47374865876547;
   fWeightMatrix0to1[14][8] = -0.0442165226113487;
   fWeightMatrix0to1[0][9] = 1.12048829648427;
   fWeightMatrix0to1[1][9] = 1.76798462327495;
   fWeightMatrix0to1[2][9] = -1.88147788882624;
   fWeightMatrix0to1[3][9] = 0.44500280064188;
   fWeightMatrix0to1[4][9] = 1.65498104110272;
   fWeightMatrix0to1[5][9] = 1.5899921328525;
   fWeightMatrix0to1[6][9] = 0.0518184522819663;
   fWeightMatrix0to1[7][9] = -1.41663935691933;
   fWeightMatrix0to1[8][9] = -0.183291520192968;
   fWeightMatrix0to1[9][9] = -1.34423131604093;
   fWeightMatrix0to1[10][9] = 1.71967373595523;
   fWeightMatrix0to1[11][9] = 1.30231800543486;
   fWeightMatrix0to1[12][9] = -0.485272656991436;
   fWeightMatrix0to1[13][9] = -0.410376694743997;
   fWeightMatrix0to1[14][9] = 0.000109099209682099;
   fWeightMatrix0to1[0][10] = -1.42846429175325;
   fWeightMatrix0to1[1][10] = 0.686547875492702;
   fWeightMatrix0to1[2][10] = 1.73083784146728;
   fWeightMatrix0to1[3][10] = -0.633831908525938;
   fWeightMatrix0to1[4][10] = -0.480159817060152;
   fWeightMatrix0to1[5][10] = 0.288480228209232;
   fWeightMatrix0to1[6][10] = 1.00204595900675;
   fWeightMatrix0to1[7][10] = 0.616906247632399;
   fWeightMatrix0to1[8][10] = 0.922721990616092;
   fWeightMatrix0to1[9][10] = -1.31559281292211;
   fWeightMatrix0to1[10][10] = 1.53960132865742;
   fWeightMatrix0to1[11][10] = 0.825649606227082;
   fWeightMatrix0to1[12][10] = 0.539630766907693;
   fWeightMatrix0to1[13][10] = 0.571396425886631;
   fWeightMatrix0to1[14][10] = 0.819264750473709;
   fWeightMatrix0to1[0][11] = -0.586702531469356;
   fWeightMatrix0to1[1][11] = -0.647508941249627;
   fWeightMatrix0to1[2][11] = 1.01397330804437;
   fWeightMatrix0to1[3][11] = -0.747799682293632;
   fWeightMatrix0to1[4][11] = -0.493507059491281;
   fWeightMatrix0to1[5][11] = 1.56310461982636;
   fWeightMatrix0to1[6][11] = 0.837288563967063;
   fWeightMatrix0to1[7][11] = -0.287491988183539;
   fWeightMatrix0to1[8][11] = 1.4898458223655;
   fWeightMatrix0to1[9][11] = 1.80021982723878;
   fWeightMatrix0to1[10][11] = -1.87497871573603;
   fWeightMatrix0to1[11][11] = 0.496813071758235;
   fWeightMatrix0to1[12][11] = -0.0626324499982846;
   fWeightMatrix0to1[13][11] = 0.48286157139118;
   fWeightMatrix0to1[14][11] = -1.66443432298152;
   fWeightMatrix0to1[0][12] = -1.61609687225923;
   fWeightMatrix0to1[1][12] = 1.15813836694603;
   fWeightMatrix0to1[2][12] = 1.79111901653104;
   fWeightMatrix0to1[3][12] = -1.41734271856823;
   fWeightMatrix0to1[4][12] = -0.357547310462157;
   fWeightMatrix0to1[5][12] = -0.596228372344189;
   fWeightMatrix0to1[6][12] = -0.0833468376853035;
   fWeightMatrix0to1[7][12] = 1.79761435380534;
   fWeightMatrix0to1[8][12] = -0.443129234210694;
   fWeightMatrix0to1[9][12] = -0.456406281959201;
   fWeightMatrix0to1[10][12] = -0.953959538222731;
   fWeightMatrix0to1[11][12] = 1.29122771758684;
   fWeightMatrix0to1[12][12] = 1.56684405696589;
   fWeightMatrix0to1[13][12] = 1.09547147914449;
   fWeightMatrix0to1[14][12] = 0.266447428375493;
   fWeightMatrix0to1[0][13] = -0.797766400362123;
   fWeightMatrix0to1[1][13] = -1.93962989259412;
   fWeightMatrix0to1[2][13] = 1.0819600824636;
   fWeightMatrix0to1[3][13] = 0.497502127538807;
   fWeightMatrix0to1[4][13] = -1.32034800104046;
   fWeightMatrix0to1[5][13] = -0.673571759412525;
   fWeightMatrix0to1[6][13] = 0.365461185799566;
   fWeightMatrix0to1[7][13] = 0.107215091310205;
   fWeightMatrix0to1[8][13] = -1.94919279037184;
   fWeightMatrix0to1[9][13] = 1.67583466190376;
   fWeightMatrix0to1[10][13] = 0.916870400152001;
   fWeightMatrix0to1[11][13] = -0.520564756453308;
   fWeightMatrix0to1[12][13] = -0.0373621499962116;
   fWeightMatrix0to1[13][13] = 1.60881155603927;
   fWeightMatrix0to1[14][13] = 0.985720439144848;
   fWeightMatrix0to1[0][14] = 0.584966456993724;
   fWeightMatrix0to1[1][14] = -0.164785055195403;
   fWeightMatrix0to1[2][14] = -1.96729064066466;
   fWeightMatrix0to1[3][14] = -1.28511575639279;
   fWeightMatrix0to1[4][14] = 1.92495901689751;
   fWeightMatrix0to1[5][14] = 1.34313480715996;
   fWeightMatrix0to1[6][14] = 1.2231196259313;
   fWeightMatrix0to1[7][14] = 0.162641949754283;
   fWeightMatrix0to1[8][14] = 2.09636861840773;
   fWeightMatrix0to1[9][14] = -1.74996977962034;
   fWeightMatrix0to1[10][14] = -1.36428135695335;
   fWeightMatrix0to1[11][14] = -0.509897952874949;
   fWeightMatrix0to1[12][14] = -1.46084212632803;
   fWeightMatrix0to1[13][14] = 1.00604535162022;
   fWeightMatrix0to1[14][14] = 1.78433440039667;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.36799800992917;
   fWeightMatrix1to2[1][0] = 0.7067083819985;
   fWeightMatrix1to2[2][0] = -0.222375611480288;
   fWeightMatrix1to2[3][0] = -1.70736959650439;
   fWeightMatrix1to2[4][0] = -1.1979111565785;
   fWeightMatrix1to2[5][0] = 0.735537999250695;
   fWeightMatrix1to2[6][0] = -0.0263333389127592;
   fWeightMatrix1to2[7][0] = 0.803610383750885;
   fWeightMatrix1to2[8][0] = -1.16066881594375;
   fWeightMatrix1to2[9][0] = 1.60277057242855;
   fWeightMatrix1to2[10][0] = -1.79869651592182;
   fWeightMatrix1to2[11][0] = 0.839365644414391;
   fWeightMatrix1to2[12][0] = 0.131942165115307;
   fWeightMatrix1to2[13][0] = -1.52334848943441;
   fWeightMatrix1to2[0][1] = -1.21524378492639;
   fWeightMatrix1to2[1][1] = -1.96083996875162;
   fWeightMatrix1to2[2][1] = -0.3340120760183;
   fWeightMatrix1to2[3][1] = -1.88862505230061;
   fWeightMatrix1to2[4][1] = -1.3835368954491;
   fWeightMatrix1to2[5][1] = -1.51530429300566;
   fWeightMatrix1to2[6][1] = 0.0959135071479174;
   fWeightMatrix1to2[7][1] = -1.22416519484491;
   fWeightMatrix1to2[8][1] = -1.53986191711989;
   fWeightMatrix1to2[9][1] = 1.55504907145093;
   fWeightMatrix1to2[10][1] = -0.845356539228977;
   fWeightMatrix1to2[11][1] = 0.162562678133728;
   fWeightMatrix1to2[12][1] = -1.12751274233987;
   fWeightMatrix1to2[13][1] = 0.30722339045304;
   fWeightMatrix1to2[0][2] = 1.98337975392355;
   fWeightMatrix1to2[1][2] = 1.30538166436185;
   fWeightMatrix1to2[2][2] = -0.804275968468584;
   fWeightMatrix1to2[3][2] = -1.49849756329768;
   fWeightMatrix1to2[4][2] = -0.889619444641537;
   fWeightMatrix1to2[5][2] = -0.619208101133939;
   fWeightMatrix1to2[6][2] = -1.57193074945843;
   fWeightMatrix1to2[7][2] = 0.103100197310248;
   fWeightMatrix1to2[8][2] = 0.433343045142834;
   fWeightMatrix1to2[9][2] = 2.01001072629547;
   fWeightMatrix1to2[10][2] = -0.331899898343455;
   fWeightMatrix1to2[11][2] = 0.250837248425236;
   fWeightMatrix1to2[12][2] = -0.577768339224018;
   fWeightMatrix1to2[13][2] = -1.80759647292255;
   fWeightMatrix1to2[0][3] = 1.18670234980232;
   fWeightMatrix1to2[1][3] = 1.19098040508132;
   fWeightMatrix1to2[2][3] = -0.76465842003096;
   fWeightMatrix1to2[3][3] = -1.04689868452452;
   fWeightMatrix1to2[4][3] = 1.04580476732159;
   fWeightMatrix1to2[5][3] = 1.49137886276848;
   fWeightMatrix1to2[6][3] = 0.490710695993141;
   fWeightMatrix1to2[7][3] = -0.27549995343991;
   fWeightMatrix1to2[8][3] = -0.284502977878692;
   fWeightMatrix1to2[9][3] = 1.47309770888573;
   fWeightMatrix1to2[10][3] = 1.00335863359169;
   fWeightMatrix1to2[11][3] = 0.995293061888207;
   fWeightMatrix1to2[12][3] = -0.35577945131739;
   fWeightMatrix1to2[13][3] = 0.37633844729753;
   fWeightMatrix1to2[0][4] = -0.398995256991966;
   fWeightMatrix1to2[1][4] = -1.38978471516653;
   fWeightMatrix1to2[2][4] = -0.635430895038429;
   fWeightMatrix1to2[3][4] = -1.76537389535301;
   fWeightMatrix1to2[4][4] = -1.56024575163366;
   fWeightMatrix1to2[5][4] = -1.77242275913025;
   fWeightMatrix1to2[6][4] = 1.68759718022946;
   fWeightMatrix1to2[7][4] = -1.57679404991799;
   fWeightMatrix1to2[8][4] = 1.50725240725339;
   fWeightMatrix1to2[9][4] = -1.67644060710925;
   fWeightMatrix1to2[10][4] = 1.13180734622967;
   fWeightMatrix1to2[11][4] = -1.10396123963099;
   fWeightMatrix1to2[12][4] = 0.513221427175096;
   fWeightMatrix1to2[13][4] = 0.737129750488672;
   fWeightMatrix1to2[0][5] = -1.96918104480395;
   fWeightMatrix1to2[1][5] = 0.272413261971047;
   fWeightMatrix1to2[2][5] = 0.53456074038722;
   fWeightMatrix1to2[3][5] = -1.95430514955133;
   fWeightMatrix1to2[4][5] = -1.65950995096593;
   fWeightMatrix1to2[5][5] = -1.99983837770168;
   fWeightMatrix1to2[6][5] = -0.884911712805557;
   fWeightMatrix1to2[7][5] = 2.1164226480853;
   fWeightMatrix1to2[8][5] = -0.714353824248295;
   fWeightMatrix1to2[9][5] = 0.147605210917734;
   fWeightMatrix1to2[10][5] = -0.897390547191609;
   fWeightMatrix1to2[11][5] = -1.1934027191572;
   fWeightMatrix1to2[12][5] = -1.65539649037094;
   fWeightMatrix1to2[13][5] = -1.10511060775159;
   fWeightMatrix1to2[0][6] = -1.47466426714715;
   fWeightMatrix1to2[1][6] = 0.981050581123249;
   fWeightMatrix1to2[2][6] = -1.41868206593191;
   fWeightMatrix1to2[3][6] = -1.24361929854617;
   fWeightMatrix1to2[4][6] = 1.57439226291277;
   fWeightMatrix1to2[5][6] = 0.0110555376137068;
   fWeightMatrix1to2[6][6] = -0.550777060051003;
   fWeightMatrix1to2[7][6] = 2.04549400427927;
   fWeightMatrix1to2[8][6] = -1.93152307621656;
   fWeightMatrix1to2[9][6] = 1.24428437487405;
   fWeightMatrix1to2[10][6] = 0.967124297889969;
   fWeightMatrix1to2[11][6] = -1.04750747446701;
   fWeightMatrix1to2[12][6] = -0.744802377857549;
   fWeightMatrix1to2[13][6] = -0.15345293262215;
   fWeightMatrix1to2[0][7] = -1.07732781869741;
   fWeightMatrix1to2[1][7] = 0.448464075541374;
   fWeightMatrix1to2[2][7] = 1.99699903374339;
   fWeightMatrix1to2[3][7] = 1.33237735562059;
   fWeightMatrix1to2[4][7] = 1.75219414682549;
   fWeightMatrix1to2[5][7] = -1.08599875621963;
   fWeightMatrix1to2[6][7] = 1.07556144513177;
   fWeightMatrix1to2[7][7] = -2.16081254631784;
   fWeightMatrix1to2[8][7] = 0.761678281691669;
   fWeightMatrix1to2[9][7] = -1.60882037104148;
   fWeightMatrix1to2[10][7] = -1.84537251035154;
   fWeightMatrix1to2[11][7] = -0.0479348209304225;
   fWeightMatrix1to2[12][7] = 1.20433716073869;
   fWeightMatrix1to2[13][7] = 0.541947688647762;
   fWeightMatrix1to2[0][8] = 1.02797570403231;
   fWeightMatrix1to2[1][8] = 0.188321240028944;
   fWeightMatrix1to2[2][8] = -0.248223393802471;
   fWeightMatrix1to2[3][8] = -0.752610674919467;
   fWeightMatrix1to2[4][8] = -0.0338317577973704;
   fWeightMatrix1to2[5][8] = 1.65718740789405;
   fWeightMatrix1to2[6][8] = -1.59250277811683;
   fWeightMatrix1to2[7][8] = 0.242037941865135;
   fWeightMatrix1to2[8][8] = -1.4269718406351;
   fWeightMatrix1to2[9][8] = -0.625814044452005;
   fWeightMatrix1to2[10][8] = 0.0392915566147601;
   fWeightMatrix1to2[11][8] = 0.196965703364767;
   fWeightMatrix1to2[12][8] = -1.08223930674394;
   fWeightMatrix1to2[13][8] = 0.86299654307306;
   fWeightMatrix1to2[0][9] = 1.65529217764538;
   fWeightMatrix1to2[1][9] = 0.270379235938175;
   fWeightMatrix1to2[2][9] = -0.0806633709041639;
   fWeightMatrix1to2[3][9] = -0.930320742001;
   fWeightMatrix1to2[4][9] = -1.28966452769636;
   fWeightMatrix1to2[5][9] = -1.79397496327869;
   fWeightMatrix1to2[6][9] = 1.10422735330693;
   fWeightMatrix1to2[7][9] = -0.766970818642403;
   fWeightMatrix1to2[8][9] = -0.993181323787173;
   fWeightMatrix1to2[9][9] = 0.503754533935498;
   fWeightMatrix1to2[10][9] = -1.70652866342435;
   fWeightMatrix1to2[11][9] = -1.14875875003262;
   fWeightMatrix1to2[12][9] = -1.66563435380817;
   fWeightMatrix1to2[13][9] = 1.17916980353174;
   fWeightMatrix1to2[0][10] = -1.28871787913544;
   fWeightMatrix1to2[1][10] = -1.82894565366617;
   fWeightMatrix1to2[2][10] = -0.484520924078262;
   fWeightMatrix1to2[3][10] = -0.952954331651992;
   fWeightMatrix1to2[4][10] = -1.42498514793451;
   fWeightMatrix1to2[5][10] = 1.67791455886426;
   fWeightMatrix1to2[6][10] = -1.36645119383142;
   fWeightMatrix1to2[7][10] = -1.22476900126427;
   fWeightMatrix1to2[8][10] = 1.55459947390099;
   fWeightMatrix1to2[9][10] = 0.642520110404444;
   fWeightMatrix1to2[10][10] = 0.310598365876764;
   fWeightMatrix1to2[11][10] = 0.112828989686107;
   fWeightMatrix1to2[12][10] = 1.31690667310667;
   fWeightMatrix1to2[13][10] = 1.73819034150732;
   fWeightMatrix1to2[0][11] = 0.635289167347421;
   fWeightMatrix1to2[1][11] = -1.23523943358167;
   fWeightMatrix1to2[2][11] = -0.631146002991237;
   fWeightMatrix1to2[3][11] = -1.72601850680665;
   fWeightMatrix1to2[4][11] = 0.894016429123189;
   fWeightMatrix1to2[5][11] = 1.19023802056588;
   fWeightMatrix1to2[6][11] = 0.140254976161787;
   fWeightMatrix1to2[7][11] = 0.806308305695583;
   fWeightMatrix1to2[8][11] = 0.981419360970705;
   fWeightMatrix1to2[9][11] = 1.50910393630348;
   fWeightMatrix1to2[10][11] = -1.33548272675109;
   fWeightMatrix1to2[11][11] = 1.73488073527036;
   fWeightMatrix1to2[12][11] = 0.707549766046247;
   fWeightMatrix1to2[13][11] = -1.85388704026891;
   fWeightMatrix1to2[0][12] = -0.218015070084579;
   fWeightMatrix1to2[1][12] = -1.11598212704461;
   fWeightMatrix1to2[2][12] = 0.995407581308856;
   fWeightMatrix1to2[3][12] = 0.470972429553287;
   fWeightMatrix1to2[4][12] = 1.1887423998239;
   fWeightMatrix1to2[5][12] = 2.10969911254177;
   fWeightMatrix1to2[6][12] = -0.351523402224379;
   fWeightMatrix1to2[7][12] = 1.57705558602712;
   fWeightMatrix1to2[8][12] = 1.79930034618702;
   fWeightMatrix1to2[9][12] = 0.439817350667711;
   fWeightMatrix1to2[10][12] = -1.18661536862719;
   fWeightMatrix1to2[11][12] = 1.66824858881032;
   fWeightMatrix1to2[12][12] = -2.01592964856813;
   fWeightMatrix1to2[13][12] = 0.684273038391867;
   fWeightMatrix1to2[0][13] = 1.59034140994078;
   fWeightMatrix1to2[1][13] = -0.390125458367939;
   fWeightMatrix1to2[2][13] = -0.905626189402045;
   fWeightMatrix1to2[3][13] = -0.0608530372720412;
   fWeightMatrix1to2[4][13] = -1.49083681315563;
   fWeightMatrix1to2[5][13] = 0.143890139361981;
   fWeightMatrix1to2[6][13] = -1.96441956326913;
   fWeightMatrix1to2[7][13] = 0.44825827437294;
   fWeightMatrix1to2[8][13] = -0.349863450162508;
   fWeightMatrix1to2[9][13] = 1.58891127362986;
   fWeightMatrix1to2[10][13] = 1.23749413047627;
   fWeightMatrix1to2[11][13] = 1.66823004265919;
   fWeightMatrix1to2[12][13] = -0.479589893419315;
   fWeightMatrix1to2[13][13] = -0.531135561777154;
   fWeightMatrix1to2[0][14] = 0.44253213151975;
   fWeightMatrix1to2[1][14] = 1.64986046455447;
   fWeightMatrix1to2[2][14] = -1.73128230043511;
   fWeightMatrix1to2[3][14] = -1.38141715377314;
   fWeightMatrix1to2[4][14] = -0.513769935179113;
   fWeightMatrix1to2[5][14] = -1.38011453220782;
   fWeightMatrix1to2[6][14] = -1.64038146873042;
   fWeightMatrix1to2[7][14] = -1.25363696446162;
   fWeightMatrix1to2[8][14] = 0.609827828986366;
   fWeightMatrix1to2[9][14] = 0.210089651559255;
   fWeightMatrix1to2[10][14] = -1.94517094893767;
   fWeightMatrix1to2[11][14] = -1.9029267764036;
   fWeightMatrix1to2[12][14] = -0.168693740282275;
   fWeightMatrix1to2[13][14] = 1.62047537252436;
   fWeightMatrix1to2[0][15] = 1.73096092310493;
   fWeightMatrix1to2[1][15] = 1.34084945304867;
   fWeightMatrix1to2[2][15] = -0.746176774035231;
   fWeightMatrix1to2[3][15] = -1.94435880651737;
   fWeightMatrix1to2[4][15] = -0.2902137313194;
   fWeightMatrix1to2[5][15] = -1.58173592611159;
   fWeightMatrix1to2[6][15] = -1.64085034572368;
   fWeightMatrix1to2[7][15] = -0.4210118377779;
   fWeightMatrix1to2[8][15] = -0.148093656199342;
   fWeightMatrix1to2[9][15] = -1.60022706390343;
   fWeightMatrix1to2[10][15] = 1.5468606809234;
   fWeightMatrix1to2[11][15] = 1.23139272920201;
   fWeightMatrix1to2[12][15] = 0.186155884813163;
   fWeightMatrix1to2[13][15] = -0.735872620823855;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.000432853902159624;
   fWeightMatrix2to3[0][1] = 1.30690465560079;
   fWeightMatrix2to3[0][2] = -0.358744926643574;
   fWeightMatrix2to3[0][3] = 0.290133044201199;
   fWeightMatrix2to3[0][4] = 1.49987052553611;
   fWeightMatrix2to3[0][5] = 1.32800776932918;
   fWeightMatrix2to3[0][6] = -0.99944893348268;
   fWeightMatrix2to3[0][7] = 0.598894376773551;
   fWeightMatrix2to3[0][8] = -0.993090268261383;
   fWeightMatrix2to3[0][9] = 1.44231707361305;
   fWeightMatrix2to3[0][10] = 1.88369445359793;
   fWeightMatrix2to3[0][11] = -0.00604697806153935;
   fWeightMatrix2to3[0][12] = 0.000352235331835977;
   fWeightMatrix2to3[0][13] = -0.00567263587407443;
   fWeightMatrix2to3[0][14] = -0.59289616749162;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
