// Class: ReadMLP10_EC_1x1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Mon Aug 10 14:58:33 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 17820


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
ClusterParameters.start       ClusterParameters.start           'F'    [0,9.11687469482]
ClusterParameters.end         ClusterParameters.end             'F'    [6.94315624237,36.449131012]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,22.68309021]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.878392636776]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0150793632492,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.668472290039,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.22321242094,0.999999701977]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999996125698]
ClusterParameters.Es3/ClusterParameters.Etot_g   ClusterParameters.Es3_D_ClusterParameters.Etot_g     'F'    [0,0.659605383873]
ClusterParameters.Width       ClusterParameters.Width           'F'    [6.55900526047,43.7862434387]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.134515196085,0.875020623207]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [10,241]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [5831.41210938,1030628.75]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [0,21.7456951141]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP10_EC_1x1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP10_EC_1x1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP10_EC_1x1" ),
        fStatusIsClean( true ),
        fNvars( 14 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Es3/ClusterParameters.Etot_g", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 9.11687469482422;
      fVmin[1] = 6.94315624237061;
      fVmax[1] = 36.4491310119629;
      fVmin[2] = 0;
      fVmax[2] = 22.6830902099609;
      fVmin[3] = 0;
      fVmax[3] = 0.87839263677597;
      fVmin[4] = 0.0150793632492423;
      fVmax[4] = 1;
      fVmin[5] = 0.668472290039062;
      fVmax[5] = 1;
      fVmin[6] = 0.223212420940399;
      fVmax[6] = 0.999999701976776;
      fVmin[7] = 0;
      fVmax[7] = 0.99999612569809;
      fVmin[8] = 0;
      fVmax[8] = 0.659605383872986;
      fVmin[9] = 6.55900526046753;
      fVmax[9] = 43.7862434387207;
      fVmin[10] = 0.134515196084976;
      fVmax[10] = 0.875020623207092;
      fVmin[11] = 10;
      fVmax[11] = 241;
      fVmin[12] = 5831.412109375;
      fVmax[12] = 1030628.75;
      fVmin[13] = 0;
      fVmax[13] = 21.7456951141357;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP10_EC_1x1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[16][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[15][16];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][15];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP10_EC_1x1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 15; fWeights[2] = new double[15]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.505839472397999;
   fWeightMatrix0to1[1][0] = 1.94183106325352;
   fWeightMatrix0to1[2][0] = 0.973648909283064;
   fWeightMatrix0to1[3][0] = 1.82182833467171;
   fWeightMatrix0to1[4][0] = -1.97229663938366;
   fWeightMatrix0to1[5][0] = -1.45860082971234;
   fWeightMatrix0to1[6][0] = -0.50794634558224;
   fWeightMatrix0to1[7][0] = 2.10002591182052;
   fWeightMatrix0to1[8][0] = -1.3738484462836;
   fWeightMatrix0to1[9][0] = -1.02130650174928;
   fWeightMatrix0to1[10][0] = -2.02553930292616;
   fWeightMatrix0to1[11][0] = -0.074523744169725;
   fWeightMatrix0to1[12][0] = -1.26305683184604;
   fWeightMatrix0to1[13][0] = 0.434989135750663;
   fWeightMatrix0to1[14][0] = -0.635359313027551;
   fWeightMatrix0to1[0][1] = 0.597590763686775;
   fWeightMatrix0to1[1][1] = -0.364699516422893;
   fWeightMatrix0to1[2][1] = 1.67492981696983;
   fWeightMatrix0to1[3][1] = 0.250511663742284;
   fWeightMatrix0to1[4][1] = 0.711246120469122;
   fWeightMatrix0to1[5][1] = -0.329129177206568;
   fWeightMatrix0to1[6][1] = -0.411331697100128;
   fWeightMatrix0to1[7][1] = 0.619986761172959;
   fWeightMatrix0to1[8][1] = 0.233393702028235;
   fWeightMatrix0to1[9][1] = -1.35467548696781;
   fWeightMatrix0to1[10][1] = -0.046508661998038;
   fWeightMatrix0to1[11][1] = 0.740867981225832;
   fWeightMatrix0to1[12][1] = -1.04100280724646;
   fWeightMatrix0to1[13][1] = -1.7671353642097;
   fWeightMatrix0to1[14][1] = 0.0906238360839835;
   fWeightMatrix0to1[0][2] = 0.708367484588029;
   fWeightMatrix0to1[1][2] = 1.6714806153913;
   fWeightMatrix0to1[2][2] = -0.40517193082266;
   fWeightMatrix0to1[3][2] = -0.081284624225584;
   fWeightMatrix0to1[4][2] = -0.405136363388843;
   fWeightMatrix0to1[5][2] = -0.226944587811129;
   fWeightMatrix0to1[6][2] = -1.43328126169545;
   fWeightMatrix0to1[7][2] = 1.36407240551159;
   fWeightMatrix0to1[8][2] = -1.02087700069339;
   fWeightMatrix0to1[9][2] = 0.97109862274041;
   fWeightMatrix0to1[10][2] = 1.18874268056945;
   fWeightMatrix0to1[11][2] = 0.967590367714527;
   fWeightMatrix0to1[12][2] = 1.87087767637806;
   fWeightMatrix0to1[13][2] = 1.46001387627362;
   fWeightMatrix0to1[14][2] = -0.588382490782824;
   fWeightMatrix0to1[0][3] = -1.74066710464494;
   fWeightMatrix0to1[1][3] = 0.819804866139381;
   fWeightMatrix0to1[2][3] = 0.130600425390201;
   fWeightMatrix0to1[3][3] = 1.49766686094797;
   fWeightMatrix0to1[4][3] = 1.80233406030721;
   fWeightMatrix0to1[5][3] = 1.40317342846398;
   fWeightMatrix0to1[6][3] = 1.52845687001338;
   fWeightMatrix0to1[7][3] = -1.03334621641434;
   fWeightMatrix0to1[8][3] = 0.92919780869919;
   fWeightMatrix0to1[9][3] = -1.68671330788384;
   fWeightMatrix0to1[10][3] = -1.56959099984213;
   fWeightMatrix0to1[11][3] = -1.25309308870628;
   fWeightMatrix0to1[12][3] = -1.65494654016758;
   fWeightMatrix0to1[13][3] = 1.46361774568603;
   fWeightMatrix0to1[14][3] = 0.570216586416139;
   fWeightMatrix0to1[0][4] = -1.3944597085411;
   fWeightMatrix0to1[1][4] = 0.4859864365706;
   fWeightMatrix0to1[2][4] = -0.375009203698734;
   fWeightMatrix0to1[3][4] = 0.611837264587402;
   fWeightMatrix0to1[4][4] = 1.35787106424565;
   fWeightMatrix0to1[5][4] = -0.381636983716897;
   fWeightMatrix0to1[6][4] = 0.510842570778667;
   fWeightMatrix0to1[7][4] = -1.04725005349378;
   fWeightMatrix0to1[8][4] = 0.928656454242978;
   fWeightMatrix0to1[9][4] = -0.365530348816049;
   fWeightMatrix0to1[10][4] = -1.05179324117184;
   fWeightMatrix0to1[11][4] = -1.31190396176761;
   fWeightMatrix0to1[12][4] = 0.663170457889465;
   fWeightMatrix0to1[13][4] = 1.56193238226173;
   fWeightMatrix0to1[14][4] = 1.50077322846776;
   fWeightMatrix0to1[0][5] = -0.0839577776349968;
   fWeightMatrix0to1[1][5] = -1.95170901873499;
   fWeightMatrix0to1[2][5] = -2.04826570665144;
   fWeightMatrix0to1[3][5] = 0.940442489401091;
   fWeightMatrix0to1[4][5] = 0.710461693042933;
   fWeightMatrix0to1[5][5] = 2.05801153519454;
   fWeightMatrix0to1[6][5] = 0.577843867311156;
   fWeightMatrix0to1[7][5] = 0.722415729841082;
   fWeightMatrix0to1[8][5] = -0.377013138020374;
   fWeightMatrix0to1[9][5] = -0.484767865990645;
   fWeightMatrix0to1[10][5] = -0.430286288697458;
   fWeightMatrix0to1[11][5] = 0.453640541327943;
   fWeightMatrix0to1[12][5] = -1.33468609376496;
   fWeightMatrix0to1[13][5] = -1.74952393585465;
   fWeightMatrix0to1[14][5] = -1.3909953732586;
   fWeightMatrix0to1[0][6] = 0.0594851832812538;
   fWeightMatrix0to1[1][6] = 0.00974299424386997;
   fWeightMatrix0to1[2][6] = 1.46029306494561;
   fWeightMatrix0to1[3][6] = -1.43976612225644;
   fWeightMatrix0to1[4][6] = -1.34893550583507;
   fWeightMatrix0to1[5][6] = 1.75498829007396;
   fWeightMatrix0to1[6][6] = -0.565967471424768;
   fWeightMatrix0to1[7][6] = -2.04093498848771;
   fWeightMatrix0to1[8][6] = -0.948762406702682;
   fWeightMatrix0to1[9][6] = -0.0257613796106189;
   fWeightMatrix0to1[10][6] = -1.62872647272182;
   fWeightMatrix0to1[11][6] = -2.01127371763131;
   fWeightMatrix0to1[12][6] = 0.48626385812119;
   fWeightMatrix0to1[13][6] = 1.81119123151064;
   fWeightMatrix0to1[14][6] = -0.81016197957784;
   fWeightMatrix0to1[0][7] = 1.33312651149568;
   fWeightMatrix0to1[1][7] = -1.05431106069011;
   fWeightMatrix0to1[2][7] = -0.767545338281646;
   fWeightMatrix0to1[3][7] = 0.096192821291739;
   fWeightMatrix0to1[4][7] = 1.14565352514824;
   fWeightMatrix0to1[5][7] = -1.64363459412977;
   fWeightMatrix0to1[6][7] = 0.953492285955909;
   fWeightMatrix0to1[7][7] = 0.527193895365553;
   fWeightMatrix0to1[8][7] = 0.181587871823099;
   fWeightMatrix0to1[9][7] = -1.05590791366414;
   fWeightMatrix0to1[10][7] = 0.688865520960502;
   fWeightMatrix0to1[11][7] = -1.24841921941971;
   fWeightMatrix0to1[12][7] = -0.971697158997043;
   fWeightMatrix0to1[13][7] = 0.471939908354807;
   fWeightMatrix0to1[14][7] = -0.77534854028258;
   fWeightMatrix0to1[0][8] = -1.76614531481125;
   fWeightMatrix0to1[1][8] = 0.326009156326776;
   fWeightMatrix0to1[2][8] = -0.314792211947676;
   fWeightMatrix0to1[3][8] = 1.96520247539981;
   fWeightMatrix0to1[4][8] = 0.612060306215853;
   fWeightMatrix0to1[5][8] = -0.228829963875242;
   fWeightMatrix0to1[6][8] = -0.427161066222165;
   fWeightMatrix0to1[7][8] = 0.529327224118206;
   fWeightMatrix0to1[8][8] = -2.10994310666762;
   fWeightMatrix0to1[9][8] = 1.04416949630646;
   fWeightMatrix0to1[10][8] = -0.141625908668167;
   fWeightMatrix0to1[11][8] = -2.02837311197819;
   fWeightMatrix0to1[12][8] = 0.730210637863098;
   fWeightMatrix0to1[13][8] = -1.19209369470561;
   fWeightMatrix0to1[14][8] = -0.391753487213929;
   fWeightMatrix0to1[0][9] = 1.08207776901481;
   fWeightMatrix0to1[1][9] = 1.716741960375;
   fWeightMatrix0to1[2][9] = -1.87547836542621;
   fWeightMatrix0to1[3][9] = 0.365567970798;
   fWeightMatrix0to1[4][9] = 1.34695294470477;
   fWeightMatrix0to1[5][9] = 1.5955179597349;
   fWeightMatrix0to1[6][9] = -0.200149315771763;
   fWeightMatrix0to1[7][9] = -1.54738359551129;
   fWeightMatrix0to1[8][9] = -0.289282089724168;
   fWeightMatrix0to1[9][9] = -1.97233301779564;
   fWeightMatrix0to1[10][9] = 2.24524525221184;
   fWeightMatrix0to1[11][9] = 1.8081203557651;
   fWeightMatrix0to1[12][9] = -0.496894720093644;
   fWeightMatrix0to1[13][9] = -0.725779396485126;
   fWeightMatrix0to1[14][9] = -0.055560294825309;
   fWeightMatrix0to1[0][10] = -1.30854175681051;
   fWeightMatrix0to1[1][10] = 0.444421117277498;
   fWeightMatrix0to1[2][10] = 1.7156813029297;
   fWeightMatrix0to1[3][10] = -0.68411847086056;
   fWeightMatrix0to1[4][10] = -0.635905069991797;
   fWeightMatrix0to1[5][10] = 0.255911953874412;
   fWeightMatrix0to1[6][10] = 0.833898255495314;
   fWeightMatrix0to1[7][10] = 0.461370697974774;
   fWeightMatrix0to1[8][10] = 0.888250905394404;
   fWeightMatrix0to1[9][10] = -1.91427499043989;
   fWeightMatrix0to1[10][10] = 1.73042232385858;
   fWeightMatrix0to1[11][10] = 1.86872168363;
   fWeightMatrix0to1[12][10] = 0.371108820098658;
   fWeightMatrix0to1[13][10] = 0.333812285827094;
   fWeightMatrix0to1[14][10] = 1.02789602846771;
   fWeightMatrix0to1[0][11] = -0.687001340612514;
   fWeightMatrix0to1[1][11] = -0.54304393507459;
   fWeightMatrix0to1[2][11] = 1.08819915917245;
   fWeightMatrix0to1[3][11] = -0.917952502447535;
   fWeightMatrix0to1[4][11] = -0.548982559531525;
   fWeightMatrix0to1[5][11] = 1.50748650707856;
   fWeightMatrix0to1[6][11] = 1.36181000980688;
   fWeightMatrix0to1[7][11] = 0.112484254898661;
   fWeightMatrix0to1[8][11] = 1.22691128169758;
   fWeightMatrix0to1[9][11] = 1.83283994943658;
   fWeightMatrix0to1[10][11] = -2.07382977489818;
   fWeightMatrix0to1[11][11] = 0.00341052626532143;
   fWeightMatrix0to1[12][11] = 0.233551435088129;
   fWeightMatrix0to1[13][11] = 0.758090161731542;
   fWeightMatrix0to1[14][11] = -2.03007176050563;
   fWeightMatrix0to1[0][12] = -1.74722261942328;
   fWeightMatrix0to1[1][12] = 1.22720659310583;
   fWeightMatrix0to1[2][12] = 1.8650401794241;
   fWeightMatrix0to1[3][12] = -1.67569484170686;
   fWeightMatrix0to1[4][12] = -0.0644822955626076;
   fWeightMatrix0to1[5][12] = -0.68610203158332;
   fWeightMatrix0to1[6][12] = 0.131267171967145;
   fWeightMatrix0to1[7][12] = 2.09229821810158;
   fWeightMatrix0to1[8][12] = -0.72027610673673;
   fWeightMatrix0to1[9][12] = -0.690722504803378;
   fWeightMatrix0to1[10][12] = -0.752303162874959;
   fWeightMatrix0to1[11][12] = 0.631859872144719;
   fWeightMatrix0to1[12][12] = 1.74530379832646;
   fWeightMatrix0to1[13][12] = 1.03123615031976;
   fWeightMatrix0to1[14][12] = -0.131862176583028;
   fWeightMatrix0to1[0][13] = -0.821689667773883;
   fWeightMatrix0to1[1][13] = -1.90791301754654;
   fWeightMatrix0to1[2][13] = 1.01719245096777;
   fWeightMatrix0to1[3][13] = 0.544216883036524;
   fWeightMatrix0to1[4][13] = -1.82484480744598;
   fWeightMatrix0to1[5][13] = -0.720978115665531;
   fWeightMatrix0to1[6][13] = 0.162366029957116;
   fWeightMatrix0to1[7][13] = -0.0891294579705331;
   fWeightMatrix0to1[8][13] = -2.00811409504489;
   fWeightMatrix0to1[9][13] = 1.43524536467136;
   fWeightMatrix0to1[10][13] = 0.883873127640876;
   fWeightMatrix0to1[11][13] = -0.610236881540385;
   fWeightMatrix0to1[12][13] = -0.0289659023416502;
   fWeightMatrix0to1[13][13] = 1.57153014975072;
   fWeightMatrix0to1[14][13] = 1.03835799203789;
   fWeightMatrix0to1[0][14] = 0.832913908102519;
   fWeightMatrix0to1[1][14] = -0.249089255239789;
   fWeightMatrix0to1[2][14] = -2.04984217346204;
   fWeightMatrix0to1[3][14] = -0.977881558490454;
   fWeightMatrix0to1[4][14] = 1.07347569484097;
   fWeightMatrix0to1[5][14] = 1.5072035370699;
   fWeightMatrix0to1[6][14] = 0.867356837104683;
   fWeightMatrix0to1[7][14] = -0.474066991574113;
   fWeightMatrix0to1[8][14] = 2.5808428166287;
   fWeightMatrix0to1[9][14] = -1.86449232098958;
   fWeightMatrix0to1[10][14] = -1.03678760754223;
   fWeightMatrix0to1[11][14] = -0.0959962190206805;
   fWeightMatrix0to1[12][14] = -1.68365099670442;
   fWeightMatrix0to1[13][14] = 0.843407574270203;
   fWeightMatrix0to1[14][14] = 2.24114661354901;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.0523655391585;
   fWeightMatrix1to2[1][0] = 0.814754308767198;
   fWeightMatrix1to2[2][0] = -0.291628648550306;
   fWeightMatrix1to2[3][0] = -1.69510096363368;
   fWeightMatrix1to2[4][0] = -1.42846971178393;
   fWeightMatrix1to2[5][0] = 0.942085621697615;
   fWeightMatrix1to2[6][0] = -0.0286499598354888;
   fWeightMatrix1to2[7][0] = 1.24565137821985;
   fWeightMatrix1to2[8][0] = -1.17593713471764;
   fWeightMatrix1to2[9][0] = 1.35128097002156;
   fWeightMatrix1to2[10][0] = -1.82562432749588;
   fWeightMatrix1to2[11][0] = 0.795163867813306;
   fWeightMatrix1to2[12][0] = 0.124635182853917;
   fWeightMatrix1to2[13][0] = -1.12799980159262;
   fWeightMatrix1to2[0][1] = -1.5021809634338;
   fWeightMatrix1to2[1][1] = -1.99077366372537;
   fWeightMatrix1to2[2][1] = -0.321188303573854;
   fWeightMatrix1to2[3][1] = -1.95819799338953;
   fWeightMatrix1to2[4][1] = -0.969837998990875;
   fWeightMatrix1to2[5][1] = -1.59689086971002;
   fWeightMatrix1to2[6][1] = -0.0594944631884013;
   fWeightMatrix1to2[7][1] = -1.06598892949572;
   fWeightMatrix1to2[8][1] = -1.61400871275699;
   fWeightMatrix1to2[9][1] = 1.75896299540279;
   fWeightMatrix1to2[10][1] = -0.713887346741071;
   fWeightMatrix1to2[11][1] = 0.11556635021002;
   fWeightMatrix1to2[12][1] = -1.1644754169005;
   fWeightMatrix1to2[13][1] = -0.163864054765693;
   fWeightMatrix1to2[0][2] = 1.67912891965813;
   fWeightMatrix1to2[1][2] = 1.32039504550689;
   fWeightMatrix1to2[2][2] = -0.732034081113372;
   fWeightMatrix1to2[3][2] = -1.52316525187145;
   fWeightMatrix1to2[4][2] = -0.725976465004846;
   fWeightMatrix1to2[5][2] = -0.762392681886004;
   fWeightMatrix1to2[6][2] = -1.5386096547171;
   fWeightMatrix1to2[7][2] = 0.0530823319855566;
   fWeightMatrix1to2[8][2] = 0.413422861371826;
   fWeightMatrix1to2[9][2] = 2.16723952234002;
   fWeightMatrix1to2[10][2] = -0.189789245629164;
   fWeightMatrix1to2[11][2] = 0.306180585677866;
   fWeightMatrix1to2[12][2] = -0.644088786033675;
   fWeightMatrix1to2[13][2] = -2.33127915318387;
   fWeightMatrix1to2[0][3] = 1.31014798014249;
   fWeightMatrix1to2[1][3] = 1.20588662685549;
   fWeightMatrix1to2[2][3] = -0.71791700075017;
   fWeightMatrix1to2[3][3] = -1.14641798392548;
   fWeightMatrix1to2[4][3] = 1.36918140525417;
   fWeightMatrix1to2[5][3] = 1.26093866584113;
   fWeightMatrix1to2[6][3] = 0.362769582246347;
   fWeightMatrix1to2[7][3] = -0.477568165735133;
   fWeightMatrix1to2[8][3] = -0.294980930692694;
   fWeightMatrix1to2[9][3] = 1.79397634212787;
   fWeightMatrix1to2[10][3] = 1.10537599346441;
   fWeightMatrix1to2[11][3] = 0.99854832499217;
   fWeightMatrix1to2[12][3] = 0.188412901717491;
   fWeightMatrix1to2[13][3] = -0.0867352591734226;
   fWeightMatrix1to2[0][4] = -0.00496167311801147;
   fWeightMatrix1to2[1][4] = -1.55612244370722;
   fWeightMatrix1to2[2][4] = -0.592839328921327;
   fWeightMatrix1to2[3][4] = -1.60363556486417;
   fWeightMatrix1to2[4][4] = -1.28074750994796;
   fWeightMatrix1to2[5][4] = -1.51807288776187;
   fWeightMatrix1to2[6][4] = 1.68392881979078;
   fWeightMatrix1to2[7][4] = -1.76558323046539;
   fWeightMatrix1to2[8][4] = 1.32662733390785;
   fWeightMatrix1to2[9][4] = -1.47236375090786;
   fWeightMatrix1to2[10][4] = 1.297544645411;
   fWeightMatrix1to2[11][4] = -1.02130557623579;
   fWeightMatrix1to2[12][4] = 0.227367424737796;
   fWeightMatrix1to2[13][4] = 1.48473649596139;
   fWeightMatrix1to2[0][5] = -1.67749590166738;
   fWeightMatrix1to2[1][5] = 0.131911813189468;
   fWeightMatrix1to2[2][5] = 0.469362377768826;
   fWeightMatrix1to2[3][5] = -1.89420119878793;
   fWeightMatrix1to2[4][5] = -1.74150911863504;
   fWeightMatrix1to2[5][5] = -1.80483865494611;
   fWeightMatrix1to2[6][5] = -0.868198943178224;
   fWeightMatrix1to2[7][5] = 2.12317049684839;
   fWeightMatrix1to2[8][5] = -0.629414923633743;
   fWeightMatrix1to2[9][5] = -0.0666900891100592;
   fWeightMatrix1to2[10][5] = -1.00747941956141;
   fWeightMatrix1to2[11][5] = -1.23758584870335;
   fWeightMatrix1to2[12][5] = -1.61647668066279;
   fWeightMatrix1to2[13][5] = -0.647951812306777;
   fWeightMatrix1to2[0][6] = -0.655247109068898;
   fWeightMatrix1to2[1][6] = 0.181901333415239;
   fWeightMatrix1to2[2][6] = -1.17446554348756;
   fWeightMatrix1to2[3][6] = -1.2975773030057;
   fWeightMatrix1to2[4][6] = 1.56561427892746;
   fWeightMatrix1to2[5][6] = -0.233382708432977;
   fWeightMatrix1to2[6][6] = -0.372078436531956;
   fWeightMatrix1to2[7][6] = 1.70753814718793;
   fWeightMatrix1to2[8][6] = -1.56027471855068;
   fWeightMatrix1to2[9][6] = 1.08421327991007;
   fWeightMatrix1to2[10][6] = 0.00629820901978922;
   fWeightMatrix1to2[11][6] = -1.01798491554815;
   fWeightMatrix1to2[12][6] = -0.869236590772095;
   fWeightMatrix1to2[13][6] = -0.265477825962482;
   fWeightMatrix1to2[0][7] = -1.36773823151203;
   fWeightMatrix1to2[1][7] = 0.735013855730309;
   fWeightMatrix1to2[2][7] = 1.95885382867518;
   fWeightMatrix1to2[3][7] = 1.26448733102411;
   fWeightMatrix1to2[4][7] = 1.92564415802546;
   fWeightMatrix1to2[5][7] = -1.20414644139575;
   fWeightMatrix1to2[6][7] = 0.976157800958442;
   fWeightMatrix1to2[7][7] = -1.98828553058137;
   fWeightMatrix1to2[8][7] = 0.502493907366748;
   fWeightMatrix1to2[9][7] = -1.3431292474198;
   fWeightMatrix1to2[10][7] = -1.69441172842331;
   fWeightMatrix1to2[11][7] = -0.0147552684216855;
   fWeightMatrix1to2[12][7] = 1.16291476442529;
   fWeightMatrix1to2[13][7] = 0.317518036455557;
   fWeightMatrix1to2[0][8] = 1.31231481528413;
   fWeightMatrix1to2[1][8] = 0.0389703407861049;
   fWeightMatrix1to2[2][8] = -0.208247263470881;
   fWeightMatrix1to2[3][8] = -0.747792496469565;
   fWeightMatrix1to2[4][8] = -0.240408959373668;
   fWeightMatrix1to2[5][8] = 1.75828830990151;
   fWeightMatrix1to2[6][8] = -1.48249345328691;
   fWeightMatrix1to2[7][8] = 0.460062084117667;
   fWeightMatrix1to2[8][8] = -1.29392862788268;
   fWeightMatrix1to2[9][8] = -0.831878080202769;
   fWeightMatrix1to2[10][8] = -0.1895756298157;
   fWeightMatrix1to2[11][8] = 0.203377964641677;
   fWeightMatrix1to2[12][8] = -1.06402482871388;
   fWeightMatrix1to2[13][8] = 1.1496754554281;
   fWeightMatrix1to2[0][9] = 1.51829645502901;
   fWeightMatrix1to2[1][9] = 0.785887007194249;
   fWeightMatrix1to2[2][9] = -0.0217275276484013;
   fWeightMatrix1to2[3][9] = -0.960586631364483;
   fWeightMatrix1to2[4][9] = -1.12562037706694;
   fWeightMatrix1to2[5][9] = -1.29027514792081;
   fWeightMatrix1to2[6][9] = 1.14998291889396;
   fWeightMatrix1to2[7][9] = -0.820435521810833;
   fWeightMatrix1to2[8][9] = -1.64574575373612;
   fWeightMatrix1to2[9][9] = 0.838330534439626;
   fWeightMatrix1to2[10][9] = -1.54944325845192;
   fWeightMatrix1to2[11][9] = -1.04920226379788;
   fWeightMatrix1to2[12][9] = -1.75894456801953;
   fWeightMatrix1to2[13][9] = 0.682685391176601;
   fWeightMatrix1to2[0][10] = -1.6106841779608;
   fWeightMatrix1to2[1][10] = -1.49484145763698;
   fWeightMatrix1to2[2][10] = -0.625231690753192;
   fWeightMatrix1to2[3][10] = -1.00578598639828;
   fWeightMatrix1to2[4][10] = -1.52659357013139;
   fWeightMatrix1to2[5][10] = 1.75046498741165;
   fWeightMatrix1to2[6][10] = -1.39213845346772;
   fWeightMatrix1to2[7][10] = -1.36299344130624;
   fWeightMatrix1to2[8][10] = 2.22237964218343;
   fWeightMatrix1to2[9][10] = 0.444135356701703;
   fWeightMatrix1to2[10][10] = 0.674678073898229;
   fWeightMatrix1to2[11][10] = 0.145852600463675;
   fWeightMatrix1to2[12][10] = 1.18147803463813;
   fWeightMatrix1to2[13][10] = 1.67927904404315;
   fWeightMatrix1to2[0][11] = -0.103731037977474;
   fWeightMatrix1to2[1][11] = -0.839677137060549;
   fWeightMatrix1to2[2][11] = -0.742446405486092;
   fWeightMatrix1to2[3][11] = -1.82421220752142;
   fWeightMatrix1to2[4][11] = 0.935501240949632;
   fWeightMatrix1to2[5][11] = 1.2232463715153;
   fWeightMatrix1to2[6][11] = 0.107039257829248;
   fWeightMatrix1to2[7][11] = 1.0998447030225;
   fWeightMatrix1to2[8][11] = 1.94419049758327;
   fWeightMatrix1to2[9][11] = 1.31182381291692;
   fWeightMatrix1to2[10][11] = -1.62294877454054;
   fWeightMatrix1to2[11][11] = 1.78003456561462;
   fWeightMatrix1to2[12][11] = 0.92543167726595;
   fWeightMatrix1to2[13][11] = -1.82941743915307;
   fWeightMatrix1to2[0][12] = -0.593327209474844;
   fWeightMatrix1to2[1][12] = -1.02771746350865;
   fWeightMatrix1to2[2][12] = 0.984153460092551;
   fWeightMatrix1to2[3][12] = 0.375599127064501;
   fWeightMatrix1to2[4][12] = 1.27483674370268;
   fWeightMatrix1to2[5][12] = 2.37042492208901;
   fWeightMatrix1to2[6][12] = -0.388625375592159;
   fWeightMatrix1to2[7][12] = 1.55925403732446;
   fWeightMatrix1to2[8][12] = 1.34440356534308;
   fWeightMatrix1to2[9][12] = 0.405651611192403;
   fWeightMatrix1to2[10][12] = -0.883161872341995;
   fWeightMatrix1to2[11][12] = 1.76030512801791;
   fWeightMatrix1to2[12][12] = -1.9710325503612;
   fWeightMatrix1to2[13][12] = 0.259904782143443;
   fWeightMatrix1to2[0][13] = 1.81080932894543;
   fWeightMatrix1to2[1][13] = -0.933497133997491;
   fWeightMatrix1to2[2][13] = -0.814566528470463;
   fWeightMatrix1to2[3][13] = -0.178317180665297;
   fWeightMatrix1to2[4][13] = -1.41123889289191;
   fWeightMatrix1to2[5][13] = -0.00432873692556912;
   fWeightMatrix1to2[6][13] = -1.89621584305591;
   fWeightMatrix1to2[7][13] = 0.184142872688807;
   fWeightMatrix1to2[8][13] = 0.348204273255942;
   fWeightMatrix1to2[9][13] = 1.41221702002405;
   fWeightMatrix1to2[10][13] = 1.27780250018937;
   fWeightMatrix1to2[11][13] = 1.6118024913665;
   fWeightMatrix1to2[12][13] = -1.47337641121794;
   fWeightMatrix1to2[13][13] = -0.18112480505656;
   fWeightMatrix1to2[0][14] = 0.68737729452763;
   fWeightMatrix1to2[1][14] = 2.13947568040634;
   fWeightMatrix1to2[2][14] = -2.0026316895133;
   fWeightMatrix1to2[3][14] = -1.28294697773067;
   fWeightMatrix1to2[4][14] = -0.83139533128094;
   fWeightMatrix1to2[5][14] = -1.2626472386565;
   fWeightMatrix1to2[6][14] = -1.81157779628777;
   fWeightMatrix1to2[7][14] = -1.20660209908253;
   fWeightMatrix1to2[8][14] = 0.525470617597596;
   fWeightMatrix1to2[9][14] = -0.198092911412496;
   fWeightMatrix1to2[10][14] = -2.0041937028498;
   fWeightMatrix1to2[11][14] = -1.9663651176112;
   fWeightMatrix1to2[12][14] = 0.130564366452919;
   fWeightMatrix1to2[13][14] = 1.94054192440246;
   fWeightMatrix1to2[0][15] = 2.03465743152428;
   fWeightMatrix1to2[1][15] = 1.30839840868772;
   fWeightMatrix1to2[2][15] = -0.821563776668952;
   fWeightMatrix1to2[3][15] = -1.91927200105584;
   fWeightMatrix1to2[4][15] = -0.453421004154579;
   fWeightMatrix1to2[5][15] = -1.39300393825858;
   fWeightMatrix1to2[6][15] = -1.67418077901321;
   fWeightMatrix1to2[7][15] = -0.379215521515333;
   fWeightMatrix1to2[8][15] = -0.0991942162401586;
   fWeightMatrix1to2[9][15] = -1.81680548718356;
   fWeightMatrix1to2[10][15] = 1.47309896687006;
   fWeightMatrix1to2[11][15] = 1.18325371869417;
   fWeightMatrix1to2[12][15] = 0.210309686466443;
   fWeightMatrix1to2[13][15] = -0.242027894689121;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.469372912568814;
   fWeightMatrix2to3[0][1] = 0.424748686426229;
   fWeightMatrix2to3[0][2] = -0.173892614963;
   fWeightMatrix2to3[0][3] = 0.390381430130182;
   fWeightMatrix2to3[0][4] = 1.2141056025808;
   fWeightMatrix2to3[0][5] = 0.359394651065222;
   fWeightMatrix2to3[0][6] = -0.947017368556122;
   fWeightMatrix2to3[0][7] = 0.680230919936192;
   fWeightMatrix2to3[0][8] = -0.89374673415119;
   fWeightMatrix2to3[0][9] = 0.348486727877297;
   fWeightMatrix2to3[0][10] = 0.423744349951787;
   fWeightMatrix2to3[0][11] = 0.188906219146777;
   fWeightMatrix2to3[0][12] = -0.508162330945257;
   fWeightMatrix2to3[0][13] = 0.55309831288714;
   fWeightMatrix2to3[0][14] = -0.62093089495229;
}

inline double ReadMLP10_EC_1x1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP10_EC_1x1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP10_EC_1x1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP10_EC_1x1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
