// Class: ReadMLP10_B_1x1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 3.9.6         [198918]
ROOT Release   : 5.16/00       [331776]
Creator        : reinhard
Date           : Mon Aug 10 16:46:40 2009
Host           : Linux polui02.in2p3.fr 2.6.9-67.0.4.ELsmp #1 SMP Thu Jan 31 16:30:09 CST 2008 i686 i686 i386 GNU/Linux
Dir            : /grid_mnt/data2__polgrid/llr/ilc/reinhard/ILCSoft/TMVA/macros
Training events: 61936


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
Normalise: "True" [Normalise input variables]
V: "False" [Verbose mode]
H: "True" [Print classifier-specific help message]
NCycles: "500" [Number of training cycles]
HiddenLayers: "N+1,N" [Specification of hidden layer architecture (N stands for number of variables; any integers may also be used)]
NeuronType: "tanh" [Neuron activation function type]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
D: "False" [Use-decorrelated-variables flag (depreciated)]
VarTransform: "None" [Variable transformation method]
VarTransformType: "Signal" [Use signal or background events to derive for variable transformation (the transformation is applied on both types of, course)]
NbinsMVAPdf: "60" [Number of bins used for the PDFs of classifier outputs]
NsmoothMVAPdf: "2" [Number of smoothing iterations for classifier PDFs]
VerboseLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TxtWeightFilesOnly: "True" [If True: write all training results (weights) as text files (False: some are written in ROOT format)]
NeuronInputType: "sum" [Neuron input function type]
TrainingMethod: "BP" [Train with Back-Propagation (BP - default) or Genetic Algorithm (GA - slower and worse)]
LearningRate: "0.02" [ANN learning rate parameter]
DecayRate: "0.01" [Decay rate for learning parameter]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
ClusterParameters.start       ClusterParameters.start           'F'    [0,10.0751075745]
ClusterParameters.end         ClusterParameters.end             'F'    [3.20310044289,39.450428009]
ClusterParameters.depth       ClusterParameters.depth           'F'    [0,27.9440841675]
ClusterParameters.E1C/ClusterParameters.Etot_g   ClusterParameters.E1C_D_ClusterParameters.Etot_g     'F'    [0,0.951428174973]
ClusterParameters.E4C/ClusterParameters.Etot_g   ClusterParameters.E4C_D_ClusterParameters.Etot_g     'F'    [0.0744591131806,1]
ClusterParameters.E9C/ClusterParameters.Etot_g   ClusterParameters.E9C_D_ClusterParameters.Etot_g     'F'    [0.522128641605,1]
ClusterParameters.dirErr      ClusterParameters.dirErr          'F'    [0.00152583967429,1]
ClusterParameters.seedDirErr  ClusterParameters.seedDirErr      'F'    [0,0.999999940395]
ClusterParameters.Es3/ClusterParameters.Etot_g   ClusterParameters.Es3_D_ClusterParameters.Etot_g     'F'    [0,0.936360359192]
ClusterParameters.Width       ClusterParameters.Width           'F'    [2.3724257946,44.1146430969]
ClusterParameters.Eccentricity ClusterParameters.Eccentricity     'F'    [0.119588159025,0.943236231804]
ClusterParameters.nHits       ClusterParameters.nHits           'F'    [7,213]
ClusterParameters.Volume      ClusterParameters.Volume          'F'    [2987.97460938,2992573]
ClusterParameters.depth-ClusterParameters.start   ClusterParameters.depth_M_ClusterParameters.start     'F'    [-3.75506186485,27.3057765961]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;
};

#endif

class ReadMLP10_B_1x1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP10_B_1x1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP10_B_1x1" ),
        fStatusIsClean( true ),
        fNvars( 14 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "ClusterParameters.start", "ClusterParameters.end", "ClusterParameters.depth", "ClusterParameters.E1C/ClusterParameters.Etot_g", "ClusterParameters.E4C/ClusterParameters.Etot_g", "ClusterParameters.E9C/ClusterParameters.Etot_g", "ClusterParameters.dirErr", "ClusterParameters.seedDirErr", "ClusterParameters.Es3/ClusterParameters.Etot_g", "ClusterParameters.Width", "ClusterParameters.Eccentricity", "ClusterParameters.nHits", "ClusterParameters.Volume", "ClusterParameters.depth-ClusterParameters.start" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 10.0751075744629;
      fVmin[1] = 3.20310044288635;
      fVmax[1] = 39.4504280090332;
      fVmin[2] = 0;
      fVmax[2] = 27.9440841674805;
      fVmin[3] = 0;
      fVmax[3] = 0.951428174972534;
      fVmin[4] = 0.0744591131806374;
      fVmax[4] = 1;
      fVmin[5] = 0.522128641605377;
      fVmax[5] = 1;
      fVmin[6] = 0.00152583967428654;
      fVmax[6] = 1;
      fVmin[7] = 0;
      fVmax[7] = 0.999999940395355;
      fVmin[8] = 0;
      fVmax[8] = 0.936360359191895;
      fVmin[9] = 2.37242579460144;
      fVmax[9] = 44.1146430969238;
      fVmin[10] = 0.119588159024715;
      fVmax[10] = 0.943236231803894;
      fVmin[11] = 7;
      fVmax[11] = 213;
      fVmin[12] = 2987.974609375;
      fVmax[12] = 2992573;
      fVmin[13] = -3.75506186485291;
      fVmax[13] = 27.3057765960693;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP10_B_1x1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;
   bool fStatusIsClean;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[16][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[15][16];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][15];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP10_B_1x1::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 15; fWeights[2] = new double[15]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.300677322067736;
   fWeightMatrix0to1[1][0] = 1.90585451764175;
   fWeightMatrix0to1[2][0] = 0.960321342904923;
   fWeightMatrix0to1[3][0] = 1.09097900669743;
   fWeightMatrix0to1[4][0] = -2.12869776225167;
   fWeightMatrix0to1[5][0] = -1.55112465186351;
   fWeightMatrix0to1[6][0] = -0.313974556663434;
   fWeightMatrix0to1[7][0] = 2.26755259598349;
   fWeightMatrix0to1[8][0] = -1.79685785306641;
   fWeightMatrix0to1[9][0] = -0.604241146385375;
   fWeightMatrix0to1[10][0] = -1.05944862556297;
   fWeightMatrix0to1[11][0] = -0.174467481165101;
   fWeightMatrix0to1[12][0] = -1.15710794839481;
   fWeightMatrix0to1[13][0] = -0.746159850032621;
   fWeightMatrix0to1[14][0] = -0.238498499323943;
   fWeightMatrix0to1[0][1] = 0.676278853866136;
   fWeightMatrix0to1[1][1] = -0.521909601981961;
   fWeightMatrix0to1[2][1] = 1.82105070409982;
   fWeightMatrix0to1[3][1] = 0.198019405727455;
   fWeightMatrix0to1[4][1] = 0.944713190789737;
   fWeightMatrix0to1[5][1] = -0.0849490289717258;
   fWeightMatrix0to1[6][1] = 0.170505482688628;
   fWeightMatrix0to1[7][1] = 0.482971374439772;
   fWeightMatrix0to1[8][1] = 0.325358413612031;
   fWeightMatrix0to1[9][1] = -1.23508821181895;
   fWeightMatrix0to1[10][1] = -1.28185976972996;
   fWeightMatrix0to1[11][1] = 0.739854097754816;
   fWeightMatrix0to1[12][1] = -1.12922971684388;
   fWeightMatrix0to1[13][1] = -1.61779124846298;
   fWeightMatrix0to1[14][1] = 0.310906162921728;
   fWeightMatrix0to1[0][2] = 0.500880706459184;
   fWeightMatrix0to1[1][2] = 1.66535983023531;
   fWeightMatrix0to1[2][2] = -0.32405865325766;
   fWeightMatrix0to1[3][2] = -0.260471614843709;
   fWeightMatrix0to1[4][2] = -0.0640971182734286;
   fWeightMatrix0to1[5][2] = 0.0325141766003594;
   fWeightMatrix0to1[6][2] = -1.02207266369534;
   fWeightMatrix0to1[7][2] = 1.50672363679051;
   fWeightMatrix0to1[8][2] = -1.09784335032444;
   fWeightMatrix0to1[9][2] = 1.07596780876957;
   fWeightMatrix0to1[10][2] = 1.21521068911985;
   fWeightMatrix0to1[11][2] = 1.24356187155289;
   fWeightMatrix0to1[12][2] = 1.82896638806693;
   fWeightMatrix0to1[13][2] = 1.21489946034796;
   fWeightMatrix0to1[14][2] = -0.98474045436129;
   fWeightMatrix0to1[0][3] = -1.65831085777454;
   fWeightMatrix0to1[1][3] = 1.09337018100442;
   fWeightMatrix0to1[2][3] = -0.0212508340136533;
   fWeightMatrix0to1[3][3] = 1.87795556407801;
   fWeightMatrix0to1[4][3] = 0.972917899274793;
   fWeightMatrix0to1[5][3] = 1.4605884198551;
   fWeightMatrix0to1[6][3] = 0.773111167599884;
   fWeightMatrix0to1[7][3] = -1.18923355074151;
   fWeightMatrix0to1[8][3] = 1.02598378351681;
   fWeightMatrix0to1[9][3] = -1.43894468615745;
   fWeightMatrix0to1[10][3] = -0.195749258828258;
   fWeightMatrix0to1[11][3] = -1.67428651319653;
   fWeightMatrix0to1[12][3] = -1.66725143543341;
   fWeightMatrix0to1[13][3] = 1.2379302218437;
   fWeightMatrix0to1[14][3] = 0.77146506458885;
   fWeightMatrix0to1[0][4] = -1.19624272697681;
   fWeightMatrix0to1[1][4] = 0.230469488396525;
   fWeightMatrix0to1[2][4] = -0.386099561167176;
   fWeightMatrix0to1[3][4] = 0.475235155375499;
   fWeightMatrix0to1[4][4] = 1.98021928280327;
   fWeightMatrix0to1[5][4] = -0.304494780631375;
   fWeightMatrix0to1[6][4] = 0.25331584227725;
   fWeightMatrix0to1[7][4] = -1.15592425406319;
   fWeightMatrix0to1[8][4] = 0.746088384448394;
   fWeightMatrix0to1[9][4] = -0.716238806546663;
   fWeightMatrix0to1[10][4] = -1.63695091737513;
   fWeightMatrix0to1[11][4] = -2.70238290006212;
   fWeightMatrix0to1[12][4] = 0.622556645150025;
   fWeightMatrix0to1[13][4] = 1.05149980117856;
   fWeightMatrix0to1[14][4] = 2.02606665079479;
   fWeightMatrix0to1[0][5] = 0.109383067965429;
   fWeightMatrix0to1[1][5] = -2.17768648145606;
   fWeightMatrix0to1[2][5] = -1.88575360260328;
   fWeightMatrix0to1[3][5] = 0.650444205520035;
   fWeightMatrix0to1[4][5] = 0.729997415814389;
   fWeightMatrix0to1[5][5] = 1.94610830599096;
   fWeightMatrix0to1[6][5] = 1.01712378730916;
   fWeightMatrix0to1[7][5] = 0.655857143007746;
   fWeightMatrix0to1[8][5] = -0.450483893888765;
   fWeightMatrix0to1[9][5] = -0.992786349066453;
   fWeightMatrix0to1[10][5] = -0.021930546458958;
   fWeightMatrix0to1[11][5] = 1.00768522616613;
   fWeightMatrix0to1[12][5] = -1.40933780573172;
   fWeightMatrix0to1[13][5] = -1.39400284666209;
   fWeightMatrix0to1[14][5] = -1.71792757740759;
   fWeightMatrix0to1[0][6] = 0.227712658340585;
   fWeightMatrix0to1[1][6] = -0.407981489566708;
   fWeightMatrix0to1[2][6] = 1.74110381361437;
   fWeightMatrix0to1[3][6] = -1.73979859241562;
   fWeightMatrix0to1[4][6] = -0.828834835877893;
   fWeightMatrix0to1[5][6] = 1.69223525628748;
   fWeightMatrix0to1[6][6] = -0.541708541654708;
   fWeightMatrix0to1[7][6] = -1.89533121366113;
   fWeightMatrix0to1[8][6] = -1.09515594144342;
   fWeightMatrix0to1[9][6] = -0.100235694671046;
   fWeightMatrix0to1[10][6] = -1.98520063877135;
   fWeightMatrix0to1[11][6] = -1.38495734582334;
   fWeightMatrix0to1[12][6] = 0.736044262634255;
   fWeightMatrix0to1[13][6] = 2.14076039712744;
   fWeightMatrix0to1[14][6] = -1.28575888868347;
   fWeightMatrix0to1[0][7] = 1.2754020389751;
   fWeightMatrix0to1[1][7] = -0.974175644996208;
   fWeightMatrix0to1[2][7] = -0.922212604948964;
   fWeightMatrix0to1[3][7] = 0.141302868799467;
   fWeightMatrix0to1[4][7] = 0.723850724461803;
   fWeightMatrix0to1[5][7] = -1.71867473242042;
   fWeightMatrix0to1[6][7] = 0.137914773461277;
   fWeightMatrix0to1[7][7] = 0.266614870772632;
   fWeightMatrix0to1[8][7] = 0.463480872651372;
   fWeightMatrix0to1[9][7] = -1.40873906701537;
   fWeightMatrix0to1[10][7] = 0.219906432623739;
   fWeightMatrix0to1[11][7] = -0.107910513123832;
   fWeightMatrix0to1[12][7] = -0.956991783522255;
   fWeightMatrix0to1[13][7] = 0.590718706319239;
   fWeightMatrix0to1[14][7] = -0.567038747897735;
   fWeightMatrix0to1[0][8] = -1.86013883673586;
   fWeightMatrix0to1[1][8] = 0.238272801198566;
   fWeightMatrix0to1[2][8] = -0.355738584740791;
   fWeightMatrix0to1[3][8] = 2.00639526448648;
   fWeightMatrix0to1[4][8] = 0.207091361182463;
   fWeightMatrix0to1[5][8] = 0.180558280788;
   fWeightMatrix0to1[6][8] = 0.144028425829646;
   fWeightMatrix0to1[7][8] = 0.483538227997369;
   fWeightMatrix0to1[8][8] = -1.98933271428088;
   fWeightMatrix0to1[9][8] = 1.50898405876885;
   fWeightMatrix0to1[10][8] = -0.676534517610611;
   fWeightMatrix0to1[11][8] = -1.98786218048978;
   fWeightMatrix0to1[12][8] = 0.793839719844372;
   fWeightMatrix0to1[13][8] = -1.64409524558174;
   fWeightMatrix0to1[14][8] = 0.327084920810105;
   fWeightMatrix0to1[0][9] = 0.897498837496496;
   fWeightMatrix0to1[1][9] = 1.77977482051401;
   fWeightMatrix0to1[2][9] = -1.86097592373743;
   fWeightMatrix0to1[3][9] = 0.512613126593708;
   fWeightMatrix0to1[4][9] = 1.45625232694008;
   fWeightMatrix0to1[5][9] = 1.53487180013186;
   fWeightMatrix0to1[6][9] = 0.162890988731133;
   fWeightMatrix0to1[7][9] = -1.47164324926509;
   fWeightMatrix0to1[8][9] = -0.14085397880337;
   fWeightMatrix0to1[9][9] = -1.50494517983361;
   fWeightMatrix0to1[10][9] = 1.24318182628049;
   fWeightMatrix0to1[11][9] = 1.46968178298734;
   fWeightMatrix0to1[12][9] = -0.497722175682843;
   fWeightMatrix0to1[13][9] = -0.353122875352734;
   fWeightMatrix0to1[14][9] = -0.234735744581828;
   fWeightMatrix0to1[0][10] = -1.56239890410174;
   fWeightMatrix0to1[1][10] = 0.722831520719633;
   fWeightMatrix0to1[2][10] = 1.65119986023213;
   fWeightMatrix0to1[3][10] = -0.578747881194674;
   fWeightMatrix0to1[4][10] = -0.358646196310278;
   fWeightMatrix0to1[5][10] = 0.0469124526562152;
   fWeightMatrix0to1[6][10] = 0.806781116419082;
   fWeightMatrix0to1[7][10] = 0.526627742810175;
   fWeightMatrix0to1[8][10] = 0.847346317751147;
   fWeightMatrix0to1[9][10] = -1.38851094646177;
   fWeightMatrix0to1[10][10] = 0.316000635735493;
   fWeightMatrix0to1[11][10] = 1.02765946081404;
   fWeightMatrix0to1[12][10] = 0.376577168687642;
   fWeightMatrix0to1[13][10] = 0.358344093042217;
   fWeightMatrix0to1[14][10] = 0.478593204149876;
   fWeightMatrix0to1[0][11] = -0.579205252077668;
   fWeightMatrix0to1[1][11] = -0.541084538742909;
   fWeightMatrix0to1[2][11] = 0.985952778416028;
   fWeightMatrix0to1[3][11] = -0.983882186072943;
   fWeightMatrix0to1[4][11] = -0.622722441189457;
   fWeightMatrix0to1[5][11] = 1.55853709166681;
   fWeightMatrix0to1[6][11] = 1.60741228091772;
   fWeightMatrix0to1[7][11] = 0.039964497192173;
   fWeightMatrix0to1[8][11] = 1.42302292023095;
   fWeightMatrix0to1[9][11] = 1.92336350889195;
   fWeightMatrix0to1[10][11] = -3.11127369427704;
   fWeightMatrix0to1[11][11] = -0.704782983319908;
   fWeightMatrix0to1[12][11] = 0.0578296348469137;
   fWeightMatrix0to1[13][11] = 0.361061768378467;
   fWeightMatrix0to1[14][11] = -1.47324815494729;
   fWeightMatrix0to1[0][12] = -1.84383869635876;
   fWeightMatrix0to1[1][12] = 1.27880698713676;
   fWeightMatrix0to1[2][12] = 1.74008615234882;
   fWeightMatrix0to1[3][12] = -1.60768396302007;
   fWeightMatrix0to1[4][12] = -0.648058975394857;
   fWeightMatrix0to1[5][12] = -0.672904418513496;
   fWeightMatrix0to1[6][12] = 0.341350912035949;
   fWeightMatrix0to1[7][12] = 2.17418962550526;
   fWeightMatrix0to1[8][12] = -0.670520254349889;
   fWeightMatrix0to1[9][12] = -0.180322351557143;
   fWeightMatrix0to1[10][12] = -1.27869765083648;
   fWeightMatrix0to1[11][12] = 1.36755467650078;
   fWeightMatrix0to1[12][12] = 1.72052727240298;
   fWeightMatrix0to1[13][12] = 0.870251236965754;
   fWeightMatrix0to1[14][12] = 0.131636560312941;
   fWeightMatrix0to1[0][13] = -1.02297993568931;
   fWeightMatrix0to1[1][13] = -1.90038725873248;
   fWeightMatrix0to1[2][13] = 1.04871983617279;
   fWeightMatrix0to1[3][13] = 0.615665224792765;
   fWeightMatrix0to1[4][13] = -1.69393797961262;
   fWeightMatrix0to1[5][13] = -0.411037846457246;
   fWeightMatrix0to1[6][13] = 0.503400388259363;
   fWeightMatrix0to1[7][13] = -0.0946730814416901;
   fWeightMatrix0to1[8][13] = -1.813898442683;
   fWeightMatrix0to1[9][13] = 1.44435099006663;
   fWeightMatrix0to1[10][13] = 0.616673530795911;
   fWeightMatrix0to1[11][13] = -0.274703466360205;
   fWeightMatrix0to1[12][13] = -0.174803168500036;
   fWeightMatrix0to1[13][13] = 1.65364401242193;
   fWeightMatrix0to1[14][13] = 0.707113083015602;
   fWeightMatrix0to1[0][14] = 0.796640542581564;
   fWeightMatrix0to1[1][14] = -0.418469132850216;
   fWeightMatrix0to1[2][14] = -1.81288267146014;
   fWeightMatrix0to1[3][14] = -1.03368670107836;
   fWeightMatrix0to1[4][14] = 2.14789097786428;
   fWeightMatrix0to1[5][14] = 1.41913697153715;
   fWeightMatrix0to1[6][14] = 0.933658108385714;
   fWeightMatrix0to1[7][14] = -0.395213358921141;
   fWeightMatrix0to1[8][14] = 2.38938774167818;
   fWeightMatrix0to1[9][14] = -2.16150004837831;
   fWeightMatrix0to1[10][14] = -1.06340664073871;
   fWeightMatrix0to1[11][14] = -0.286282396104896;
   fWeightMatrix0to1[12][14] = -1.5281564037928;
   fWeightMatrix0to1[13][14] = 1.4115461186786;
   fWeightMatrix0to1[14][14] = 1.80542269428383;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.09303125814203;
   fWeightMatrix1to2[1][0] = 0.960758504345452;
   fWeightMatrix1to2[2][0] = -0.22948292267423;
   fWeightMatrix1to2[3][0] = -1.65808150950464;
   fWeightMatrix1to2[4][0] = -1.25019908619786;
   fWeightMatrix1to2[5][0] = 0.703009724334876;
   fWeightMatrix1to2[6][0] = -0.0441541124838786;
   fWeightMatrix1to2[7][0] = 1.14463788842073;
   fWeightMatrix1to2[8][0] = -1.31008385405232;
   fWeightMatrix1to2[9][0] = 1.49225483492819;
   fWeightMatrix1to2[10][0] = -1.61013364631617;
   fWeightMatrix1to2[11][0] = 0.82770774521305;
   fWeightMatrix1to2[12][0] = 0.107653929089918;
   fWeightMatrix1to2[13][0] = -1.85084860995085;
   fWeightMatrix1to2[0][1] = -1.44665372894943;
   fWeightMatrix1to2[1][1] = -2.00749442927436;
   fWeightMatrix1to2[2][1] = -0.311119436102918;
   fWeightMatrix1to2[3][1] = -1.82113331617255;
   fWeightMatrix1to2[4][1] = -1.35899521523307;
   fWeightMatrix1to2[5][1] = -1.55699426499363;
   fWeightMatrix1to2[6][1] = 0.141355389900962;
   fWeightMatrix1to2[7][1] = -1.670934313493;
   fWeightMatrix1to2[8][1] = -1.44488103505254;
   fWeightMatrix1to2[9][1] = 1.64487712008915;
   fWeightMatrix1to2[10][1] = -1.05279830145784;
   fWeightMatrix1to2[11][1] = 0.189316238267296;
   fWeightMatrix1to2[12][1] = -1.03653202269662;
   fWeightMatrix1to2[13][1] = 0.542372385592548;
   fWeightMatrix1to2[0][2] = 1.71416889800662;
   fWeightMatrix1to2[1][2] = 1.17738059821215;
   fWeightMatrix1to2[2][2] = -0.773509639542638;
   fWeightMatrix1to2[3][2] = -1.43941917893405;
   fWeightMatrix1to2[4][2] = -0.85946576494287;
   fWeightMatrix1to2[5][2] = -0.542847746846072;
   fWeightMatrix1to2[6][2] = -1.47649384752679;
   fWeightMatrix1to2[7][2] = 0.289990781916571;
   fWeightMatrix1to2[8][2] = 0.451605575756233;
   fWeightMatrix1to2[9][2] = 2.11829289671245;
   fWeightMatrix1to2[10][2] = -0.524476545343326;
   fWeightMatrix1to2[11][2] = 0.272776183040882;
   fWeightMatrix1to2[12][2] = -0.526913102930324;
   fWeightMatrix1to2[13][2] = -1.62676436793248;
   fWeightMatrix1to2[0][3] = 1.14454290532913;
   fWeightMatrix1to2[1][3] = 1.14728570422998;
   fWeightMatrix1to2[2][3] = -0.763885312370877;
   fWeightMatrix1to2[3][3] = -0.937579966060908;
   fWeightMatrix1to2[4][3] = 1.04177789159437;
   fWeightMatrix1to2[5][3] = 1.38532547683394;
   fWeightMatrix1to2[6][3] = 0.487387979408674;
   fWeightMatrix1to2[7][3] = -0.717595128407898;
   fWeightMatrix1to2[8][3] = -0.14170188911197;
   fWeightMatrix1to2[9][3] = 1.62984800414656;
   fWeightMatrix1to2[10][3] = 0.823735449294679;
   fWeightMatrix1to2[11][3] = 0.999373084014298;
   fWeightMatrix1to2[12][3] = -0.036451809331329;
   fWeightMatrix1to2[13][3] = 0.585559619966118;
   fWeightMatrix1to2[0][4] = -0.109658832132261;
   fWeightMatrix1to2[1][4] = -1.26926182924062;
   fWeightMatrix1to2[2][4] = -0.65165584647219;
   fWeightMatrix1to2[3][4] = -1.84261308089642;
   fWeightMatrix1to2[4][4] = -1.51528223423972;
   fWeightMatrix1to2[5][4] = -1.75829235901325;
   fWeightMatrix1to2[6][4] = 1.6116538280458;
   fWeightMatrix1to2[7][4] = -1.74996950276236;
   fWeightMatrix1to2[8][4] = 1.48406224362773;
   fWeightMatrix1to2[9][4] = -1.77762179579358;
   fWeightMatrix1to2[10][4] = 1.30922493701236;
   fWeightMatrix1to2[11][4] = -1.12778290332478;
   fWeightMatrix1to2[12][4] = 0.457007526576276;
   fWeightMatrix1to2[13][4] = 0.55142353422801;
   fWeightMatrix1to2[0][5] = -1.69592437823696;
   fWeightMatrix1to2[1][5] = 0.325751346947345;
   fWeightMatrix1to2[2][5] = 0.530062098550282;
   fWeightMatrix1to2[3][5] = -1.89162733193094;
   fWeightMatrix1to2[4][5] = -1.62708849969848;
   fWeightMatrix1to2[5][5] = -1.67492973831392;
   fWeightMatrix1to2[6][5] = -0.96443764420358;
   fWeightMatrix1to2[7][5] = 1.93841282805989;
   fWeightMatrix1to2[8][5] = -0.732606292491044;
   fWeightMatrix1to2[9][5] = 0.0559466414485343;
   fWeightMatrix1to2[10][5] = -0.731924840585714;
   fWeightMatrix1to2[11][5] = -1.14394499299048;
   fWeightMatrix1to2[12][5] = -1.74712585983265;
   fWeightMatrix1to2[13][5] = -1.22038917832948;
   fWeightMatrix1to2[0][6] = -1.04639607720543;
   fWeightMatrix1to2[1][6] = 0.0501572243888619;
   fWeightMatrix1to2[2][6] = -1.29511800459583;
   fWeightMatrix1to2[3][6] = -1.34029988365923;
   fWeightMatrix1to2[4][6] = 1.62457285527665;
   fWeightMatrix1to2[5][6] = -0.407848952080406;
   fWeightMatrix1to2[6][6] = -0.281809078977276;
   fWeightMatrix1to2[7][6] = 1.45470164432821;
   fWeightMatrix1to2[8][6] = -1.52675511350722;
   fWeightMatrix1to2[9][6] = 1.08104553687005;
   fWeightMatrix1to2[10][6] = 0.858011289732582;
   fWeightMatrix1to2[11][6] = -1.19732052007162;
   fWeightMatrix1to2[12][6] = -1.03275340844052;
   fWeightMatrix1to2[13][6] = -0.319339891855435;
   fWeightMatrix1to2[0][7] = -1.37800365484925;
   fWeightMatrix1to2[1][7] = 0.622629240353337;
   fWeightMatrix1to2[2][7] = 1.98203465999407;
   fWeightMatrix1to2[3][7] = 1.37975306663962;
   fWeightMatrix1to2[4][7] = 1.85888059008784;
   fWeightMatrix1to2[5][7] = -1.14295134090276;
   fWeightMatrix1to2[6][7] = 1.09372255911855;
   fWeightMatrix1to2[7][7] = -1.88764588778002;
   fWeightMatrix1to2[8][7] = 0.704382241766515;
   fWeightMatrix1to2[9][7] = -1.47063000886536;
   fWeightMatrix1to2[10][7] = -1.89809539856271;
   fWeightMatrix1to2[11][7] = -0.105281035834911;
   fWeightMatrix1to2[12][7] = 1.26233783029857;
   fWeightMatrix1to2[13][7] = 0.630549517645182;
   fWeightMatrix1to2[0][8] = 1.25366080191183;
   fWeightMatrix1to2[1][8] = -0.305107235484314;
   fWeightMatrix1to2[2][8] = -0.23302988116116;
   fWeightMatrix1to2[3][8] = -0.938909503201862;
   fWeightMatrix1to2[4][8] = -0.0950012567706131;
   fWeightMatrix1to2[5][8] = 1.51999076613453;
   fWeightMatrix1to2[6][8] = -1.43818656237718;
   fWeightMatrix1to2[7][8] = 0.215591966563161;
   fWeightMatrix1to2[8][8] = -1.38377394623676;
   fWeightMatrix1to2[9][8] = -0.789129079388393;
   fWeightMatrix1to2[10][8] = 0.0671323358515349;
   fWeightMatrix1to2[11][8] = 0.0944552101325205;
   fWeightMatrix1to2[12][8] = -1.03187434938786;
   fWeightMatrix1to2[13][8] = 0.726593421048595;
   fWeightMatrix1to2[0][9] = 1.47976413051305;
   fWeightMatrix1to2[1][9] = 0.720130896492833;
   fWeightMatrix1to2[2][9] = -0.0432541326311419;
   fWeightMatrix1to2[3][9] = -0.854979751089455;
   fWeightMatrix1to2[4][9] = -1.26742519516056;
   fWeightMatrix1to2[5][9] = -1.35493531818013;
   fWeightMatrix1to2[6][9] = 1.19276842501987;
   fWeightMatrix1to2[7][9] = -0.481420759126041;
   fWeightMatrix1to2[8][9] = -1.02229816917005;
   fWeightMatrix1to2[9][9] = 0.711427933007201;
   fWeightMatrix1to2[10][9] = -1.87836591540627;
   fWeightMatrix1to2[11][9] = -1.11613390623051;
   fWeightMatrix1to2[12][9] = -1.55799064480933;
   fWeightMatrix1to2[13][9] = 1.31369997525038;
   fWeightMatrix1to2[0][10] = -1.75312055618723;
   fWeightMatrix1to2[1][10] = -1.73248478354736;
   fWeightMatrix1to2[2][10] = -0.601113448707158;
   fWeightMatrix1to2[3][10] = -0.956982542900023;
   fWeightMatrix1to2[4][10] = -1.20379763132544;
   fWeightMatrix1to2[5][10] = 1.45379234324435;
   fWeightMatrix1to2[6][10] = -1.29815998414195;
   fWeightMatrix1to2[7][10] = -1.75601639541061;
   fWeightMatrix1to2[8][10] = 1.82647185636878;
   fWeightMatrix1to2[9][10] = 0.356599049356011;
   fWeightMatrix1to2[10][10] = 0.410506945724673;
   fWeightMatrix1to2[11][10] = 0.328900200441195;
   fWeightMatrix1to2[12][10] = 1.57638450364829;
   fWeightMatrix1to2[13][10] = 1.95488540439279;
   fWeightMatrix1to2[0][11] = 0.258822473004522;
   fWeightMatrix1to2[1][11] = -1.34376429730199;
   fWeightMatrix1to2[2][11] = -0.741397920828252;
   fWeightMatrix1to2[3][11] = -1.73591707664409;
   fWeightMatrix1to2[4][11] = 0.975479548399038;
   fWeightMatrix1to2[5][11] = 1.28821711095672;
   fWeightMatrix1to2[6][11] = 0.148617805092573;
   fWeightMatrix1to2[7][11] = 1.29848268661336;
   fWeightMatrix1to2[8][11] = 0.888289775207292;
   fWeightMatrix1to2[9][11] = 1.43055326741266;
   fWeightMatrix1to2[10][11] = -1.237488747857;
   fWeightMatrix1to2[11][11] = 2.09459398977624;
   fWeightMatrix1to2[12][11] = 2.77453935445709;
   fWeightMatrix1to2[13][11] = -1.91399460960273;
   fWeightMatrix1to2[0][12] = -0.467142349577088;
   fWeightMatrix1to2[1][12] = -1.07384658268884;
   fWeightMatrix1to2[2][12] = 1.02251216198379;
   fWeightMatrix1to2[3][12] = 0.507691193659195;
   fWeightMatrix1to2[4][12] = 1.22339071391492;
   fWeightMatrix1to2[5][12] = 2.15647114304844;
   fWeightMatrix1to2[6][12] = -0.271740991777787;
   fWeightMatrix1to2[7][12] = 1.80593615717868;
   fWeightMatrix1to2[8][12] = 1.85729558924224;
   fWeightMatrix1to2[9][12] = 0.425575272961849;
   fWeightMatrix1to2[10][12] = -1.31080523159165;
   fWeightMatrix1to2[11][12] = 1.70881340682881;
   fWeightMatrix1to2[12][12] = -1.96343395710254;
   fWeightMatrix1to2[13][12] = 0.873430671419317;
   fWeightMatrix1to2[0][13] = 1.7506848745665;
   fWeightMatrix1to2[1][13] = -0.189706233330912;
   fWeightMatrix1to2[2][13] = -0.900259090063271;
   fWeightMatrix1to2[3][13] = -0.103671069652365;
   fWeightMatrix1to2[4][13] = -1.50190102879953;
   fWeightMatrix1to2[5][13] = 0.560563438984666;
   fWeightMatrix1to2[6][13] = -2.02076234449151;
   fWeightMatrix1to2[7][13] = 0.00090380540576119;
   fWeightMatrix1to2[8][13] = -0.373186018241885;
   fWeightMatrix1to2[9][13] = 1.46651757834188;
   fWeightMatrix1to2[10][13] = 1.16882659833358;
   fWeightMatrix1to2[11][13] = 1.51366295448245;
   fWeightMatrix1to2[12][13] = -0.837622883761956;
   fWeightMatrix1to2[13][13] = -0.41913535703465;
   fWeightMatrix1to2[0][14] = 0.462838012356957;
   fWeightMatrix1to2[1][14] = 1.7920077478739;
   fWeightMatrix1to2[2][14] = -1.8087369486427;
   fWeightMatrix1to2[3][14] = -1.41751621919067;
   fWeightMatrix1to2[4][14] = -0.594754374845139;
   fWeightMatrix1to2[5][14] = -2.08885801690181;
   fWeightMatrix1to2[6][14] = -1.73978839915559;
   fWeightMatrix1to2[7][14] = -1.53013437925031;
   fWeightMatrix1to2[8][14] = 0.90712299089767;
   fWeightMatrix1to2[9][14] = 0.00149058781210329;
   fWeightMatrix1to2[10][14] = -1.77746213898323;
   fWeightMatrix1to2[11][14] = -1.65716180995914;
   fWeightMatrix1to2[12][14] = -0.272494678469761;
   fWeightMatrix1to2[13][14] = 1.49774967015863;
   fWeightMatrix1to2[0][15] = 1.99041220111953;
   fWeightMatrix1to2[1][15] = 1.49038615066201;
   fWeightMatrix1to2[2][15] = -0.75368720994218;
   fWeightMatrix1to2[3][15] = -2.00976041926863;
   fWeightMatrix1to2[4][15] = -0.319668389903602;
   fWeightMatrix1to2[5][15] = -1.61487787012287;
   fWeightMatrix1to2[6][15] = -1.77303241090967;
   fWeightMatrix1to2[7][15] = -0.598547040792015;
   fWeightMatrix1to2[8][15] = -0.159499980872474;
   fWeightMatrix1to2[9][15] = -1.68539506234502;
   fWeightMatrix1to2[10][15] = 1.73594489137188;
   fWeightMatrix1to2[11][15] = 1.2190331821672;
   fWeightMatrix1to2[12][15] = 0.136221565354609;
   fWeightMatrix1to2[13][15] = -0.923233532564549;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.034407786053902;
   fWeightMatrix2to3[0][1] = 0.834423317249376;
   fWeightMatrix2to3[0][2] = -0.0565677488929913;
   fWeightMatrix2to3[0][3] = 0.707501050447299;
   fWeightMatrix2to3[0][4] = 1.36881333321399;
   fWeightMatrix2to3[0][5] = 0.519082170781808;
   fWeightMatrix2to3[0][6] = -0.613721714867727;
   fWeightMatrix2to3[0][7] = 0.838641820827525;
   fWeightMatrix2to3[0][8] = -0.011610212579322;
   fWeightMatrix2to3[0][9] = 1.27370828184205;
   fWeightMatrix2to3[0][10] = 1.87955934144693;
   fWeightMatrix2to3[0][11] = -0.322492123393832;
   fWeightMatrix2to3[0][12] = -0.375547533963974;
   fWeightMatrix2to3[0][13] = -0.627208322097815;
   fWeightMatrix2to3[0][14] = -0.656602759430696;
}

inline double ReadMLP10_B_1x1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
   }

   return fWeights[3][0];
}

double ReadMLP10_B_1x1::ActivationFnc(double x) const
{
   // hyperbolic tan
   return tanh(x);
}
 
   
// Clean up
inline void ReadMLP10_B_1x1::Clear() 
{
   // nothing to clear
}
inline double ReadMLP10_B_1x1::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!fStatusIsClean) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
      retval = 0;
   }
   else {
      if (IsNormalised()) {
         // normalise variables
         std::vector<double> iV;
         int ivar = 0;
         for (std::vector<double>::const_iterator varIt = inputValues.begin();
              varIt != inputValues.end(); varIt++, ivar++) {
            iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
         }
         retval = GetMvaValue__( iV );
      }
      else {
         retval = GetMvaValue__( inputValues );
      }
   }

   return retval;
}
